//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Associated_Document
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public Nullable<int> document_ID { get; set; }
        public Nullable<int> Rev { get; set; }
        public string Title { get; set; }
        public string document_ID_Title { get; set; }
    }
}
