//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment_Mst
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public Nullable<int> employeeID { get; set; }
        public Nullable<int> userid { get; set; }
        public string attached_file_name { get; set; }
        public Nullable<System.DateTime> attachment_date { get; set; }
        public string file_name { get; set; }
        public string title { get; set; }
        public string approval { get; set; }
        public string attachment_Type { get; set; }
        public Nullable<int> EPO_no { get; set; }
    }
}
