//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAcct
    {
        public string Company { get; set; }
        public string BankAcctID { get; set; }
        public string Description { get; set; }
        public string CheckingAccount { get; set; }
        public bool Closed { get; set; }
        public decimal OpeningBalance { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public decimal ClosingBalance { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public string BankRoutingNum { get; set; }
        public int BankCheckDigit { get; set; }
        public string BankName { get; set; }
        public string ServClassCode { get; set; }
        public string EntryClassCode { get; set; }
        public string CDJournalCode { get; set; }
        public string PRJournalCode { get; set; }
        public string CRJournalCode { get; set; }
        public string BKJournalCode { get; set; }
        public string BankSlip { get; set; }
        public bool ExportDecimalPoint { get; set; }
        public string CurrencyCode { get; set; }
        public string BankCompID { get; set; }
        public bool DebNoteOnly { get; set; }
        public bool ReconciledBalance { get; set; }
        public bool UsePendAcct { get; set; }
        public string BankIdentifier { get; set; }
        public string BankBranchCode { get; set; }
        public string IBANCode { get; set; }
        public bool APPaymentUseBankAvg { get; set; }
        public string PayerRef { get; set; }
        public string TaxPayerID { get; set; }
        public int NextPINum { get; set; }
        public string TaxRegReason { get; set; }
        public int NumPIDigits { get; set; }
        public string CorrespAccount { get; set; }
        public string LocalBIC { get; set; }
        public string TypeCode { get; set; }
        public string TransferPersonName { get; set; }
        public string TransferPersonCode { get; set; }
        public string AccountType { get; set; }
        public decimal LOCLimit { get; set; }
        public string LegalName { get; set; }
        public decimal FloatAmt { get; set; }
        public decimal DocLOCLimit { get; set; }
        public decimal Rpt1LOCLimit { get; set; }
        public decimal Rpt2LOCLimit { get; set; }
        public decimal Rpt3LOCLimit { get; set; }
        public bool AutoStatementImport { get; set; }
        public bool AutoMatchStatement { get; set; }
        public bool AutoRecDocuments { get; set; }
        public int EFTHeadUID { get; set; }
        public bool AutoRetrieve { get; set; }
        public bool FilterByLine { get; set; }
        public string CreditorID { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public bool AutoRcgARRefNum { get; set; }
        public bool AutoRcgARCustomer { get; set; }
        public bool AutoRcgARTranDate { get; set; }
        public bool AutoRcgAPRefNum { get; set; }
        public bool AutoRcgAPSupplier { get; set; }
        public bool AutoRcgAPTranDate { get; set; }
        public bool AutoRcgUnknownTran { get; set; }
        public string CHDTAID { get; set; }
        public string CHISRPartyID { get; set; }
        public string BankType { get; set; }
        public bool AutoCashMovement { get; set; }
        public string ParamCode { get; set; }
        public bool AutoOnAccountReceipt { get; set; }
        public bool AutoInvoicePayment { get; set; }
        public bool AutoBankTransferSameCurr { get; set; }
        public bool AutoBankTransferCrossCurr { get; set; }
        public bool AutoBankAdjustment { get; set; }
        public string POBankAcctNum { get; set; }
        public string BankCustNum { get; set; }
        public bool AutoReverse { get; set; }
        public int PeriodThreshold { get; set; }
        public bool PRAlignTax { get; set; }
        public int PRLinePerPRCheck { get; set; }
        public bool PRPreprintedCheckNumber { get; set; }
        public bool PayrollCheckingAccount { get; set; }
        public string RBankNum { get; set; }
        public string RBranchNum { get; set; }
        public string JPBankName { get; set; }
        public string JPBranchName { get; set; }
        public string BankTranfAccountType { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string State { get; set; }
        public int CountryNum { get; set; }
        public string LName { get; set; }
        public string MsgIDCounter { get; set; }
        public bool ConsInvPmt { get; set; }
        public bool PreprintedCheckNum { get; set; }
        public int InvPerCheckStub { get; set; }
        public bool ReconcileOtherBalances { get; set; }
        public int RecBalFiscalYear { get; set; }
        public int RecBalFiscalPeriod { get; set; }
        public string RecBalFiscalYearSuffix { get; set; }
        public bool RevalueUseRecBal { get; set; }
        public string COOneTimeID { get; set; }
        public bool COIsOneTimeBankAcct { get; set; }
        public bool AutoCustBalanceReceipt { get; set; }
        public decimal MatchTolerance { get; set; }
        public string TranTemplateID { get; set; }
        public bool AutoCustBalanceReceiptApplyAll { get; set; }
        public string MXSATCode { get; set; }
        public string MXSATNameShort { get; set; }
        public string MXSATNameFull { get; set; }
        public string CNSellerBankName { get; set; }
        public string CNSellerAddress { get; set; }
        public string ClearBankExchRate { get; set; }
        public string PositivePayRemoteID { get; set; }
        public string PositivePayBatchID { get; set; }
        public int DefPosPayEFTHeadUID { get; set; }
        public string LogoFont { get; set; }
        public string LogoType { get; set; }
        public string LogoImageID { get; set; }
        public string LogoText01 { get; set; }
        public string LogoText02 { get; set; }
        public string LogoText03 { get; set; }
        public string LogoText04 { get; set; }
        public string LogoText05 { get; set; }
        public string LogoText06 { get; set; }
        public string SignatureFont { get; set; }
        public string SignatureType { get; set; }
        public string SignatureImageID { get; set; }
        public string SignatureText01 { get; set; }
        public string SignatureText02 { get; set; }
        public string SignatureText03 { get; set; }
        public string SignatureText04 { get; set; }
        public string SignatureText05 { get; set; }
        public string SignatureText06 { get; set; }
        public string PREntryClassCode { get; set; }
        public int PRPMEFTHeadUID { get; set; }
    }
}
