//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankTran
    {
        public string Company { get; set; }
        public string BankAcctID { get; set; }
        public int TranNum { get; set; }
        public Nullable<System.DateTime> TranDate { get; set; }
        public decimal TranAmt { get; set; }
        public string TranRef { get; set; }
        public bool GLPosted { get; set; }
        public string EntryPerson { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryTime { get; set; }
        public bool TranCleared { get; set; }
        public bool TranClearPending { get; set; }
        public decimal TranClearedAmt { get; set; }
        public string TranClearedPerson { get; set; }
        public Nullable<System.DateTime> TranClearedDate { get; set; }
        public string TranClearedTime { get; set; }
        public string BankSlip { get; set; }
        public int FiscalYear { get; set; }
        public int FiscalPeriod { get; set; }
        public int JournalNum { get; set; }
        public string JournalCode { get; set; }
        public decimal DocTranAmt { get; set; }
        public string CurrencyCode { get; set; }
        public decimal ExchangeRate { get; set; }
        public decimal DocTranClearedAmt { get; set; }
        public string GroupID { get; set; }
        public decimal CashBookNum { get; set; }
        public int CashbookLine { get; set; }
        public string GLRefType { get; set; }
        public string GLRefCode { get; set; }
        public string GLRefCodeDesc { get; set; }
        public decimal Rpt1TranAmt { get; set; }
        public decimal Rpt2TranAmt { get; set; }
        public decimal Rpt3TranAmt { get; set; }
        public decimal Rpt1TranClearedAmt { get; set; }
        public decimal Rpt2TranClearedAmt { get; set; }
        public decimal Rpt3TranClearedAmt { get; set; }
        public string RateGrpCode { get; set; }
        public string FiscalYearSuffix { get; set; }
        public string FiscalCalendarID { get; set; }
        public string BankFeeID { get; set; }
        public decimal BankFeeAmt { get; set; }
        public decimal BankFeeTaxAmt { get; set; }
        public decimal DocBankFeeAmt { get; set; }
        public decimal DocBankFeeTaxAmt { get; set; }
        public decimal Rpt1BankFeeAmt { get; set; }
        public decimal Rpt2BankFeeAmt { get; set; }
        public decimal Rpt3BankFeeAmt { get; set; }
        public decimal Rpt1BankFeeTaxAmt { get; set; }
        public decimal Rpt2BankFeeTaxAmt { get; set; }
        public decimal Rpt3BankFeeTaxAmt { get; set; }
        public string SourceModule { get; set; }
        public int HeadNum { get; set; }
        public bool Voided { get; set; }
        public string PCashDeskID { get; set; }
        public string GainLossType { get; set; }
        public int PCashRefNum { get; set; }
        public bool ReverseGL { get; set; }
        public Nullable<System.DateTime> RevalueDate { get; set; }
        public decimal RevalueBal { get; set; }
        public decimal DocRevalueBal { get; set; }
        public decimal Rpt1RevalueBal { get; set; }
        public decimal Rpt2RevalueBal { get; set; }
        public decimal Rpt3RevalueBal { get; set; }
        public string LegalNumber { get; set; }
        public string TranDocTypeID { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public string CNCFICode { get; set; }
        public string CNToCFICode { get; set; }
        public decimal BankRecGainLoss { get; set; }
        public decimal Rpt1BankRecGainLoss { get; set; }
        public decimal Rpt2BankRecGainLoss { get; set; }
        public decimal Rpt3BankRecGainLoss { get; set; }
        public int BalanceUpdated { get; set; }
        public decimal DocBankRecGainLoss { get; set; }
        public Nullable<System.DateTime> MXRecDate { get; set; }
        public bool BankBatchExcluded { get; set; }
        public System.Guid BankBatchSysRowID { get; set; }
        public string ABTUID { get; set; }
    }
}
