//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookOrd
    {
        public string Company { get; set; }
        public int OrderNum { get; set; }
        public int CustNum { get; set; }
        public string PONum { get; set; }
    }
}
