//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITEIndiaEntities : DbContext
    {
        public ITEIndiaEntities()
            : base("name=ITEIndiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Final_Inspection_Data> Final_Inspection_Data { get; set; }
        public virtual DbSet<Final_Inspection_Document_Data> Final_Inspection_Document_Data { get; set; }
        public virtual DbSet<Final_Inspection_Document_Varification> Final_Inspection_Document_Varification { get; set; }
        public virtual DbSet<Final_Inspection_LogTable> Final_Inspection_LogTable { get; set; }
        public virtual DbSet<Final_Inspection_Mrb_Data> Final_Inspection_Mrb_Data { get; set; }
        public virtual DbSet<Final_Inspection_MRB_DecisionData> Final_Inspection_MRB_DecisionData { get; set; }
        public virtual DbSet<Final_Inspection_Mrb_Rcode> Final_Inspection_Mrb_Rcode { get; set; }
        public virtual DbSet<Final_Inspection_Process> Final_Inspection_Process { get; set; }
        public virtual DbSet<Final_Inspection_Process_Rework> Final_Inspection_Process_Rework { get; set; }
        public virtual DbSet<Final_Inspection_RCode> Final_Inspection_RCode { get; set; }
        public virtual DbSet<Final_Inspection_Rework> Final_Inspection_Rework { get; set; }
        public virtual DbSet<Final_Inspection_Stage_Data> Final_Inspection_Stage_Data { get; set; }
        public virtual DbSet<Final_Inspection_Stage_Master> Final_Inspection_Stage_Master { get; set; }
        public virtual DbSet<Final_Inspection_UserList> Final_Inspection_UserList { get; set; }
        public virtual DbSet<ISUser> ISUsers { get; set; }
        public virtual DbSet<user_data> user_data { get; set; }
        public virtual DbSet<USER_MST> USER_MST { get; set; }
    }
}
