//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustCnt
    {
        public string Company { get; set; }
        public int CustNum { get; set; }
        public string ShipToNum { get; set; }
        public int ConNum { get; set; }
        public string Name { get; set; }
        public string Func { get; set; }
        public string FaxNum { get; set; }
        public string PhoneNum { get; set; }
        public bool SpecialAddress { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string CorpName { get; set; }
        public string EMailAddress { get; set; }
        public int CountryNum { get; set; }
        public string SFPortalPassword { get; set; }
        public bool SFUser { get; set; }
        public bool PortalUser { get; set; }
        public string RoleCode { get; set; }
        public string CellPhoneNum { get; set; }
        public string PagerNum { get; set; }
        public string HomeNum { get; set; }
        public string AltNum { get; set; }
        public string ContactTitle { get; set; }
        public string ReportsTo { get; set; }
        public string Comment { get; set; }
        public bool NoContact { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateDcdUserID { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string ChangeDcdUserID { get; set; }
        public bool Inactive { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
        public string Initials { get; set; }
        public string ExternalID { get; set; }
        public bool GlobalLock { get; set; }
        public bool ShowInputPrice { get; set; }
        public int ChangeTime { get; set; }
        public string ChangedBy { get; set; }
        public int MasterCustNum { get; set; }
        public string MasterShipToNum { get; set; }
        public int MasterConNum { get; set; }
        public int PerConID { get; set; }
        public bool SyncNameToPerCon { get; set; }
        public bool SyncAddressToPerCon { get; set; }
        public bool SyncPhoneToPerCon { get; set; }
        public bool SyncEmailToPerCon { get; set; }
        public bool SyncLinksToPerCon { get; set; }
        public string WebSite { get; set; }
        public string IM { get; set; }
        public string Twitter { get; set; }
        public string LinkedIn { get; set; }
        public string FaceBook { get; set; }
        public string WebLink1 { get; set; }
        public string WebLink2 { get; set; }
        public string WebLink3 { get; set; }
        public string WebLink4 { get; set; }
        public string WebLink5 { get; set; }
        public bool PerConAddress { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public bool SyncToExternalCRM { get; set; }
        public string ExternalCRMCustomerID { get; set; }
        public string ExternalCRMContactID { get; set; }
        public string Character01 { get; set; }
        public string Character02 { get; set; }
        public Nullable<bool> CheckBox01 { get; set; }
        public Nullable<System.Guid> ForeignSysRowID { get; set; }
        public byte[] UD_SysRevID { get; set; }
    }
}
