//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustView
    {
        public string Company { get; set; }
        public string CustID { get; set; }
        public int CustNum { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string SalesRepCode { get; set; }
        public string TerritoryID { get; set; }
        public string ShipToNum { get; set; }
        public string TermsCode { get; set; }
        public string ShipViaCode { get; set; }
        public bool CreditHold { get; set; }
        public string GroupCode { get; set; }
        public string Comment { get; set; }
        public string FaxNum { get; set; }
        public string PhoneNum { get; set; }
        public string TaxExempt { get; set; }
        public string MarkUpID { get; set; }
        public int BillDay { get; set; }
        public bool OneInvPerPS { get; set; }
        public string DefaultFOB { get; set; }
        public bool CreditIncludeOrders { get; set; }
        public string BTName { get; set; }
        public string BTAddress1 { get; set; }
        public string BTAddress2 { get; set; }
        public string BTAddress3 { get; set; }
        public string BTCity { get; set; }
        public string BTState { get; set; }
        public string BTZip { get; set; }
        public int BTCountryNum { get; set; }
        public string BTCountry { get; set; }
        public string BTPhoneNum { get; set; }
        public string BTFaxNum { get; set; }
        public string BTFormatStr { get; set; }
        public int ParentCustNum { get; set; }
        public string TaxRegionCode { get; set; }
        public string EMailAddress { get; set; }
        public string CustomerType { get; set; }
        public string CustURL { get; set; }
        public string PendingTerritoryID { get; set; }
        public string ExtID { get; set; }
        public bool ConsolidateSO { get; set; }
        public string BillFrequency { get; set; }
        public bool CreditIncludePI { get; set; }
        public bool GlobalCust { get; set; }
        public bool ICTrader { get; set; }
        public string TaxAuthorityCode { get; set; }
        public bool ExternalDeliveryNote { get; set; }
        public bool GlobalCredIncOrd { get; set; }
        public bool GlobalCredIncPI { get; set; }
        public string GlobalCurrencyCode { get; set; }
        public string ExternalID { get; set; }
        public string GlobalCreditHold { get; set; }
        public bool GlobalLock { get; set; }
        public bool CheckDuplicatePO { get; set; }
        public decimal CreditLimit { get; set; }
        public decimal CustPILimit { get; set; }
        public decimal GlobalCreditLimit { get; set; }
        public decimal GlobalPILimit { get; set; }
        public decimal DocGlobalCreditLimit { get; set; }
        public decimal DocGlobalPILimit { get; set; }
        public bool RfqAttachAllow { get; set; }
        public int DemandDeliveryDays { get; set; }
        public string DemandDateType { get; set; }
        public int DemandAddLeadTime { get; set; }
        public string DemandAddAction { get; set; }
        public int DemandChangeLeadTime { get; set; }
        public string DemandChangeAction { get; set; }
        public int DemandCancelLeadTime { get; set; }
        public string DemandCancelAction { get; set; }
        public int DemandNewLineLeadTime { get; set; }
        public string DemandNewLineAction { get; set; }
        public int DemandQtyChangeLeadTime { get; set; }
        public string DemandQtyChangeAction { get; set; }
        public int DemandChangeDateLeadTime { get; set; }
        public string DemandChangeDateAction { get; set; }
        public string TradingPartnerName { get; set; }
        public bool ResDelivery { get; set; }
        public bool SatDelivery { get; set; }
        public bool SatPickup { get; set; }
        public bool verbalconf { get; set; }
        public bool hazmat { get; set; }
        public string doconly { get; set; }
        public bool refnotes { get; set; }
        public decimal applychrg { get; set; }
        public bool chrgamount { get; set; }
        public string notifyflag { get; set; }
        public int CountryNum { get; set; }
        public bool TerritoryLock { get; set; }
        public bool CreditCardOrder { get; set; }
        public bool ServHomeDel { get; set; }
        public int PeriodicityCode { get; set; }
        public bool AllowAltBillTo { get; set; }
        public string RelatedToFile { get; set; }
        public string aracctid { get; set; }
    }
}
