//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ITe_INDIAEntities : DbContext
    {
        public ITe_INDIAEntities()
            : base("name=ITe_INDIAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<Associated_Document> Associated_Document { get; set; }
        public virtual DbSet<Attachment_Mst> Attachment_Mst { get; set; }
        public virtual DbSet<backup_logs> backup_logs { get; set; }
        public virtual DbSet<catagory_tbl> catagory_tbl { get; set; }
        public virtual DbSet<CRUP_MST> CRUP_MST { get; set; }
        public virtual DbSet<DayClose> DayCloses { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<ECN_CHANGE_OPTIONS> ECN_CHANGE_OPTIONS { get; set; }
        public virtual DbSet<emailauto> emailautoes { get; set; }
        public virtual DbSet<Emp_Course_data> Emp_Course_data { get; set; }
        public virtual DbSet<Emp_Limit> Emp_Limit { get; set; }
        public virtual DbSet<Emp_Training_final_database> Emp_Training_final_database { get; set; }
        public virtual DbSet<Emp_Training_Master> Emp_Training_Master { get; set; }
        public virtual DbSet<emp_trial_data> emp_trial_data { get; set; }
        public virtual DbSet<Employee_Details> Employee_Details { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Engineering_CNC_new> Engineering_CNC_new { get; set; }
        public virtual DbSet<Engwork_AddNewTool> Engwork_AddNewTool { get; set; }
        public virtual DbSet<Engwork_MAFIA> Engwork_MAFIA { get; set; }
        public virtual DbSet<Engwork_MaterialSuggestion> Engwork_MaterialSuggestion { get; set; }
        public virtual DbSet<Engwork_MOM> Engwork_MOM { get; set; }
        public virtual DbSet<Engwork_OPD> Engwork_OPD { get; set; }
        public virtual DbSet<Engwork_OPSequence> Engwork_OPSequence { get; set; }
        public virtual DbSet<Engwork_PoForecast> Engwork_PoForecast { get; set; }
        public virtual DbSet<Engwork_PTD> Engwork_PTD { get; set; }
        public virtual DbSet<Engwork_ToolingSuggesstion_AvaCheck> Engwork_ToolingSuggesstion_AvaCheck { get; set; }
        public virtual DbSet<Epicor_Job_Head> Epicor_Job_Head { get; set; }
        public virtual DbSet<Epicor_Part_Library> Epicor_Part_Library { get; set; }
        public virtual DbSet<Epicor_Part_Update_Log> Epicor_Part_Update_Log { get; set; }
        public virtual DbSet<EPO_Approval> EPO_Approval { get; set; }
        public virtual DbSet<EPO_Creation> EPO_Creation { get; set; }
        public virtual DbSet<EPO_Employee_details> EPO_Employee_details { get; set; }
        public virtual DbSet<EPO_ITEM_Receive> EPO_ITEM_Receive { get; set; }
        public virtual DbSet<EPO_MPC_VOTE> EPO_MPC_VOTE { get; set; }
        public virtual DbSet<EPO_Ref_Table> EPO_Ref_Table { get; set; }
        public virtual DbSet<Event_Logger_Data> Event_Logger_Data { get; set; }
        public virtual DbSet<Event_Logger_Supervisor_data> Event_Logger_Supervisor_data { get; set; }
        public virtual DbSet<Event_Management_MSM> Event_Management_MSM { get; set; }
        public virtual DbSet<Event_Management_MSM_Details> Event_Management_MSM_Details { get; set; }
        public virtual DbSet<Event_Management_Multiname> Event_Management_Multiname { get; set; }
        public virtual DbSet<Event_Management_Report_Details> Event_Management_Report_Details { get; set; }
        public virtual DbSet<event_management_with_textbox_values> event_management_with_textbox_values { get; set; }
        public virtual DbSet<Event_Name_Master> Event_Name_Master { get; set; }
        public virtual DbSet<Event_Secondary_MSM> Event_Secondary_MSM { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Feedback_Query_Table> Feedback_Query_Table { get; set; }
        public virtual DbSet<Final_Inspection_Data> Final_Inspection_Data { get; set; }
        public virtual DbSet<Final_Inspection_Mrb_Data> Final_Inspection_Mrb_Data { get; set; }
        public virtual DbSet<Final_Inspection_Process> Final_Inspection_Process { get; set; }
        public virtual DbSet<Final_Inspection_Process_Rework> Final_Inspection_Process_Rework { get; set; }
        public virtual DbSet<Final_Inspection_Rework> Final_Inspection_Rework { get; set; }
        public virtual DbSet<Final_Inspection_Stage_Master> Final_Inspection_Stage_Master { get; set; }
        public virtual DbSet<Final_Inspection_UserList> Final_Inspection_UserList { get; set; }
        public virtual DbSet<formula_history_tbl> formula_history_tbl { get; set; }
        public virtual DbSet<formula_master_tbl> formula_master_tbl { get; set; }
        public virtual DbSet<FUNCTION_MST> FUNCTION_MST { get; set; }
        public virtual DbSet<gatepass> gatepasses { get; set; }
        public virtual DbSet<gatepass_jobwork> gatepass_jobwork { get; set; }
        public virtual DbSet<gatepass_returnablenew> gatepass_returnablenew { get; set; }
        public virtual DbSet<gatepasspreviousdaydetail> gatepasspreviousdaydetails { get; set; }
        public virtual DbSet<HIBC_Apprentix_Table> HIBC_Apprentix_Table { get; set; }
        public virtual DbSet<HIBC_Code_Generator> HIBC_Code_Generator { get; set; }
        public virtual DbSet<HIBC_Primary_Barcode_Temp> HIBC_Primary_Barcode_Temp { get; set; }
        public virtual DbSet<HIBC_Temp_Storage> HIBC_Temp_Storage { get; set; }
        public virtual DbSet<holiday> holidays { get; set; }
        public virtual DbSet<hourcounting> hourcountings { get; set; }
        public virtual DbSet<icrdtemp> icrdtemps { get; set; }
        public virtual DbSet<InitiatorName> InitiatorNames { get; set; }
        public virtual DbSet<Intervierw_Experience_Reference> Intervierw_Experience_Reference { get; set; }
        public virtual DbSet<Interview_Answer_verify> Interview_Answer_verify { get; set; }
        public virtual DbSet<Interview_Education_details> Interview_Education_details { get; set; }
        public virtual DbSet<Interview_family_background> Interview_family_background { get; set; }
        public virtual DbSet<Interview_form_personal_details> Interview_form_personal_details { get; set; }
        public virtual DbSet<Interview_Questions> Interview_Questions { get; set; }
        public virtual DbSet<Invoice_entry_master_tbl> Invoice_entry_master_tbl { get; set; }
        public virtual DbSet<ISQuery> ISQueries { get; set; }
        public virtual DbSet<Issue_Material> Issue_Material { get; set; }
        public virtual DbSet<ISUser> ISUsers { get; set; }
        public virtual DbSet<item_name_tbl> item_name_tbl { get; set; }
        public virtual DbSet<item_type> item_type { get; set; }
        public virtual DbSet<Items_of_EPO_temp> Items_of_EPO_temp { get; set; }
        public virtual DbSet<jobwork> jobworks { get; set; }
        public virtual DbSet<jobworkhour> jobworkhours { get; set; }
        public virtual DbSet<Late_comers_of_week_mail> Late_comers_of_week_mail { get; set; }
        public virtual DbSet<late_coming_img_table> late_coming_img_table { get; set; }
        public virtual DbSet<login_tbl> login_tbl { get; set; }
        public virtual DbSet<machine> machines { get; set; }
        public virtual DbSet<Machine_Details> Machine_Details { get; set; }
        public virtual DbSet<maintenance> maintenances { get; set; }
        public virtual DbSet<Material_Library> Material_Library { get; set; }
        public virtual DbSet<MDR_Part_Data> MDR_Part_Data { get; set; }
        public virtual DbSet<METADATA> METADATAs { get; set; }
        public virtual DbSet<MiscelleneousRequestTbl> MiscelleneousRequestTbls { get; set; }
        public virtual DbSet<MODULE_MAP> MODULE_MAP { get; set; }
        public virtual DbSet<MODULE_MST> MODULE_MST { get; set; }
        public virtual DbSet<monthly_attendance_data> monthly_attendance_data { get; set; }
        public virtual DbSet<multiname> multinames { get; set; }
        public virtual DbSet<mytimepunchrecord> mytimepunchrecords { get; set; }
        public virtual DbSet<nonreturnablegatepass> nonreturnablegatepasses { get; set; }
        public virtual DbSet<NotificationList_Document> NotificationList_Document { get; set; }
        public virtual DbSet<Part_Library> Part_Library { get; set; }
        public virtual DbSet<PartMasterTbl> PartMasterTbls { get; set; }
        public virtual DbSet<partnumber> partnumbers { get; set; }
        public virtual DbSet<PPAP_Data> PPAP_Data { get; set; }
        public virtual DbSet<PRIVILAGE_MENUDemon> PRIVILAGE_MENUDemon { get; set; }
        public virtual DbSet<PRIVILEGE_MST> PRIVILEGE_MST { get; set; }
        public virtual DbSet<Prod_Flex_Bulk_Shaft_Issue> Prod_Flex_Bulk_Shaft_Issue { get; set; }
        public virtual DbSet<Prod_Flex_Bulk_Shaft_Job_List> Prod_Flex_Bulk_Shaft_Job_List { get; set; }
        public virtual DbSet<Prod_Flex_Bulk_Shaft_Job_List_History> Prod_Flex_Bulk_Shaft_Job_List_History { get; set; }
        public virtual DbSet<Prod_Flex_Cut_Shaft_Job_List> Prod_Flex_Cut_Shaft_Job_List { get; set; }
        public virtual DbSet<Prod_Flex_Cut_Shaft_Job_List_History> Prod_Flex_Cut_Shaft_Job_List_History { get; set; }
        public virtual DbSet<Prod_Flex_Inventory> Prod_Flex_Inventory { get; set; }
        public virtual DbSet<Prod_Flex_Part_List> Prod_Flex_Part_List { get; set; }
        public virtual DbSet<Prod_Flex_Part_List_History> Prod_Flex_Part_List_History { get; set; }
        public virtual DbSet<Prod_Flex_Part_Wise_Operation> Prod_Flex_Part_Wise_Operation { get; set; }
        public virtual DbSet<Prodcution_Report_CNC> Prodcution_Report_CNC { get; set; }
        public virtual DbSet<Production_Deviation_Report> Production_Deviation_Report { get; set; }
        public virtual DbSet<Production_ECR_Data> Production_ECR_Data { get; set; }
        public virtual DbSet<Production_Final_Data> Production_Final_Data { get; set; }
        public virtual DbSet<Production_Planning> Production_Planning { get; set; }
        public virtual DbSet<Production_Production_dtls> Production_Production_dtls { get; set; }
        public virtual DbSet<Production_Qtydtls> Production_Qtydtls { get; set; }
        public virtual DbSet<Production_Report_Generator_Detail> Production_Report_Generator_Detail { get; set; }
        public virtual DbSet<Production_Setup_Dtls> Production_Setup_Dtls { get; set; }
        public virtual DbSet<Production_Tool_Details> Production_Tool_Details { get; set; }
        public virtual DbSet<Production_Utilization> Production_Utilization { get; set; }
        public virtual DbSet<Program_Operation_wise_Tool_Library> Program_Operation_wise_Tool_Library { get; set; }
        public virtual DbSet<purchase_analysis_item_group_master> purchase_analysis_item_group_master { get; set; }
        public virtual DbSet<purreq> purreqs { get; set; }
        public virtual DbSet<purreq_invoice_viewdetail> purreq_invoice_viewdetail { get; set; }
        public virtual DbSet<Query_tbl> Query_tbl { get; set; }
        public virtual DbSet<RequisitionEntry> RequisitionEntries { get; set; }
        public virtual DbSet<ReturnMiscelleneousRequestTbl> ReturnMiscelleneousRequestTbls { get; set; }
        public virtual DbSet<ROLE_MST> ROLE_MST { get; set; }
        public virtual DbSet<shift> shifts { get; set; }
        public virtual DbSet<Sholder_Implant_Database> Sholder_Implant_Database { get; set; }
        public virtual DbSet<Sholder_Implant_Database_History> Sholder_Implant_Database_History { get; set; }
        public virtual DbSet<ShopFloorEntry> ShopFloorEntries { get; set; }
        public virtual DbSet<Shoulder_Implant_Database_New> Shoulder_Implant_Database_New { get; set; }
        public virtual DbSet<Shoulder_implant_Images> Shoulder_implant_Images { get; set; }
        public virtual DbSet<Shoulder_Implant_Images_desc> Shoulder_Implant_Images_desc { get; set; }
        public virtual DbSet<Shoulder_Implant_Master> Shoulder_Implant_Master { get; set; }
        public virtual DbSet<Shoulder_Implant_Technique> Shoulder_Implant_Technique { get; set; }
        public virtual DbSet<ssw_appliance_for_reference> ssw_appliance_for_reference { get; set; }
        public virtual DbSet<SSW_Appliances> SSW_Appliances { get; set; }
        public virtual DbSet<SSW_Appliances_Main> SSW_Appliances_Main { get; set; }
        public virtual DbSet<SSW_Appliances_Main_added> SSW_Appliances_Main_added { get; set; }
        public virtual DbSet<SSW_Vacancy> SSW_Vacancy { get; set; }
        public virtual DbSet<sswhite_gallery> sswhite_gallery { get; set; }
        public virtual DbSet<Student_Data> Student_Data { get; set; }
        public virtual DbSet<supp_email> supp_email { get; set; }
        public virtual DbSet<Supplier_Data> Supplier_Data { get; set; }
        public virtual DbSet<Supplier_Data_new> Supplier_Data_new { get; set; }
        public virtual DbSet<Supplier_master> Supplier_master { get; set; }
        public virtual DbSet<Supplier_New_Data> Supplier_New_Data { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Task_Management_Trial> Task_Management_Trial { get; set; }
        public virtual DbSet<Task_Management_Trial_Secondary> Task_Management_Trial_Secondary { get; set; }
        public virtual DbSet<tblAudit> tblAudits { get; set; }
        public virtual DbSet<TBLBIN> TBLBINs { get; set; }
        public virtual DbSet<tblCityStatesCounty> tblCityStatesCounties { get; set; }
        public virtual DbSet<TBLCONTACT> TBLCONTACTs { get; set; }
        public virtual DbSet<tblCOUNTRY> tblCOUNTRies { get; set; }
        public virtual DbSet<tblFile> tblFiles { get; set; }
        public virtual DbSet<TBLLabelDTL> TBLLabelDTLs { get; set; }
        public virtual DbSet<TBLLabelMST> TBLLabelMSTs { get; set; }
        public virtual DbSet<TBLLOCATION> TBLLOCATIONs { get; set; }
        public virtual DbSet<Tempdatatable> Tempdatatables { get; set; }
        public virtual DbSet<tempUser> tempUsers { get; set; }
        public virtual DbSet<tempUser1> tempUser1 { get; set; }
        public virtual DbSet<test> tests { get; set; }
        public virtual DbSet<Ticket_generated_department_applicable> Ticket_generated_department_applicable { get; set; }
        public virtual DbSet<Ticket_generation_application_revision_detail> Ticket_generation_application_revision_detail { get; set; }
        public virtual DbSet<Ticket_generation_Process> Ticket_generation_Process { get; set; }
        public virtual DbSet<Ticket_process_chat> Ticket_process_chat { get; set; }
        public virtual DbSet<Tool_Category> Tool_Category { get; set; }
        public virtual DbSet<Tool_Inventory_System> Tool_Inventory_System { get; set; }
        public virtual DbSet<Tool_Utilization> Tool_Utilization { get; set; }
        public virtual DbSet<Tooling_Utilization_all_details> Tooling_Utilization_all_details { get; set; }
        public virtual DbSet<Tooling_Utilization_details> Tooling_Utilization_details { get; set; }
        public virtual DbSet<UDAI_UDIMaster> UDAI_UDIMaster { get; set; }
        public virtual DbSet<UDAI_UDIMaster_History_tbl> UDAI_UDIMaster_History_tbl { get; set; }
        public virtual DbSet<unit> units { get; set; }
        public virtual DbSet<UOM> UOMs { get; set; }
        public virtual DbSet<user_data> user_data { get; set; }
        public virtual DbSet<USER_DTL> USER_DTL { get; set; }
        public virtual DbSet<USER_MST> USER_MST { get; set; }
        public virtual DbSet<User_Mst_For_Shoulder> User_Mst_For_Shoulder { get; set; }
        public virtual DbSet<USER_RIGHTS> USER_RIGHTS { get; set; }
        public virtual DbSet<USER_ROLE> USER_ROLE { get; set; }
        public virtual DbSet<User_roles_for_Shoulder_app> User_roles_for_Shoulder_app { get; set; }
        public virtual DbSet<User_Wise_Sholder_Implant_FVRT> User_Wise_Sholder_Implant_FVRT { get; set; }
        public virtual DbSet<User_Wise_Shoulder_Implant_History> User_Wise_Shoulder_Implant_History { get; set; }
        public virtual DbSet<userdata> userdatas { get; set; }
        public virtual DbSet<Version> Versions { get; set; }
        public virtual DbSet<video_table> video_table { get; set; }
        public virtual DbSet<Visitor_gatepass_data> Visitor_gatepass_data { get; set; }
        public virtual DbSet<VMS_DATA_FROM_DASHBOARD> VMS_DATA_FROM_DASHBOARD { get; set; }
        public virtual DbSet<VMS_FTO_Request> VMS_FTO_Request { get; set; }
        public virtual DbSet<VMS_Monthly_Data> VMS_Monthly_Data { get; set; }
        public virtual DbSet<VMSAttendanceShiftchangedata> VMSAttendanceShiftchangedatas { get; set; }
        public virtual DbSet<VMSAttendanceShiftchangedata_History> VMSAttendanceShiftchangedata_History { get; set; }
        public virtual DbSet<VMSAttendanceShiftDetail> VMSAttendanceShiftDetails { get; set; }
        public virtual DbSet<VMSEmployeeDetail> VMSEmployeeDetails { get; set; }
        public virtual DbSet<VMSFLEXDATAFilter> VMSFLEXDATAFilters { get; set; }
        public virtual DbSet<VMSFORExport> VMSFORExports { get; set; }
        public virtual DbSet<VMSFOREXPORTATTEND> VMSFOREXPORTATTENDs { get; set; }
        public virtual DbSet<Weather> Weathers { get; set; }
        public virtual DbSet<who_Is_In_the_Building> who_Is_In_the_Building { get; set; }
        public virtual DbSet<Work_Sampling_Study_All> Work_Sampling_Study_All { get; set; }
        public virtual DbSet<Work_Sampling_Study_machine> Work_Sampling_Study_machine { get; set; }
        public virtual DbSet<Working_Sampling_Time> Working_Sampling_Time { get; set; }
        public virtual DbSet<React_Employee> React_Employee { get; set; }
        public virtual DbSet<View_1> View_1 { get; set; }
        public virtual DbSet<view_invoice_with_supplier> view_invoice_with_supplier { get; set; }
        public virtual DbSet<VW_UdiOnHold> VW_UdiOnHold { get; set; }
    
        public virtual ObjectResult<AllRating_Result> AllRating()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllRating_Result>("AllRating");
        }
    
        public virtual ObjectResult<AllUdaiReqWithHistory_Result> AllUdaiReqWithHistory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllUdaiReqWithHistory_Result>("AllUdaiReqWithHistory");
        }
    
        public virtual ObjectResult<GetProductDesc_Result> GetProductDesc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductDesc_Result>("GetProductDesc");
        }
    
        public virtual ObjectResult<MonthlyAvgRating_Result> MonthlyAvgRating()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MonthlyAvgRating_Result>("MonthlyAvgRating");
        }
    
        public virtual ObjectResult<MonthlyDeliveryRating_Result> MonthlyDeliveryRating()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MonthlyDeliveryRating_Result>("MonthlyDeliveryRating");
        }
    
        public virtual ObjectResult<MonthlyExpense_Result> MonthlyExpense()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MonthlyExpense_Result>("MonthlyExpense");
        }
    
        public virtual ObjectResult<MonthlyQualityRating_Result> MonthlyQualityRating()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MonthlyQualityRating_Result>("MonthlyQualityRating");
        }
    
        public virtual ObjectResult<OTD_Report_Result> OTD_Report()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OTD_Report_Result>("OTD_Report");
        }
    
        public virtual ObjectResult<SelectQuery_Result> SelectQuery()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectQuery_Result>("SelectQuery");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_group_by_slip_no_Result> sp_group_by_slip_no()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_group_by_slip_no_Result>("sp_group_by_slip_no");
        }
    
        public virtual ObjectResult<sp_group_by_slip_no_with_supplier_name_Result> sp_group_by_slip_no_with_supplier_name()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_group_by_slip_no_with_supplier_name_Result>("sp_group_by_slip_no_with_supplier_name");
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<SP_UdiOnHold_Result> SP_UdiOnHold()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_UdiOnHold_Result>("SP_UdiOnHold");
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<sp_viewInvoiceData_Result> sp_viewInvoiceData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_viewInvoiceData_Result>("sp_viewInvoiceData");
        }
    }
}
