//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMRCorAct
    {
        public string Company { get; set; }
        public string Description { get; set; }
        public string CommentText { get; set; }
        public int NonConfNum { get; set; }
        public string AsigndTo { get; set; }
        public string AuditBy { get; set; }
        public string AuditCmts { get; set; }
        public string CauseInv { get; set; }
        public string Dept { get; set; }
        public Nullable<System.DateTime> DateOpen { get; set; }
        public Nullable<System.DateTime> DuDate { get; set; }
        public Nullable<System.DateTime> AuditDt { get; set; }
        public Nullable<System.DateTime> ActionComp { get; set; }
        public int DMRNum { get; set; }
        public int ActionID { get; set; }
        public string CauseReasonCode { get; set; }
        public string CorrectiveActionReasonCode { get; set; }
        public int VendorNum { get; set; }
        public int ConNum { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public string Character01 { get; set; }
        public string Character02 { get; set; }
        public string Character03 { get; set; }
        public string Character04 { get; set; }
        public string Character05 { get; set; }
        public string Character06 { get; set; }
        public string Character07 { get; set; }
        public string Character08 { get; set; }
        public string Character09 { get; set; }
        public Nullable<System.DateTime> Date01 { get; set; }
        public Nullable<System.DateTime> Date02 { get; set; }
        public Nullable<System.DateTime> Date03 { get; set; }
        public Nullable<System.Guid> ForeignSysRowID { get; set; }
        public byte[] UD_SysRevID { get; set; }
    }
}
