//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECN_CHANGE_OPTIONS
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int ECNID { get; set; }
        public int PID { get; set; }
        public string ECN_Name { get; set; }
    }
}
