//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECOCOPart
    {
        public string Company { get; set; }
        public string GroupID { get; set; }
        public string PartNum { get; set; }
        public string RevisionNum { get; set; }
        public string CoPartNum { get; set; }
        public string CoRevisionNum { get; set; }
        public int PartsPerOp { get; set; }
        public int LbrCostBase { get; set; }
        public int MtlCostBase { get; set; }
        public string PartDescription { get; set; }
        public string IUM { get; set; }
        public string AltMethod { get; set; }
        public bool PreventSugg { get; set; }
        public bool PrimaryCost { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public string ShortChar01 { get; set; }
        public Nullable<System.Guid> ForeignSysRowID { get; set; }
        public byte[] UD_SysRevID { get; set; }
    }
}
