//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Training_Master
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string Department { get; set; }
        public string Sub_Department { get; set; }
        public string Cource_Name { get; set; }
        public string Summary_of_Content { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public string Location { get; set; }
    }
}
