//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engineering_CNC_new
    {
        public int ID { get; set; }
        public string PO_Number { get; set; }
        public string Part_Number { get; set; }
        public int PID { get; set; }
        public Nullable<int> Line_Number { get; set; }
        public string Previously_Ava_Or_New { get; set; }
        public Nullable<System.DateTime> PO_Date { get; set; }
        public Nullable<System.DateTime> PO_Received_Date_Entry { get; set; }
        public string Category { get; set; }
        public string SubPart { get; set; }
        public Nullable<int> Revision_Number { get; set; }
        public string SQRM_Code { get; set; }
        public Nullable<int> PO_Qty { get; set; }
        public string Part_maximum_DIA_HEIGHT { get; set; }
        public string Material_Part_Name { get; set; }
        public string Bar_Plate_Diameter_Dimensions { get; set; }
        public Nullable<decimal> Quantity_Parent { get; set; }
        public string Unit { get; set; }
        public string Special_Tool_Detail { get; set; }
        public string PO_DRAWING_Related_Remarks { get; set; }
        public string Material_Related_Remark { get; set; }
        public Nullable<System.DateTime> Drawing_Available_Date { get; set; }
        public Nullable<System.DateTime> Drawing_Verify_Date { get; set; }
        public Nullable<System.DateTime> Part_Entry_Date { get; set; }
        public Nullable<System.DateTime> Material_Suggestion_Email_Date { get; set; }
        public Nullable<System.DateTime> PTD_Date { get; set; }
        public Nullable<System.DateTime> OP_Seq_Sheet_complete_Date { get; set; }
        public Nullable<System.DateTime> Mom_Complete_Date { get; set; }
        public string SN_Made_out_Source { get; set; }
        public string PTD_Form_Required { get; set; }
        public string PTD_Form_Status { get; set; }
        public string Stage_Drawing_Required { get; set; }
        public Nullable<System.DateTime> Stage_Drawing_Available_Date { get; set; }
        public string op10 { get; set; }
        public string op20 { get; set; }
        public string op30 { get; set; }
        public string op40 { get; set; }
        public string op50 { get; set; }
        public string op60 { get; set; }
        public string op70 { get; set; }
        public string op80 { get; set; }
        public string op90 { get; set; }
        public string op100 { get; set; }
        public string op110 { get; set; }
        public string op120 { get; set; }
        public string op130 { get; set; }
        public string op140 { get; set; }
        public string op150 { get; set; }
        public string op160 { get; set; }
        public string op170 { get; set; }
        public string op180 { get; set; }
        public string op190 { get; set; }
        public string op200 { get; set; }
        public string op210 { get; set; }
        public string op220 { get; set; }
        public string Process_Detail { get; set; }
        public string Process_Remark { get; set; }
        public string Template { get; set; }
        public string SN_AVA_NOTA { get; set; }
        public string NJ_AVA_NOTA { get; set; }
        public string Mafia_Made { get; set; }
        public string Mafia_Released { get; set; }
        public string PIR_MAFIA_Status { get; set; }
        public Nullable<System.DateTime> COMP_Date_Mafia_Status_Check { get; set; }
        public Nullable<System.DateTime> Mafia_Made_Date { get; set; }
        public Nullable<System.DateTime> Correction_Date { get; set; }
        public Nullable<System.DateTime> Released_Date { get; set; }
        public string Made_By { get; set; }
        public string Mafia_Remark { get; set; }
        public string KPI_Drawing_Verify { get; set; }
        public string MOM_KPI { get; set; }
        public string Material_Suggestion_KPI { get; set; }
        public string Wrong_Drawing_In_Part_Library { get; set; }
        public Nullable<System.DateTime> po_entry_date { get; set; }
        public Nullable<System.DateTime> partdate { get; set; }
        public Nullable<int> part_final_entry { get; set; }
        public string Tool_Category { get; set; }
        public string Tool_type { get; set; }
        public string mafia_update_by { get; set; }
        public Nullable<System.DateTime> mom_Creation_Date { get; set; }
        public string Tool_Type_New { get; set; }
    }
}
