//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engwork_OPD
    {
        public int Id { get; set; }
        public int RId { get; set; }
        public int MId { get; set; }
        public Nullable<bool> DXFRequired { get; set; }
        public Nullable<System.DateTime> DXFAvilableDate { get; set; }
        public string DXFRemark { get; set; }
        public Nullable<int> OPDRequestFrom { get; set; }
        public string OPDRequirementDescription { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> OPDCorrectionDate { get; set; }
        public Nullable<System.DateTime> StageDrawingAvilableDate { get; set; }
        public Nullable<bool> Is_deleted { get; set; }
        public Nullable<bool> Is_Saved { get; set; }
        public Nullable<bool> Is_Submited { get; set; }
        public Nullable<bool> Is_SavedBy { get; set; }
        public Nullable<System.DateTime> Timestapm { get; set; }
    }
}
