//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPO_ITEM_Receive
    {
        public int ID { get; set; }
        public int EPO_NO { get; set; }
        public int line_no { get; set; }
        public int PID { get; set; }
        public Nullable<int> Order_qty { get; set; }
        public Nullable<int> received_qty { get; set; }
        public Nullable<int> remaining_qty { get; set; }
        public Nullable<int> transaction_qty { get; set; }
        public string invoice_no { get; set; }
        public string challan_no { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
        public string received_by { get; set; }
    }
}
