//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPO_Approval
    {
        public int ID { get; set; }
        public int PID { get; set; }
        public int epo { get; set; }
        public string Employee { get; set; }
        public string Manager { get; set; }
        public string MPC { get; set; }
        public string Higher_authority { get; set; }
        public Nullable<decimal> Employee_Limit { get; set; }
        public Nullable<decimal> Manager_Limit { get; set; }
        public Nullable<decimal> MPC_Limit { get; set; }
        public string Self_approval { get; set; }
        public string Manager_approval { get; set; }
        public string MPC_approval { get; set; }
        public string MPC_Higher_approval { get; set; }
        public string active { get; set; }
        public Nullable<System.DateTime> Employee_approval_Date { get; set; }
        public Nullable<System.DateTime> Manager_approval_date { get; set; }
        public Nullable<System.DateTime> MPC_Approval_date { get; set; }
        public Nullable<System.DateTime> MPC_Higher_approval_date { get; set; }
    }
}
