//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equip
    {
        public string Company { get; set; }
        public string EquipID { get; set; }
        public string Plant { get; set; }
        public bool InActive { get; set; }
        public string Description { get; set; }
        public string StatusID { get; set; }
        public string OEM { get; set; }
        public string SerialNum { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public Nullable<System.DateTime> InServiceDate { get; set; }
        public Nullable<System.DateTime> WarrantyExpDate { get; set; }
        public string TypeID { get; set; }
        public string ResourceGrpID { get; set; }
        public string ResourceID { get; set; }
        public int SellingVendorNum { get; set; }
        public string SellingPurPoint { get; set; }
        public int ServiceVendorNum { get; set; }
        public string ServicePurPoint { get; set; }
        public string AssetNum { get; set; }
        public string Comments { get; set; }
        public string Specs { get; set; }
        public string MeterUOM { get; set; }
        public int CurrentMeter { get; set; }
        public string ReadingComment { get; set; }
        public string LocID { get; set; }
        public string ParentEquipID { get; set; }
        public string LaborMeterOpt { get; set; }
        public Nullable<System.DateTime> ReadingDate { get; set; }
        public int ReadingTime { get; set; }
        public string InspPlanPartNum { get; set; }
        public string SpecID { get; set; }
        public Nullable<System.DateTime> LastCalDate { get; set; }
        public string InspPlanRevNum { get; set; }
        public string SpecRevNum { get; set; }
        public string ProjectID { get; set; }
        public string UOMClassID { get; set; }
        public string PhaseID { get; set; }
        public int PriorMeter { get; set; }
        public string Lineage { get; set; }
        public string TemplateJobNum { get; set; }
        public int AvgDailyUsage { get; set; }
        public bool GlobalEquip { get; set; }
        public bool GlobalLock { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public Nullable<System.Guid> ForeignSysRowID { get; set; }
        public byte[] UD_SysRevID { get; set; }
        public string AssignedEmpID_c { get; set; }
        public string Sublocation_c { get; set; }
        public string SubType_c { get; set; }
        public Nullable<System.DateTime> AssignedDate_c { get; set; }
    }
}
