//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_management_with_textbox_values
    {
        public int Id { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string Event_Generated_Id { get; set; }
        public string Event_Name { get; set; }
        public string Event_id { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Event_Label { get; set; }
    }
}
