//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Management_Multiname
    {
        public int ID { get; set; }
        public string EventID { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<System.DateTime> uploaddate { get; set; }
        public string Shift { get; set; }
    }
}
