//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Secondary_MSM
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string Event_ID { get; set; }
        public string Event_Name { get; set; }
        public string Event_Transfer_for { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> Event_date { get; set; }
        public string Event_Textboxid { get; set; }
    }
}
