//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback_Query_Table
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public string Query_Title { get; set; }
        public string Query_Reason { get; set; }
        public string Query_Application_Name { get; set; }
        public Nullable<System.DateTime> Query_generate_date { get; set; }
        public string active { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> query_complition_date { get; set; }
        public string remark_on_completion { get; set; }
        public string PersonID { get; set; }
    }
}
