//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Final_Inspection_Process_Rework
    {
        public int ID { get; set; }
        public int PID { get; set; }
        public int MID { get; set; }
        public string Inspection_ID { get; set; }
        public string JobNum { get; set; }
        public string PartNum { get; set; }
        public string Inspection_Type { get; set; }
        public Nullable<System.DateTime> Inspection_date { get; set; }
        public string DecisionType { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> reject_qty { get; set; }
        public Nullable<System.DateTime> sent_date { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
        public string done_by { get; set; }
        public string decision_of_MRB { get; set; }
        public string MRB_Comment { get; set; }
        public Nullable<System.DateTime> MRB_Date { get; set; }
        public Nullable<bool> CompleteRework { get; set; }
        public Nullable<int> Inspectionqty { get; set; }
        public string Qualitystage { get; set; }
    }
}
