//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Final_Inspection_MRB_DecisionData
    {
        public int ID { get; set; }
        public int IID { get; set; }
        public int PID { get; set; }
        public string MRBDecision { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Time { get; set; }
        public string OkQty { get; set; }
        public string RejectQty { get; set; }
        public string Remark { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
    }
}
