//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Final_Inspection_Mrb_Rcode
    {
        public int id { get; set; }
        public Nullable<int> PID { get; set; }
        public string Rtaxt { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Desicion { get; set; }
        public string Rcode { get; set; }
        public string SubQty { get; set; }
        public string DesicionSubQty { get; set; }
        public Nullable<int> mrbsubqty { get; set; }
        public Nullable<int> Reject { get; set; }
        public Nullable<int> Accept { get; set; }
        public Nullable<int> Rework { get; set; }
        public Nullable<int> Sorting { get; set; }
        public Nullable<int> Resorting { get; set; }
        public Nullable<int> Deviation { get; set; }
        public Nullable<int> Reworkinmrb { get; set; }
        public Nullable<int> Remeasured { get; set; }
        public Nullable<int> Split { get; set; }
        public Nullable<int> Hold { get; set; }
    }
}
