//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Final_Inspection_Mrb_Data
    {
        public int ID { get; set; }
        public int Qty { get; set; }
        public string Desccription { get; set; }
        public string location { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Stage { get; set; }
        public Nullable<int> Gid { get; set; }
        public string JobNo { get; set; }
        public string PartNo { get; set; }
    }
}
