//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Final_Inspection_LogTable
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CurrentDateTime { get; set; }
        public string Message { get; set; }
        public string Exception { get; set; }
        public string PageName { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public string MethodName { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
