//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Final_Inspection_Stage_Master
    {
        public int ID { get; set; }
        public Nullable<int> Stage { get; set; }
        public string stage_part_status { get; set; }
        public string ProcessTypes { get; set; }
    }
}
