//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Final_Inspection_Process
    {
        public int ID { get; set; }
        public int PID { get; set; }
        public int MID { get; set; }
        public string Inspection_ID { get; set; }
        public Nullable<int> Rework_Id { get; set; }
        public string Process { get; set; }
        public string JobNum { get; set; }
        public string PartNum { get; set; }
        public string Inspection_Type { get; set; }
        public Nullable<System.DateTime> Inspection_date { get; set; }
        public string starttime { get; set; }
        public string endtime { get; set; }
        public Nullable<int> Inspection_Qty { get; set; }
        public string done_by { get; set; }
        public Nullable<int> Non_conformance_Part_Qty { get; set; }
        public string Non_conformance_defect { get; set; }
        public string decision_by_MRB { get; set; }
        public Nullable<int> reject_Qty { get; set; }
        public Nullable<int> accept_Qty { get; set; }
        public Nullable<int> rework_Qty { get; set; }
        public Nullable<System.DateTime> MRB_date { get; set; }
        public string Gauge_No { get; set; }
        public Nullable<System.DateTime> Upload_date { get; set; }
        public string MRB_Comment { get; set; }
        public string Accept_Remark { get; set; }
        public string reject_remark { get; set; }
        public string rework_remark { get; set; }
        public string accept_mrb { get; set; }
        public string reject_mrb { get; set; }
        public string rework_mrb { get; set; }
        public string Stage { get; set; }
        public Nullable<bool> CkMRB { get; set; }
        public Nullable<bool> Statuschange { get; set; }
        public string QualityStage { get; set; }
        public Nullable<bool> waitingMRB { get; set; }
        public Nullable<bool> waitngsorting { get; set; }
        public Nullable<bool> deviation { get; set; }
        public Nullable<bool> reworkWAITING { get; set; }
        public Nullable<bool> packingwaiting { get; set; }
        public Nullable<bool> rejectwaiting { get; set; }
    }
}
