//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Final_Inspection_Stage_Data
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int Inspection_ID { get; set; }
        public System.DateTime CurrentDateTime { get; set; }
        public string JobNum { get; set; }
        public string PartNum { get; set; }
        public string Stage { get; set; }
        public string Qty { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string InspectionType { get; set; }
        public string stageno { get; set; }
        public string Qualitystage { get; set; }
    }
}
