//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class formula_master_tbl
    {
        public int id { get; set; }
        public string formula { get; set; }
        public string formated_formula { get; set; }
        public string added_by { get; set; }
        public Nullable<byte> is_active { get; set; }
    }
}
