//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class gatepass
    {
        public string GPNo { get; set; }
        public int id { get; set; }
        public int gid { get; set; }
        public Nullable<System.DateTime> gatedate { get; set; }
        public string suppliername { get; set; }
        public string descriptionofgoods { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> price { get; set; }
        public string remarks { get; set; }
        public string authorizedperson { get; set; }
        public string status { get; set; }
        public string receiverperson { get; set; }
        public Nullable<System.DateTime> deliverydate { get; set; }
        public Nullable<System.DateTime> returneddate { get; set; }
        public Nullable<System.DateTime> cancelleddate { get; set; }
        public string reasonfordeletegatepass { get; set; }
        public Nullable<int> receivedQty { get; set; }
        public string receiverremark { get; set; }
        public string supplieraddress { get; set; }
        public string gatepasstye { get; set; }
        public string weight { get; set; }
        public Nullable<decimal> totalmaterialcost { get; set; }
        public string sswpart { get; set; }
        public string approxsswpartqty { get; set; }
        public string authorisedperson { get; set; }
        public Nullable<int> receivedsswpartqty { get; set; }
        public Nullable<decimal> receivedpartweight { get; set; }
        public string supplierphone { get; set; }
        public string suppliergst { get; set; }
        public string supplieremail { get; set; }
        public Nullable<int> userid { get; set; }
        public string department { get; set; }
        public string historyallow { get; set; }
        public Nullable<int> returnst { get; set; }
        public Nullable<int> pending_qty { get; set; }
        public string copytype { get; set; }
        public Nullable<int> copytypeconfirm { get; set; }
        public string force_close_reason { get; set; }
    }
}
