//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspectr
    {
        public string Company { get; set; }
        public string InspectorID { get; set; }
        public string Name { get; set; }
        public bool InActive { get; set; }
        public string CnvEmpID { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public Nullable<System.Guid> ForeignSysRowID { get; set; }
        public byte[] UD_SysRevID { get; set; }
        public Nullable<int> StampID_c { get; set; }
        public Nullable<System.DateTime> StampIssued_c { get; set; }
        public Nullable<System.DateTime> StampReturned_c { get; set; }
        public Nullable<bool> StampActive_c { get; set; }
    }
}
