//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview_Answer_verify
    {
        public int IID { get; set; }
        public int MID { get; set; }
        public Nullable<int> Personal_ID { get; set; }
        public string Question { get; set; }
        public string answer_ticked { get; set; }
        public string actual_answer { get; set; }
        public string Type { get; set; }
    }
}
