//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISQuery
    {
        public int ID { get; set; }
        public string QTitle { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> CompeletedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> PersonId { get; set; }
    }
}
