//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobwork
    {
        public string gatepassno { get; set; }
        public int id { get; set; }
        public int pid { get; set; }
        public Nullable<System.DateTime> gdate { get; set; }
        public string suppliername { get; set; }
        public string supplieraddress { get; set; }
        public string descriptionofgoods { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> totalmaterialcost { get; set; }
        public string sswpart { get; set; }
        public string approxsswpartqty { get; set; }
        public string authorisedperson { get; set; }
        public string status { get; set; }
        public string receiverperson { get; set; }
        public Nullable<System.DateTime> deliverydate { get; set; }
        public Nullable<System.DateTime> returneddate { get; set; }
        public Nullable<System.DateTime> cancelleddate { get; set; }
        public string reasonfordelete { get; set; }
        public Nullable<decimal> receivedsswpartqty { get; set; }
        public Nullable<decimal> receivedpartweight { get; set; }
        public string receiverremark { get; set; }
    }
}
