//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public string Company { get; set; }
        public string MenuID { get; set; }
        public string MenuDesc { get; set; }
        public string ParentMenuID { get; set; }
        public int Sequence { get; set; }
        public string OptionType { get; set; }
        public string OptionSubType { get; set; }
        public string Program { get; set; }
        public bool Enabled { get; set; }
        public string SecCode { get; set; }
        public bool DoNotDisplayInMenu { get; set; }
        public string Arguments { get; set; }
        public string Module { get; set; }
        public string MenuType { get; set; }
        public string CGCCode { get; set; }
        public string DashboardID { get; set; }
        public bool ExpressAvailable { get; set; }
        public string SystemCode { get; set; }
        public string OldProgram { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }
        public bool CRMMenu { get; set; }
        public bool SystemFlag { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public string SaaSParam { get; set; }
        public int CompanyVisibility { get; set; }
        public string WebResourceURL { get; set; }
        public string DefaultFormType { get; set; }
        public string ShortChar01 { get; set; }
        public Nullable<System.Guid> ForeignSysRowID { get; set; }
        public byte[] UD_SysRevID { get; set; }
    }
}
