//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MscShpDt
    {
        public string Company { get; set; }
        public int PackNum { get; set; }
        public int PackLine { get; set; }
        public string LineType { get; set; }
        public int Packages { get; set; }
        public string PartNum { get; set; }
        public string LineDesc { get; set; }
        public string IUM { get; set; }
        public string RevisionNum { get; set; }
        public string ShipComment { get; set; }
        public string XPartNum { get; set; }
        public string XRevisionNum { get; set; }
        public int ShpConNum { get; set; }
        public string WUM { get; set; }
        public string LotNum { get; set; }
        public int CustNum { get; set; }
        public string ShipToNum { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string Plant { get; set; }
        public decimal Quantity { get; set; }
        public int CallNum { get; set; }
        public int CallLine { get; set; }
        public int MtlSeq { get; set; }
        public int AssemblySeq { get; set; }
        public string JobNum { get; set; }
        public int DMRNum { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public int ChangeTime { get; set; }
        public int ShipToCustNum { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public int RMAReceipt { get; set; }
        public int RMADisp { get; set; }
        public Nullable<decimal> Number01 { get; set; }
        public Nullable<System.Guid> ForeignSysRowID { get; set; }
        public byte[] UD_SysRevID { get; set; }
        public Nullable<decimal> PartNetWeight_c { get; set; }
    }
}
