//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartCost
    {
        public string Company { get; set; }
        public string PartNum { get; set; }
        public string CostID { get; set; }
        public decimal AvgLaborCost { get; set; }
        public decimal AvgBurdenCost { get; set; }
        public decimal AvgMaterialCost { get; set; }
        public decimal AvgSubContCost { get; set; }
        public decimal AvgMtlBurCost { get; set; }
        public decimal StdLaborCost { get; set; }
        public decimal StdBurdenCost { get; set; }
        public decimal StdMaterialCost { get; set; }
        public decimal StdSubContCost { get; set; }
        public decimal StdMtlBurCost { get; set; }
        public decimal LastLaborCost { get; set; }
        public decimal LastBurdenCost { get; set; }
        public decimal LastMaterialCost { get; set; }
        public decimal LastSubContCost { get; set; }
        public decimal LastMtlBurCost { get; set; }
        public decimal FIFOAvgLaborCost { get; set; }
        public decimal FIFOAvgBurdenCost { get; set; }
        public decimal FIFOAvgMaterialCost { get; set; }
        public decimal FIFOAvgSubContCost { get; set; }
        public decimal FIFOAvgMtlBurCost { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public decimal TotalQtyAvg { get; set; }
        public bool ExternalMESSyncRequired { get; set; }
        public Nullable<System.DateTime> ExternalMESLastSync { get; set; }
    }
}
