//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartBin
    {
        public string Company { get; set; }
        public string PartNum { get; set; }
        public string WarehouseCode { get; set; }
        public string BinNum { get; set; }
        public decimal OnhandQty { get; set; }
        public string LotNum { get; set; }
        public string DimCode { get; set; }
        public decimal AllocatedQty { get; set; }
        public decimal SalesAllocatedQty { get; set; }
        public decimal SalesPickingQty { get; set; }
        public decimal SalesPickedQty { get; set; }
        public decimal JobAllocatedQty { get; set; }
        public decimal JobPickingQty { get; set; }
        public decimal JobPickedQty { get; set; }
        public decimal TFOrdAllocatedQty { get; set; }
        public decimal TFOrdPickingQty { get; set; }
        public decimal TFOrdPickedQty { get; set; }
        public decimal ShippingQty { get; set; }
        public decimal PackedQty { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public string PCID { get; set; }
        public bool SendToFSA { get; set; }
    }
}
