//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartPlant
    {
        public string Company { get; set; }
        public string Plant { get; set; }
        public string PartNum { get; set; }
        public string PrimWhse { get; set; }
        public decimal MinimumQty { get; set; }
        public decimal MaximumQty { get; set; }
        public decimal SafetyQty { get; set; }
        public decimal MinOrderQty { get; set; }
        public int LeadTime { get; set; }
        public int VendorNum { get; set; }
        public string PurPoint { get; set; }
        public bool BackFlush { get; set; }
        public decimal MfgLotSize { get; set; }
        public decimal MinMfgLotSize { get; set; }
        public decimal MaxMfgLotSize { get; set; }
        public decimal MfgLotMultiple { get; set; }
        public int DaysOfSupply { get; set; }
        public bool ReOrderLevel { get; set; }
        public bool MRPRecalcNeeded { get; set; }
        public bool ProcessMRP { get; set; }
        public bool GenerateSugg { get; set; }
        public bool GetFromLocalWhse { get; set; }
        public int ForecastTime { get; set; }
        public string TransferPlant { get; set; }
        public string SourceType { get; set; }
        public int TransferLeadTime { get; set; }
        public int PrepTime { get; set; }
        public int ReceiveTime { get; set; }
        public int PlanTimeFence { get; set; }
        public int ReschedOutDelta { get; set; }
        public int ReschedInDelta { get; set; }
        public bool NonStock { get; set; }
        public bool PhantomBOM { get; set; }
        public string BuyerID { get; set; }
        public string PersonID { get; set; }
        public string CostMethod { get; set; }
        public string AltMethod { get; set; }
        public int KitTime { get; set; }
        public bool KitAllowUpdate { get; set; }
        public bool KitShipComplete { get; set; }
        public bool KitAllowChangeParms { get; set; }
        public bool KitBackFlush { get; set; }
        public string KitPricing { get; set; }
        public bool KitPrintCompsPS { get; set; }
        public bool KitPrintCompsInv { get; set; }
        public int ShortHorizonDays { get; set; }
        public decimal ShortHorizonMinMfgLotSize { get; set; }
        public decimal ShortHorizonMaxMfgLotSize { get; set; }
        public bool LimitProdYldRecalc { get; set; }
        public bool QtyBearing { get; set; }
        public Nullable<System.DateTime> MRPLastRunDate { get; set; }
        public int MRPLastRunTime { get; set; }
        public Nullable<System.DateTime> MRPLastScheduledDate { get; set; }
        public Nullable<System.DateTime> MRPLastCutOffDate { get; set; }
        public int ShortHorizonDaysSupp { get; set; }
        public string SNMask { get; set; }
        public string SNMaskExample { get; set; }
        public string SNBaseDataType { get; set; }
        public string SNFormat { get; set; }
        public string SNPrefix { get; set; }
        public string SNMaskSuffix { get; set; }
        public string SNMaskPrefix { get; set; }
        public string SNLastUsedSeq { get; set; }
        public bool UseMaskSeq { get; set; }
        public bool BuyToOrder { get; set; }
        public bool DropShip { get; set; }
        public decimal PcntTolerance { get; set; }
        public bool CalcPcnt { get; set; }
        public bool CalcQty { get; set; }
        public bool CalcValue { get; set; }
        public decimal QtyAdjTolerance { get; set; }
        public decimal QtyTolerance { get; set; }
        public decimal ValueTolerance { get; set; }
        public decimal DemandQty { get; set; }
        public decimal ReservedQty { get; set; }
        public decimal AllocatedQty { get; set; }
        public string XRefPartNum { get; set; }
        public string XRefPartType { get; set; }
        public bool NeverReuseMRPJob { get; set; }
        public bool DeleteMRPJobs { get; set; }
        public int TotMfgLeadTimeSys { get; set; }
        public int TotMfgLeadTimeMnl { get; set; }
        public int LvlMfgLeadTimeSys { get; set; }
        public int LvlMfgLeadTimeMnl { get; set; }
        public Nullable<System.DateTime> MfgLeadTimeCalcDate { get; set; }
        public Nullable<System.DateTime> MfgLeadTimeMnlDate { get; set; }
        public bool AutoConsumeStock { get; set; }
        public bool StartMinLotQty { get; set; }
        public int MinLotLeadTime { get; set; }
        public bool MfgLeadTimeMnl { get; set; }
        public string MfgLeadTimeEnteredBy { get; set; }
        public decimal MinStartQty { get; set; }
        public bool RawMaterial { get; set; }
        public bool MultiLevelCTP { get; set; }
        public bool RcvInspectionReq { get; set; }
        public bool ConsumeSafety { get; set; }
        public int SLTVendorNum { get; set; }
        public string SLTPurPoint { get; set; }
        public int ShortLeadTime { get; set; }
        public bool ExternalMES { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public int UrgentLeadTime { get; set; }
        public decimal UrgentMinOrdQty { get; set; }
        public decimal UrgentMultQty { get; set; }
        public string UrgentPurPoint { get; set; }
        public int UrgentVendorNum { get; set; }
        public bool PartRunMRP { get; set; }
        public bool LinkToContract { get; set; }
        public bool MMSExclude { get; set; }
        public bool MMSSales { get; set; }
        public bool MMSIssue { get; set; }
        public int MMSHistory { get; set; }
        public int MMSSafetyFactor { get; set; }
        public decimal MMSMaxFactor { get; set; }
        public decimal SavedMinimumQty { get; set; }
        public decimal SavedMaximumQty { get; set; }
        public decimal SavedSafetyQty { get; set; }
        public decimal SavedCalculatedUsageQty { get; set; }
        public Nullable<System.DateTime> SavedOnDateTime { get; set; }
        public int ACWPercentage { get; set; }
        public int ACWDays { get; set; }
        public int GenNewPCIDDelaySeconds { get; set; }
        public int GenNewPCIDLimitDays { get; set; }
        public int TopLvlMfgLeadTimeSys { get; set; }
        public int TopLvlMfgLeadTimeMnl { get; set; }
        public Nullable<decimal> Number01 { get; set; }
        public Nullable<decimal> Number02 { get; set; }
        public Nullable<System.Guid> ForeignSysRowID { get; set; }
        public byte[] UD_SysRevID { get; set; }
    }
}
