//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerCon
    {
        public string Company { get; set; }
        public int PerConID { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PRName { get; set; }
        public string Func { get; set; }
        public string FaxNum { get; set; }
        public string PhoneNum { get; set; }
        public string EMailAddress { get; set; }
        public string CellPhoneNum { get; set; }
        public string PagerNum { get; set; }
        public string HomeNum { get; set; }
        public string AltNum { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
        public string Initials { get; set; }
        public string WebSite { get; set; }
        public string IM { get; set; }
        public string Twitter { get; set; }
        public string LinkedIn { get; set; }
        public string FaceBook { get; set; }
        public string WebLink1 { get; set; }
        public string WebLink2 { get; set; }
        public string WebLink3 { get; set; }
        public string WebLink4 { get; set; }
        public string WebLink5 { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public int CountryNum { get; set; }
        public string CorpName { get; set; }
        public string RoleCode { get; set; }
        public string Comment { get; set; }
        public string ContactTitle { get; set; }
        public string ReportsTo { get; set; }
        public string PRLastName { get; set; }
        public string PRFirstName { get; set; }
        public string PRMiddleName { get; set; }
        public string DcdUserID { get; set; }
        public string PhotoFile { get; set; }
        public bool GlobalPerCon { get; set; }
        public bool GlobalLock { get; set; }
        public bool HCMLinked { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public string IssuerPrsnIDCode { get; set; }
        public string IssuerIDType { get; set; }
        public string IssuerName { get; set; }
        public string IssuerSurname { get; set; }
        public string IssuerSerialNum { get; set; }
        public Nullable<System.DateTime> IssuerIDIssDate { get; set; }
        public string ImageID { get; set; }
        public string Character01 { get; set; }
        public string Character02 { get; set; }
        public Nullable<bool> CheckBox01 { get; set; }
        public Nullable<System.Guid> ForeignSysRowID { get; set; }
        public byte[] UD_SysRevID { get; set; }
    }
}
