//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class POHeader
    {
        public string Company { get; set; }
        public bool OpenOrder { get; set; }
        public bool VoidOrder { get; set; }
        public int PONum { get; set; }
        public string EntryPerson { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string FOB { get; set; }
        public string ShipViaCode { get; set; }
        public string TermsCode { get; set; }
        public string ShipName { get; set; }
        public string ShipAddress1 { get; set; }
        public string ShipAddress2 { get; set; }
        public string ShipAddress3 { get; set; }
        public string ShipCity { get; set; }
        public string ShipState { get; set; }
        public string ShipZIP { get; set; }
        public string ShipCountry { get; set; }
        public string BuyerID { get; set; }
        public bool FreightPP { get; set; }
        public int PrcConNum { get; set; }
        public int VendorNum { get; set; }
        public string PurPoint { get; set; }
        public string CommentText { get; set; }
        public bool OrderHeld { get; set; }
        public string ShipToConName { get; set; }
        public bool ReadyToPrint { get; set; }
        public string PrintAs { get; set; }
        public string CurrencyCode { get; set; }
        public decimal ExchangeRate { get; set; }
        public bool LockRate { get; set; }
        public int ShipCountryNum { get; set; }
        public bool LogChanges { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool Approve { get; set; }
        public string ApprovalStatus { get; set; }
        public decimal ApprovedAmount { get; set; }
        public bool PostToWeb { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string VendorRefNum { get; set; }
        public bool ConfirmReq { get; set; }
        public bool Confirmed { get; set; }
        public string ConfirmVia { get; set; }
        public int OrderNum { get; set; }
        public string LegalNumber { get; set; }
        public bool Linked { get; set; }
        public string ExtCompany { get; set; }
        public string XRefPONum { get; set; }
        public bool ConsolidatedPO { get; set; }
        public string GlbCompany { get; set; }
        public bool ContractOrder { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public bool PrintHeaderAddress { get; set; }
        public string RateGrpCode { get; set; }
        public string POType { get; set; }
        public string APLOCID { get; set; }
        public string TranDocTypeID { get; set; }
        public bool AutoPrintReady { get; set; }
        public bool ICPOLocked { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> PromiseDate { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public bool POTaxReadyToProcess { get; set; }
        public string TaxRegionCode { get; set; }
        public Nullable<System.DateTime> TaxPoint { get; set; }
        public Nullable<System.DateTime> TaxRateDate { get; set; }
        public decimal TotalTax { get; set; }
        public decimal DocTotalTax { get; set; }
        public decimal Rpt1TotalTax { get; set; }
        public decimal Rpt2TotalTax { get; set; }
        public decimal Rpt3TotalTax { get; set; }
        public decimal TotalWhTax { get; set; }
        public decimal DocTotalWhTax { get; set; }
        public decimal Rpt1TotalWhTax { get; set; }
        public decimal Rpt2TotalWhTax { get; set; }
        public decimal Rpt3TotalWhTax { get; set; }
        public decimal TotalSATax { get; set; }
        public decimal DocTotalSATax { get; set; }
        public decimal Rpt1TotalSATax { get; set; }
        public decimal Rpt2TotalSATax { get; set; }
        public decimal Rpt3TotalSATax { get; set; }
        public bool InPrice { get; set; }
        public bool HdrTaxNoUpdt { get; set; }
        public string TaxRateGrpCode { get; set; }
        public decimal TotalDedTax { get; set; }
        public decimal DocTotalDedTax { get; set; }
        public decimal Rpt1TotalDedTax { get; set; }
        public decimal Rpt2TotalDedTax { get; set; }
        public decimal Rpt3TotalDedTax { get; set; }
        public decimal TotalCharges { get; set; }
        public decimal TotalMiscCharges { get; set; }
        public decimal TotalOrder { get; set; }
        public decimal DocTotalCharges { get; set; }
        public decimal DocTotalMisc { get; set; }
        public decimal DocTotalOrder { get; set; }
        public decimal Rpt1TotalCharges { get; set; }
        public decimal Rpt2TotalCharges { get; set; }
        public decimal Rpt3TotalCharges { get; set; }
        public decimal Rpt1TotalMiscCharges { get; set; }
        public decimal Rpt2TotalMiscCharges { get; set; }
        public decimal Rpt3TotalMiscCharges { get; set; }
        public decimal Rpt1TotalOrder { get; set; }
        public decimal Rpt2TotalOrder { get; set; }
        public decimal Rpt3TotalOrder { get; set; }
        public string Character01 { get; set; }
        public string Character03 { get; set; }
        public Nullable<System.DateTime> Date01 { get; set; }
        public Nullable<System.Guid> ForeignSysRowID { get; set; }
        public byte[] UD_SysRevID { get; set; }
    }
}
