//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORel
    {
        public string Company { get; set; }
        public bool OpenRelease { get; set; }
        public bool VoidRelease { get; set; }
        public int PONum { get; set; }
        public int POLine { get; set; }
        public int PORelNum { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public decimal XRelQty { get; set; }
        public decimal PurchasingFactor { get; set; }
        public decimal RelQty { get; set; }
        public string JobNum { get; set; }
        public int AssemblySeq { get; set; }
        public string JobSeqType { get; set; }
        public int JobSeq { get; set; }
        public string WarehouseCode { get; set; }
        public decimal ReceivedQty { get; set; }
        public bool ExpOverride { get; set; }
        public int ReqNum { get; set; }
        public int ReqLine { get; set; }
        public string Plant { get; set; }
        public Nullable<System.DateTime> PromiseDt { get; set; }
        public string ProjectID { get; set; }
        public bool Confirmed { get; set; }
        public string ConfirmVia { get; set; }
        public Nullable<System.DateTime> ReqChgDate { get; set; }
        public decimal ReqChgQty { get; set; }
        public string LockRel { get; set; }
        public string RefDisplayAccount { get; set; }
        public string RefType { get; set; }
        public string RefCode { get; set; }
        public string RefCodeDesc { get; set; }
        public int OrderNum { get; set; }
        public int OrderLine { get; set; }
        public int OrderRelNum { get; set; }
        public bool Linked { get; set; }
        public string ExtCompany { get; set; }
        public decimal ShippedQty { get; set; }
        public string TranType { get; set; }
        public string GlbCompany { get; set; }
        public string GlbPlant { get; set; }
        public string GlbWarehouse { get; set; }
        public bool GlbCreateJobMtl { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public int ContainerID { get; set; }
        public string PurchasingFactorDirection { get; set; }
        public Nullable<System.DateTime> PreviousDueDate { get; set; }
        public decimal BaseQty { get; set; }
        public string BaseUOM { get; set; }
        public int BTOOrderNum { get; set; }
        public int BTOOrderLine { get; set; }
        public int BTOOrderRelNum { get; set; }
        public bool DropShip { get; set; }
        public string ShipToNum { get; set; }
        public int SoldToNum { get; set; }
        public decimal SMIRcvdQty { get; set; }
        public int ShpConNum { get; set; }
        public int ShipToCustNum { get; set; }
        public int MangCustNum { get; set; }
        public bool UseOTS { get; set; }
        public string OTSName { get; set; }
        public string OTSAddress1 { get; set; }
        public string OTSAddress2 { get; set; }
        public string OTSAddress3 { get; set; }
        public string OTSCity { get; set; }
        public string OTSState { get; set; }
        public string OTSZIP { get; set; }
        public string OTSResaleID { get; set; }
        public string OTSContact { get; set; }
        public string OTSFaxNum { get; set; }
        public string OTSPhoneNum { get; set; }
        public int OTSCountryNum { get; set; }
        public string ComplianceMsg { get; set; }
        public bool PORelOpen { get; set; }
        public bool Mapping { get; set; }
        public string PhaseID { get; set; }
        public string WBSPhaseID { get; set; }
        public bool IsMultiRel { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public decimal SMIRemQty { get; set; }
        public bool LockQty { get; set; }
        public bool LockDate { get; set; }
        public bool DueDateChanged { get; set; }
        public string ContractID { get; set; }
        public bool LinkToContract { get; set; }
        public string Status { get; set; }
        public decimal ArrivedQty { get; set; }
        public decimal InvoicedQty { get; set; }
        public Nullable<System.DateTime> NeedByDate { get; set; }
        public bool LockNeedByDate { get; set; }
        public decimal InspectionQty { get; set; }
        public decimal FailedQty { get; set; }
        public decimal PassedQty { get; set; }
        public bool ProjProcessed { get; set; }
        public string DeliverTo { get; set; }
        public bool Taxable { get; set; }
        public string TaxExempt { get; set; }
        public bool NoTaxRecalc { get; set; }
        public bool EpicorFSA { get; set; }
        public Nullable<System.DateTime> ReqChgPromiseDate { get; set; }
        public string Character01 { get; set; }
        public string Character02 { get; set; }
        public Nullable<decimal> Number01 { get; set; }
        public Nullable<System.DateTime> Date01 { get; set; }
        public Nullable<System.DateTime> Date06 { get; set; }
        public Nullable<System.Guid> ForeignSysRowID { get; set; }
        public byte[] UD_SysRevID { get; set; }
    }
}
