//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production_ECR_Data
    {
        public int Id { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string ECR_ID { get; set; }
        public string Production_ID { get; set; }
        public string Job_No { get; set; }
        public string Part_Number { get; set; }
        public string Op_No { get; set; }
        public string Rev_No { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> ecr_date { get; set; }
        public string ECN_ID { get; set; }
        public Nullable<bool> Dimentional { get; set; }
        public Nullable<bool> Asthetical { get; set; }
        public Nullable<bool> functional { get; set; }
    }
}
