//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production_Utilization
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string Setup_ID { get; set; }
        public string JobNum { get; set; }
        public string PartNum { get; set; }
        public string Machine_Name { get; set; }
        public string Shift { get; set; }
        public Nullable<System.DateTime> Upload_date { get; set; }
        public Nullable<decimal> Machine_utilization { get; set; }
        public Nullable<decimal> Productive_time { get; set; }
        public Nullable<decimal> non_productive_time { get; set; }
        public Nullable<decimal> machining_quality { get; set; }
        public string status { get; set; }
    }
}
