//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production_Setup_Dtls
    {
        public int Id { get; set; }
        public int PID { get; set; }
        public int Setup_ID { get; set; }
        public string JobNum { get; set; }
        public string PartNum { get; set; }
        public string RevNo { get; set; }
        public Nullable<int> OP { get; set; }
        public string Shift { get; set; }
        public Nullable<int> PersonID { get; set; }
        public string Setup { get; set; }
        public Nullable<decimal> setup_Time { get; set; }
        public Nullable<decimal> Cycle_Time { get; set; }
        public Nullable<decimal> Loading_Time { get; set; }
        public Nullable<decimal> Other_Time { get; set; }
        public Nullable<decimal> OK_QTY { get; set; }
        public Nullable<decimal> Reject_Qty { get; set; }
        public Nullable<decimal> NonCon_Qty { get; set; }
        public Nullable<decimal> Total_Qty { get; set; }
        public Nullable<decimal> Remaining_Qty { get; set; }
        public Nullable<decimal> Time_For_Total_Qty { get; set; }
        public Nullable<System.DateTime> Updatedate { get; set; }
        public string status { get; set; }
        public string Machine { get; set; }
        public string Machine_no { get; set; }
        public string Machine_Name { get; set; }
        public Nullable<System.DateTime> uploaddate { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public Nullable<decimal> Setup_time_total { get; set; }
        public string Remark_For_Machine { get; set; }
        public string Remark_For_Job { get; set; }
        public Nullable<decimal> Force_qty { get; set; }
        public Nullable<bool> Force_close { get; set; }
        public Nullable<decimal> lot_Qty { get; set; }
        public string Type { get; set; }
    }
}
