//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_Flex_Bulk_Shaft_Issue
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string Inventory_ID { get; set; }
        public string Shaft_Part_Number { get; set; }
        public string Job_Number { get; set; }
        public Nullable<System.DateTime> Issue_Date { get; set; }
        public string Issue_time { get; set; }
        public string Operator { get; set; }
        public string Issue_Machine_Name { get; set; }
        public string Issue_Machine_No { get; set; }
        public Nullable<decimal> Issue_Feet { get; set; }
        public string Shift { get; set; }
        public string Comment { get; set; }
    }
}
