//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production_Tool_Details
    {
        public int Id { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string ToolID { get; set; }
        public string Production_Id { get; set; }
        public string JobNum { get; set; }
        public string PartNum { get; set; }
        public string RevNo { get; set; }
        public Nullable<int> OpNo { get; set; }
        public string Shift { get; set; }
        public string Operator { get; set; }
        public string Toolname { get; set; }
        public string InsertOrCorner { get; set; }
        public string NewOrUsed { get; set; }
        public string RuffOrFinish { get; set; }
        public Nullable<int> PieceMade { get; set; }
        public string Remark { get; set; }
    }
}
