//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production_Qtydtls
    {
        public int Id { get; set; }
        public int PID { get; set; }
        public int MID { get; set; }
        public string JobNum { get; set; }
        public Nullable<int> OpNo { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string reason { get; set; }
        public string Type_of_Qty { get; set; }
        public string Shift { get; set; }
        public string Operator { get; set; }
        public string setup { get; set; }
        public Nullable<System.DateTime> uploaddate { get; set; }
        public string Machine { get; set; }
    }
}
