//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_Flex_Inventory
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string Inventory_ID { get; set; }
        public Nullable<System.DateTime> inventory_date { get; set; }
        public string Machine_name { get; set; }
        public string Machine_no { get; set; }
        public string Part_name { get; set; }
        public string Job_number { get; set; }
        public Nullable<decimal> weight_kg { get; set; }
        public Nullable<decimal> feet { get; set; }
        public string inventory_time { get; set; }
        public Nullable<decimal> current_stock { get; set; }
        public Nullable<decimal> reel_stock { get; set; }
        public string status { get; set; }
        public Nullable<bool> Job_to_MES_Production { get; set; }
        public Nullable<bool> Job_to_MES_Quality { get; set; }
        public Nullable<bool> Job_to_Inventory { get; set; }
        public Nullable<System.DateTime> Issue_date { get; set; }
        public string Issue_time { get; set; }
        public string Issue_Machine_Name { get; set; }
        public string Issue_Machine_No { get; set; }
        public Nullable<decimal> Issue_Feet { get; set; }
        public string Part_Name_For_issue { get; set; }
        public string AFC_MSM_Job_No { get; set; }
        public string AFC_Operator { get; set; }
        public string Reel_Issue_Shift { get; set; }
        public Nullable<bool> Issue_Material { get; set; }
        public Nullable<System.DateTime> Return_Date { get; set; }
        public string Return_Time { get; set; }
        public Nullable<decimal> Return_weight_kg { get; set; }
        public Nullable<decimal> Return_feet { get; set; }
        public Nullable<bool> Reel_Return_Shift { get; set; }
        public string Responsible_MSM_Operator { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> Return_Material { get; set; }
        public Nullable<System.DateTime> Reel_Issue_Date { get; set; }
        public string Reel_Issue_Time { get; set; }
        public string AFC_MSM_Machine_Name { get; set; }
        public string AFC_MSM_Machine_No { get; set; }
        public Nullable<decimal> Issue_Weight_Kg { get; set; }
    }
}
