//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production_Final_Data
    {
        public int ID { get; set; }
        public string Setup_ID { get; set; }
        public string Shift { get; set; }
        public string Person { get; set; }
        public string Machine { get; set; }
        public string JobNum { get; set; }
        public string PartNum { get; set; }
        public string Op { get; set; }
        public string Rev { get; set; }
        public Nullable<System.DateTime> Setup_Start { get; set; }
        public Nullable<System.DateTime> Setup_Continue { get; set; }
        public Nullable<System.DateTime> Setup_End { get; set; }
        public Nullable<decimal> Setup_Time { get; set; }
        public Nullable<decimal> Cycle_Time { get; set; }
        public Nullable<decimal> Loading_Time { get; set; }
        public Nullable<decimal> Other_Time { get; set; }
        public Nullable<decimal> OK_Qty { get; set; }
        public Nullable<decimal> Reject_Qty { get; set; }
        public Nullable<decimal> NonCon_Qty { get; set; }
        public Nullable<System.DateTime> Uploaddate { get; set; }
    }
}
