//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production_Production_dtls
    {
        public int ID { get; set; }
        public int PID { get; set; }
        public int MID { get; set; }
        public int Setup_ID { get; set; }
        public string JobNum { get; set; }
        public string PartNum { get; set; }
        public string RevNo { get; set; }
        public Nullable<int> OP { get; set; }
        public string Shift { get; set; }
        public Nullable<decimal> Cycle_time { get; set; }
        public Nullable<decimal> Setup_time { get; set; }
        public Nullable<decimal> Loading_Time { get; set; }
        public Nullable<decimal> OK_Qty { get; set; }
        public Nullable<decimal> Reject_Qty { get; set; }
        public Nullable<decimal> NonCon_Qty { get; set; }
        public Nullable<decimal> Total_Qty { get; set; }
        public Nullable<decimal> Remaining_Qty { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public string Setup { get; set; }
        public string PersonID { get; set; }
        public string Machine { get; set; }
        public string Machine_No { get; set; }
        public string Machine_Name { get; set; }
        public Nullable<decimal> Lot_qty { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<decimal> Other_Time { get; set; }
        public Nullable<decimal> Production_time { get; set; }
    }
}
