//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class purreq
    {
        public string req_no { get; set; }
        public int id { get; set; }
        public int pid { get; set; }
        public string nameofinitiator { get; set; }
        public string department { get; set; }
        public string itemname { get; set; }
        public string purpose { get; set; }
        public string itemtype { get; set; }
        public string uom { get; set; }
        public Nullable<int> itemqty { get; set; }
        public Nullable<int> totalkg { get; set; }
        public Nullable<decimal> peruom_price { get; set; }
        public Nullable<decimal> extracharge { get; set; }
        public string suggested_supplier { get; set; }
        public string remark_on_item { get; set; }
        public Nullable<System.DateTime> askforquotation_date { get; set; }
        public string supplier_name { get; set; }
        public string epo { get; set; }
        public Nullable<System.DateTime> epo_date { get; set; }
        public string epo_status { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
        public Nullable<System.DateTime> bill_received_date { get; set; }
        public string remark_on_received_item { get; set; }
        public string purchaser_remark { get; set; }
        public string check_point { get; set; }
        public Nullable<System.DateTime> item_issue_date_against_req_no { get; set; }
        public string item_issue_to_person { get; set; }
        public string status { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<System.DateTime> req_date { get; set; }
        public Nullable<decimal> received_qty { get; set; }
        public string approval { get; set; }
        public string remarkonitem { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<bool> askforquotation { get; set; }
        public string billno { get; set; }
        public Nullable<int> pending_qty { get; set; }
        public string challan_no { get; set; }
        public string invoice_no { get; set; }
        public Nullable<int> qtymanage { get; set; }
        public string invoice_no2 { get; set; }
        public string invoice_no3 { get; set; }
        public string invoice_no4 { get; set; }
        public string invoice_no5 { get; set; }
        public string challan_no2 { get; set; }
        public string challan_no3 { get; set; }
        public string challan_no4 { get; set; }
        public string challan_no5 { get; set; }
        public string epo2 { get; set; }
        public string epo3 { get; set; }
        public string epo4 { get; set; }
        public string epo5 { get; set; }
        public string payslipnumber { get; set; }
        public string quotation_type { get; set; }
        public Nullable<int> epo_lineno { get; set; }
        public Nullable<decimal> itemqty_new { get; set; }
        public string issue_status { get; set; }
        public string attachment { get; set; }
        public string filter_allow { get; set; }
        public string reasonforedit { get; set; }
        public Nullable<decimal> issue_item_qty { get; set; }
        public string Remark_in_Query { get; set; }
        public Nullable<bool> Query_in_Req { get; set; }
        public Nullable<bool> Query_Resolve { get; set; }
        public string Query_Resolve_remark { get; set; }
        public Nullable<System.DateTime> Req_in_query_date { get; set; }
        public Nullable<System.DateTime> Query_resolve_date { get; set; }
        public string EPO_Attachment { get; set; }
        public Nullable<bool> perfoma_waiting { get; set; }
        public Nullable<System.DateTime> performa_waiting_date { get; set; }
        public Nullable<System.DateTime> intransit_date { get; set; }
        public string void_remark { get; set; }
        public Nullable<System.DateTime> Void_Date { get; set; }
    }
}
