//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class QCIncoming
    {
        public string PartNum { get; set; }
        public decimal OurQty { get; set; }
        public int PONum { get; set; }
        public int POLine { get; set; }
        public int PORelNum { get; set; }
        public Nullable<bool> CheckBox01 { get; set; }
        public Nullable<System.DateTime> Date01 { get; set; }
        public bool InspectionReq { get; set; }
        public bool InspectionPending { get; set; }
        public string Character01 { get; set; }
        public string Character02 { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
    }
}
