//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionEntry
    {
        public int ID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public string RequisitionNo { get; set; }
        public string ToolType { get; set; }
        public string ToolName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> PreviousQuantity { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<int> RID { get; set; }
        public Nullable<bool> F_Status { get; set; }
        public Nullable<int> DueQuantity { get; set; }
        public string SConfirmation { get; set; }
        public Nullable<int> IssueQut { get; set; }
    }
}
