//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceGroup
    {
        public string Company { get; set; }
        public string Plant { get; set; }
        public string ResourceGrpID { get; set; }
        public string Description { get; set; }
        public string CalendarID { get; set; }
        public bool Inactive { get; set; }
        public bool AllowManualOverride { get; set; }
        public int FiniteHorizon { get; set; }
        public int NumberOfMachines { get; set; }
        public int SchMachine { get; set; }
        public string BurdenType { get; set; }
        public decimal MoveHours { get; set; }
        public string JCDept { get; set; }
        public decimal QueHours { get; set; }
        public string OpCode { get; set; }
        public decimal ProdBurRate { get; set; }
        public decimal ProdLabRate { get; set; }
        public decimal SetupBurRate { get; set; }
        public decimal SetupLabRate { get; set; }
        public decimal QProdBurRate { get; set; }
        public decimal QProdLabRate { get; set; }
        public decimal QSetupBurRate { get; set; }
        public decimal QSetupLabRate { get; set; }
        public bool SplitBurden { get; set; }
        public decimal ProdCrewSize { get; set; }
        public decimal SetupCrewSize { get; set; }
        public string OpStdID { get; set; }
        public int ReloadNum { get; set; }
        public string ReloadStatus { get; set; }
        public decimal DailyCapacity1 { get; set; }
        public decimal DailyCapacity2 { get; set; }
        public decimal DailyCapacity3 { get; set; }
        public decimal DailyCapacity4 { get; set; }
        public decimal DailyCapacity5 { get; set; }
        public decimal DailyCapacity6 { get; set; }
        public decimal DailyCapacity7 { get; set; }
        public string QBurdenType { get; set; }
        public bool BurdenEQLabor { get; set; }
        public bool SplitOperations { get; set; }
        public string ResourceType { get; set; }
        public string InputWhse { get; set; }
        public string InputBinNum { get; set; }
        public string OutputWhse { get; set; }
        public string OutputBinNum { get; set; }
        public string BackflushWhse { get; set; }
        public string BackflushBinNum { get; set; }
        public bool InformOverload { get; set; }
        public decimal MinOverloadPerc { get; set; }
        public string BackflushEmpID { get; set; }
        public bool SubContract { get; set; }
        public bool AutoMove { get; set; }
        public bool UseEstimates { get; set; }
        public decimal DailyProdQty { get; set; }
        public decimal BillLaborRate { get; set; }
        public decimal DailyProdRate { get; set; }
        public bool Location { get; set; }
        public bool DistributeLoad { get; set; }
        public bool TrkProdAct { get; set; }
        public bool SetShopLoad { get; set; }
        public decimal TAKTValue { get; set; }
        public bool UseCalendarForMove { get; set; }
        public bool UseCalendarForQueue { get; set; }
        public string URL { get; set; }
        public string JDFDevice { get; set; }
        public string JDFOperation { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public bool ExternalMES { get; set; }
        public bool MESQueue { get; set; }
        public string Character01 { get; set; }
        public Nullable<System.Guid> ForeignSysRowID { get; set; }
        public byte[] UD_SysRevID { get; set; }
    }
}
