//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnMiscelleneousRequestTbl
    {
        public int id { get; set; }
        public int Group_id { get; set; }
        public int Line_id { get; set; }
        public string Request_no { get; set; }
        public string user_id { get; set; }
        public string initiator_id { get; set; }
        public string initiator_name { get; set; }
        public string department_name { get; set; }
        public Nullable<System.DateTime> return_req_date { get; set; }
        public string return_part_no { get; set; }
        public string return_part_desc { get; set; }
        public string where_use_part_no { get; set; }
        public Nullable<double> return_request_qty { get; set; }
        public string return_refference { get; set; }
        public string return_lotno { get; set; }
        public string return_reason { get; set; }
        public Nullable<System.DateTime> return_timestamp { get; set; }
        public string return_id { get; set; }
        public string uom { get; set; }
        public string purpose { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public string status { get; set; }
        public Nullable<double> returned_qty { get; set; }
        public string return_remark { get; set; }
        public string return_purpose { get; set; }
        public Nullable<bool> is_return { get; set; }
        public Nullable<bool> is_final { get; set; }
        public string void_resoan { get; set; }
    }
}
