//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTBD
    {
        public string Company { get; set; }
        public string TerritoryID { get; set; }
        public int CountryNum { get; set; }
        public string CountryName { get; set; }
        public string State { get; set; }
        public string StartZip { get; set; }
        public string EndZip { get; set; }
        public bool GlobalSalesTBD { get; set; }
        public bool GlobalLock { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public Nullable<System.Guid> ForeignSysRowID { get; set; }
        public byte[] UD_SysRevID { get; set; }
        public string SalesRep_c { get; set; }
    }
}
