//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipDtl
    {
        public string Company { get; set; }
        public int PackNum { get; set; }
        public int PackLine { get; set; }
        public int OrderNum { get; set; }
        public int OrderLine { get; set; }
        public int OrderRelNum { get; set; }
        public string LineType { get; set; }
        public decimal OurInventoryShipQty { get; set; }
        public decimal OurJobShipQty { get; set; }
        public string JobNum { get; set; }
        public int Packages { get; set; }
        public string PartNum { get; set; }
        public string LineDesc { get; set; }
        public string IUM { get; set; }
        public string RevisionNum { get; set; }
        public string ShipComment { get; set; }
        public bool ShipCmpl { get; set; }
        public string WarehouseCode { get; set; }
        public string BinNum { get; set; }
        public bool UpdatedInventory { get; set; }
        public string XPartNum { get; set; }
        public string XRevisionNum { get; set; }
        public int ShpConNum { get; set; }
        public bool TMBilling { get; set; }
        public bool Invoiced { get; set; }
        public string WUM { get; set; }
        public string LotNum { get; set; }
        public string DimCode { get; set; }
        public string DUM { get; set; }
        public decimal DimConvFactor { get; set; }
        public string InvoiceComment { get; set; }
        public string WarrantyCode { get; set; }
        public int CustNum { get; set; }
        public string ShipToNum { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public int MaterialDuration { get; set; }
        public int LaborDuration { get; set; }
        public int MiscDuration { get; set; }
        public string MaterialMod { get; set; }
        public string LaborMod { get; set; }
        public string MiscMod { get; set; }
        public Nullable<System.DateTime> MaterialExpiration { get; set; }
        public Nullable<System.DateTime> LaborExpiration { get; set; }
        public Nullable<System.DateTime> MiscExpiration { get; set; }
        public Nullable<System.DateTime> LastExpiration { get; set; }
        public string WarrantyComment { get; set; }
        public int ContractNum { get; set; }
        public string ContractCode { get; set; }
        public bool Onsite { get; set; }
        public bool MatCovered { get; set; }
        public bool LabCovered { get; set; }
        public bool MiscCovered { get; set; }
        public string Plant { get; set; }
        public bool ReadyToInvoice { get; set; }
        public decimal SellingInventoryShipQty { get; set; }
        public decimal SellingJobShipQty { get; set; }
        public decimal SellingFactor { get; set; }
        public string SalesUM { get; set; }
        public decimal TotalNetWeight { get; set; }
        public string WIPWarehouseCode { get; set; }
        public string WIPBinNum { get; set; }
        public string SellingFactorDirection { get; set; }
        public string HeaderShipComment { get; set; }
        public int KitParentLine { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public int ChangeTime { get; set; }
        public string InventoryShipUOM { get; set; }
        public string JobShipUOM { get; set; }
        public bool TrackSerialNum { get; set; }
        public string JobLotNum { get; set; }
        public string BinType { get; set; }
        public bool NotCompliant { get; set; }
        public string ComplianceMsg { get; set; }
        public decimal DiscountPercent { get; set; }
        public string PricePerCode { get; set; }
        public decimal Discount { get; set; }
        public decimal DocDiscount { get; set; }
        public decimal Rpt1Discount { get; set; }
        public decimal Rpt2Discount { get; set; }
        public decimal Rpt3Discount { get; set; }
        public decimal ExtPrice { get; set; }
        public decimal DocExtPrice { get; set; }
        public decimal Rpt1ExtPrice { get; set; }
        public decimal Rpt2ExtPrice { get; set; }
        public decimal Rpt3ExtPrice { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal DocUnitPrice { get; set; }
        public decimal Rpt1UnitPrice { get; set; }
        public decimal Rpt2UnitPrice { get; set; }
        public decimal Rpt3UnitPrice { get; set; }
        public decimal PickedAutoAllocatedQty { get; set; }
        public int ShipToCustNum { get; set; }
        public decimal InDiscount { get; set; }
        public decimal DocInDiscount { get; set; }
        public decimal Rpt1InDiscount { get; set; }
        public decimal Rpt2InDiscount { get; set; }
        public decimal Rpt3InDiscount { get; set; }
        public decimal InExtPrice { get; set; }
        public decimal DocInExtPrice { get; set; }
        public decimal Rpt1InExtPrice { get; set; }
        public decimal Rpt2InExtPrice { get; set; }
        public decimal Rpt3InExtPrice { get; set; }
        public decimal InUnitPrice { get; set; }
        public decimal DocInUnitPrice { get; set; }
        public decimal Rpt1InUnitPrice { get; set; }
        public decimal Rpt2InUnitPrice { get; set; }
        public decimal Rpt3InUnitPrice { get; set; }
        public bool InPrice { get; set; }
        public int Obs10_PkgNum { get; set; }
        public int Obs10_PkgLine { get; set; }
        public int MFCustNum { get; set; }
        public string MFShipToNum { get; set; }
        public bool UseOTMF { get; set; }
        public string OTMFName { get; set; }
        public string OTMFAddress1 { get; set; }
        public string OTMFAddress2 { get; set; }
        public string OTMFAddress3 { get; set; }
        public string OTMFCity { get; set; }
        public string OTMFState { get; set; }
        public string OTMFZIP { get; set; }
        public string OTMFContact { get; set; }
        public string OTMFFaxNum { get; set; }
        public string OTMFPhoneNum { get; set; }
        public int OTMFCountryNum { get; set; }
        public int RenewalNbr { get; set; }
        public bool ShipOvers { get; set; }
        public decimal AllowedOvers { get; set; }
        public decimal AllowedUnders { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public decimal NotAllocatedQty { get; set; }
        public string PCID { get; set; }
        public long PCIDItemSeq { get; set; }
        public int PCIDParentLine { get; set; }
        public string DockingStation { get; set; }
        public bool UseShipDtlInfo { get; set; }
        public string PkgCodePartNum { get; set; }
        public string CustContainerPartNum { get; set; }
        public string LabelType { get; set; }
        public bool WarrantySendToFSA { get; set; }
        public bool FSAEquipment { get; set; }
    }
}
