//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipTo
    {
        public string Company { get; set; }
        public int CustNum { get; set; }
        public string ShipToNum { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP { get; set; }
        public string Country { get; set; }
        public string ResaleID { get; set; }
        public string SalesRepCode { get; set; }
        public string TerritoryID { get; set; }
        public string ShipViaCode { get; set; }
        public int PrimSCon { get; set; }
        public string FaxNum { get; set; }
        public string PhoneNum { get; set; }
        public string TaxExempt { get; set; }
        public string EDIShipNum { get; set; }
        public int CountryNum { get; set; }
        public string LangNameID { get; set; }
        public string BorderCrossing { get; set; }
        public string FormatStr { get; set; }
        public string TaxRegionCode { get; set; }
        public string EMailAddress { get; set; }
        public string TerritorySelect { get; set; }
        public string PendingTerritoryID { get; set; }
        public bool CreatedByEDI { get; set; }
        public string ExternalID { get; set; }
        public string TaxAuthorityCode { get; set; }
        public bool GlobalLock { get; set; }
        public string EDICode { get; set; }
        public int DemandDeliveryDays { get; set; }
        public string DemandDateType { get; set; }
        public int DemandAddLeadTime { get; set; }
        public string DemandAddAction { get; set; }
        public int DemandChangeLeadTime { get; set; }
        public string DemandChangeAction { get; set; }
        public int DemandCancelLeadTime { get; set; }
        public string DemandCancelAction { get; set; }
        public int DemandNewLineLeadTime { get; set; }
        public string DemandNewLineAction { get; set; }
        public int DemandQtyChangeLeadTime { get; set; }
        public string DemandQtyChangeAction { get; set; }
        public int DemandChangeDateLeadTime { get; set; }
        public string DemandChangeDateAction { get; set; }
        public string TradingPartnerName { get; set; }
        public bool ResDelivery { get; set; }
        public bool SatDelivery { get; set; }
        public bool SatPickup { get; set; }
        public bool Hazmat { get; set; }
        public bool DocOnly { get; set; }
        public string RefNotes { get; set; }
        public bool ApplyChrg { get; set; }
        public decimal ChrgAmount { get; set; }
        public bool COD { get; set; }
        public bool CODFreight { get; set; }
        public bool CODCheck { get; set; }
        public decimal CODAmount { get; set; }
        public string GroundType { get; set; }
        public bool NotifyFlag { get; set; }
        public string NotifyEMail { get; set; }
        public bool DeclaredIns { get; set; }
        public decimal DeclaredAmt { get; set; }
        public int PeriodicityCode { get; set; }
        public bool ServSignature { get; set; }
        public bool ServAlert { get; set; }
        public bool ServHomeDel { get; set; }
        public string DeliveryType { get; set; }
        public Nullable<System.DateTime> ServDeliveryDate { get; set; }
        public string ServPhone { get; set; }
        public string ServInstruct { get; set; }
        public bool ServRelease { get; set; }
        public string ServAuthNum { get; set; }
        public string ServRef1 { get; set; }
        public bool CommercialInvoice { get; set; }
        public string ServRef2 { get; set; }
        public bool ShipExprtDeclartn { get; set; }
        public string ServRef3 { get; set; }
        public bool CertOfOrigin { get; set; }
        public string ServRef4 { get; set; }
        public bool LetterOfInstr { get; set; }
        public string ServRef5 { get; set; }
        public bool HazardousShipment { get; set; }
        public bool OverrideCarrier { get; set; }
        public bool IntrntlShip { get; set; }
        public bool OverrideService { get; set; }
        public bool DemandUseCustomerValues { get; set; }
        public string TaxRegReason { get; set; }
        public int EarlyBuffer { get; set; }
        public string OrgRegCode { get; set; }
        public int LateBuffer { get; set; }
        public bool DemandUnitPriceDiff { get; set; }
        public string DemandUnitPriceDiffAction { get; set; }
        public bool ExcFromVal { get; set; }
        public bool AddressVal { get; set; }
        public bool DemandCheckForPart { get; set; }
        public string DemandCheckForPartAction { get; set; }
        public string FFID { get; set; }
        public string FFAddress1 { get; set; }
        public string FFAddress2 { get; set; }
        public string FFCity { get; set; }
        public string FFState { get; set; }
        public string FFZip { get; set; }
        public string FFCountry { get; set; }
        public string FFContact { get; set; }
        public string FFCompName { get; set; }
        public string FFPhoneNum { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public int ChangeTime { get; set; }
        public bool IndividualPackIDs { get; set; }
        public int FFCountryNum { get; set; }
        public bool NonStdPkg { get; set; }
        public int DeliveryConf { get; set; }
        public bool AddlHdlgFlag { get; set; }
        public bool UPSQuantumView { get; set; }
        public string UPSQVShipFromName { get; set; }
        public string UPSQVMemo { get; set; }
        public string FFAddress3 { get; set; }
        public bool ETCAddrChg { get; set; }
        public bool IsAlternate { get; set; }
        public int MasterCustNum { get; set; }
        public string MasterShipToNum { get; set; }
        public bool DemandCheckForRev { get; set; }
        public string DemandCheckForRevAction { get; set; }
        public bool DemandCheckPartialShip { get; set; }
        public string DemandCheckShipAction { get; set; }
        public bool DemandCloseRejSkd { get; set; }
        public string DemandPricing { get; set; }
        public decimal PriceTolerance { get; set; }
        public bool CheckDateCapPromise { get; set; }
        public bool CheckConfirmCapPromise { get; set; }
        public bool CheckUpdateCapPromise { get; set; }
        public string DemandCapPromiseDate { get; set; }
        public string DemandCapPromiseAction { get; set; }
        public string DemandCapPromiseUpdate { get; set; }
        public bool OTSmartString { get; set; }
        public string LegalName { get; set; }
        public bool DemandCheckConfig { get; set; }
        public string DemandCheckCfgAction { get; set; }
        public bool WIWebShipTo { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public string AGApartment { get; set; }
        public string AGExtraStreetNumber { get; set; }
        public string AGFloor { get; set; }
        public string AGGrossIncomeTaxID { get; set; }
        public string AGLocationCode { get; set; }
        public string AGNeighborhood { get; set; }
        public string AGProvinceCode { get; set; }
        public string AGStreet { get; set; }
        public string AGStreetNumber { get; set; }
        public string EntityUseCode { get; set; }
        public bool DemandCheckForRunOutPart { get; set; }
        public string DemandCheckForRunOutPartAction { get; set; }
        public string INExciseRegNumber { get; set; }
        public string INVATNumber { get; set; }
        public string INSTRegistration { get; set; }
        public string MXCURP { get; set; }
        public string MXMunicipio { get; set; }
        public string MXFederalID { get; set; }
        public string INTaxRegistrationID { get; set; }
        public string PEUBIGEOCode { get; set; }
        public string ShortChar10 { get; set; }
        public Nullable<System.Guid> ForeignSysRowID { get; set; }
        public byte[] UD_SysRevID { get; set; }
    }
}
