//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sholder_Implant_Database
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string Sholder_ID { get; set; }
        public string Implant_name { get; set; }
        public string Manufacturer { get; set; }
        public string Anatomy_Reverse { get; set; }
        public Nullable<bool> Collar { get; set; }
        public Nullable<bool> Proximal_Notched_Lip { get; set; }
        public Nullable<bool> Trunnion { get; set; }
        public Nullable<bool> Threads { get; set; }
        public Nullable<bool> Inner_Lip { get; set; }
        public string Stem_Trunnion_Angle { get; set; }
        public Nullable<bool> Fins { get; set; }
        public Nullable<bool> Unthreaded_Proximal_Hole { get; set; }
        public string Stem { get; set; }
        public string Humeral_Heads { get; set; }
        public string Glenoid_Glenosphere { get; set; }
        public string Liners { get; set; }
        public string Other { get; set; }
        public string Stem_Extraction_Technique_A_Tools { get; set; }
        public string Stem_Extraction_Technique_A_Steps { get; set; }
        public string Stem_Extraction_Technique_B_Tools { get; set; }
        public string Stem_Extraction_Technique_B_Steps { get; set; }
        public string Stem_Extraction_Technique_C_Tools { get; set; }
        public string Stem_Extraction_Technique_C_Steps { get; set; }
        public string Stem_Extraction_Technique_D_Tools { get; set; }
        public string Stem_Extraction_Technique_D_Steps { get; set; }
        public string Steps_Extraction_Technique_E_Tools { get; set; }
        public string Steps_Extraction_Technique_E_Steps { get; set; }
        public string Link { get; set; }
        public string Notes { get; set; }
        public string Trinnion_new { get; set; }
        public string implant_img { get; set; }
        public Nullable<bool> Approved_by_Admin { get; set; }
        public string status { get; set; }
        public Nullable<bool> stem_angle { get; set; }
        public Nullable<System.DateTime> Approval_Date { get; set; }
        public string Approved_By { get; set; }
        public string Upload_By { get; set; }
        public Nullable<System.DateTime> Upload_Date { get; set; }
        public string Denied_by { get; set; }
        public Nullable<System.DateTime> Denied_date { get; set; }
        public string Denied_Reason { get; set; }
    }
}
