//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shoulder_Implant_Database_New
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string Shoulder_ID { get; set; }
        public string Implant_Name { get; set; }
        public string Manufacturer { get; set; }
        public string Anatomic_Reverse { get; set; }
        public Nullable<bool> Collar { get; set; }
        public Nullable<bool> Proximal_Falsetched_Lip { get; set; }
        public string Trunnion { get; set; }
        public Nullable<bool> Threads { get; set; }
        public Nullable<bool> Inner_Lip { get; set; }
        public string Stem_Trunnion_Angle { get; set; }
        public Nullable<bool> Fins { get; set; }
        public Nullable<bool> Unthreaded_proximal_hole { get; set; }
        public string Stem { get; set; }
        public string Huneral_Heads { get; set; }
        public string Glenoid_Glenosphere { get; set; }
        public string Liners { get; set; }
        public string Other { get; set; }
        public string Stem_Extraction_Technique_A_Tools { get; set; }
        public string Stem_Extraction_Technique_A_Steps { get; set; }
        public string Stem_Extraction_Technique_B_Tools { get; set; }
        public string Stem_Extraction_Technique_B_Steps { get; set; }
        public string Stem_Extraction_Technique_C_Tools { get; set; }
        public string Stem_Extraction_Technique_C_Steps { get; set; }
        public string Stem_Extraction_Technique_D_Tools { get; set; }
        public string Stem_Extraction_Technique_D_Steps { get; set; }
        public string Stem_Extraction_Technique_E_Tools { get; set; }
        public string Stem_Extraction_Technique_E_Steps { get; set; }
        public string Link { get; set; }
        public string Notes { get; set; }
    }
}
