//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shoulder_Implant_Master
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public int Refid { get; set; }
        public string Ref_Type { get; set; }
        public string Rer_Sub_Type { get; set; }
        public string Manufacturer_Name { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
