//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSW_Appliances_Main
    {
        public int ID { get; set; }
        public int PID { get; set; }
        public int MID { get; set; }
        public int SID { get; set; }
        public string Type_of_appliance { get; set; }
        public string Appliance_Type { get; set; }
        public string Appliance_Sub_Type { get; set; }
        public string Appliance_Name { get; set; }
        public string Appliance_Number { get; set; }
        public string Active { get; set; }
        public string Location { get; set; }
        public string IP { get; set; }
        public string other_detail { get; set; }
        public string mount_stand { get; set; }
        public string Window_Version { get; set; }
        public string PC_Configuration { get; set; }
        public string Keyboard_Mouse { get; set; }
        public string MAC_Address { get; set; }
        public string Item_image { get; set; }
    }
}
