//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_master
    {
        public int id { get; set; }
        public string auto_supp_id { get; set; }
        public string manual_supp_id { get; set; }
        public string supp_name { get; set; }
        public string item_supplied { get; set; }
        public string add_one { get; set; }
        public string add_two { get; set; }
        public string add_three { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postal_code { get; set; }
        public string country { get; set; }
        public string phone { get; set; }
        public string email_id { get; set; }
        public string group_id { get; set; }
        public string tax_id { get; set; }
        public string pan_no { get; set; }
        public string gst_id { get; set; }
        public Nullable<byte> is_deleted { get; set; }
        public string insert_time { get; set; }
        public string added_by { get; set; }
    }
}
