//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Data_new
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public string SID { get; set; }
        public string Supp_Name { get; set; }
        public string Supp_Add { get; set; }
        public string Supp_mob { get; set; }
        public string Supp_email { get; set; }
        public string Supp_gst { get; set; }
    }
}
