//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_generation_Process
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string Ticket_ID { get; set; }
        public string Ticket_Generator_Name { get; set; }
        public string Email_ID { get; set; }
        public string from_department { get; set; }
        public string to_department { get; set; }
        public string Requestregarding { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Need_Application { get; set; }
        public string Application_name { get; set; }
        public string Applicaiton_scope { get; set; }
        public string Application_purpose { get; set; }
        public string Resposible_user { get; set; }
        public string How_It_Works { get; set; }
        public Nullable<System.DateTime> Upload_date { get; set; }
        public Nullable<System.DateTime> deadline_date { get; set; }
        public string Server_Requirement { get; set; }
        public string attachment { get; set; }
        public string status { get; set; }
        public string What_are_you_using_now { get; set; }
        public string Application_Type { get; set; }
        public string Which_department_monitoring { get; set; }
        public string Database_importance { get; set; }
        public string Responsible_Department { get; set; }
        public string Application_Liability { get; set; }
        public Nullable<System.DateTime> Mock_due_date { get; set; }
        public Nullable<System.DateTime> Final_date { get; set; }
        public string retention_data { get; set; }
        public Nullable<bool> approval { get; set; }
        public Nullable<int> user_ID { get; set; }
        public Nullable<System.DateTime> approval_date { get; set; }
        public string type_of_ticket { get; set; }
        public string remark_completion { get; set; }
        public string remark_cancel { get; set; }
        public Nullable<System.DateTime> completion_date { get; set; }
        public Nullable<System.DateTime> cancel_date { get; set; }
        public string Approval_remark { get; set; }
        public string IT_Close_remark { get; set; }
        public string User_Close_remark { get; set; }
        public Nullable<System.DateTime> IT_Close_date { get; set; }
        public Nullable<System.DateTime> User_Close_date { get; set; }
    }
}
