//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_generated_department_applicable
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string TicketID { get; set; }
        public string applicable_department { get; set; }
    }
}
