//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_generation_application_revision_detail
    {
        public int ID { get; set; }
        public int PID { get; set; }
        public int MID { get; set; }
        public string Ticket_no { get; set; }
        public string Revision_type { get; set; }
        public string version_no { get; set; }
        public string Release_notes { get; set; }
        public string Link { get; set; }
        public string status { get; set; }
        public string department { get; set; }
        public Nullable<int> vesrion_no_gen { get; set; }
        public Nullable<int> version_no_two { get; set; }
        public Nullable<System.DateTime> Release_date { get; set; }
        public Nullable<System.DateTime> Deny_date { get; set; }
    }
}
