//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tooling_Utilization_details
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public string Tool_Type { get; set; }
        public string Tool_Name { get; set; }
        public Nullable<int> Order_Qty { get; set; }
        public Nullable<int> Qty_Move { get; set; }
        public string Transaction_Type { get; set; }
        public Nullable<System.DateTime> Transaction_date { get; set; }
        public string transaction_by { get; set; }
        public string Machine_Type { get; set; }
        public string status { get; set; }
        public Nullable<int> used_qty { get; set; }
        public Nullable<int> unused_qty { get; set; }
        public string job_no { get; set; }
        public string part_no { get; set; }
        public string rev { get; set; }
    }
}
