//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tool_Inventory_System
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public int Tool_ID { get; set; }
        public string Part_name { get; set; }
        public string Part_Dscription { get; set; }
        public string Tool_Type { get; set; }
        public string Product_Class { get; set; }
        public string Product_group { get; set; }
        public string UOM { get; set; }
        public Nullable<int> Qty_as_per_physical_stock { get; set; }
        public Nullable<int> min_qty { get; set; }
        public Nullable<int> item_qty_in_box { get; set; }
        public string active { get; set; }
        public string Remark { get; set; }
    }
}
