//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UDAI_UDIMaster
    {
        public int Id { get; set; }
        public int GroupID { get; set; }
        public int LineID { get; set; }
        public string PartNo { get; set; }
        public string SuggestedJobNo { get; set; }
        public string JobNo { get; set; }
        public int RevisionNo { get; set; }
        public string UdiRemark { get; set; }
        public System.DateTime RequestDate { get; set; }
        public Nullable<bool> UDIDrawingRequired { get; set; }
        public string Status { get; set; }
        public Nullable<int> JobConfirmBy { get; set; }
        public string DenyReson { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int userId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> PlanningTimestamp { get; set; }
        public Nullable<System.DateTime> UDIGenerationTimestamp { get; set; }
        public Nullable<int> UDIGeneratedBy { get; set; }
        public string UDIString { get; set; }
        public string UdiMatrixFilePath { get; set; }
        public string UdiMatrixQr { get; set; }
        public string UdiMatrixBarcode { get; set; }
        public Nullable<bool> ApprovedDgAvail { get; set; }
        public string ApproveDgAvailFilePath { get; set; }
        public Nullable<System.DateTime> EngProcessTimestamp { get; set; }
        public Nullable<int> EngProcessBy { get; set; }
        public Nullable<System.DateTime> CloseTimestamp { get; set; }
        public Nullable<int> ClosedBy { get; set; }
        public string QualityDoc { get; set; }
        public Nullable<bool> IsFinal { get; set; }
    }
}
