//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Mst_For_Shoulder
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string Username { get; set; }
        public string password { get; set; }
        public string confirm_password { get; set; }
        public string Role { get; set; }
        public string Organization { get; set; }
        public string email { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string mobile_number { get; set; }
        public Nullable<bool> approved_by_admin { get; set; }
        public string status { get; set; }
        public Nullable<bool> admin_rights { get; set; }
    }
}
