//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class video_table
    {
        public int MID { get; set; }
        public int VID { get; set; }
        public int ID { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public string url { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
