//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_invoice_with_supplier
    {
        public string s_id { get; set; }
        public string slip_no { get; set; }
        public Nullable<int> invoice_mounth { get; set; }
        public Nullable<int> invoice_year { get; set; }
        public string supplier_id { get; set; }
        public string invoice_no { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public string supp_name { get; set; }
        public Nullable<double> total_cost { get; set; }
        public int id { get; set; }
        public Nullable<double> delivery_rating { get; set; }
        public Nullable<double> average_rating { get; set; }
        public string over_all_rating { get; set; }
        public Nullable<double> quality_rating { get; set; }
        public string department { get; set; }
        public bool is_deleted { get; set; }
    }
}
