//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewActiveLaborDetail
    {
        public string EmployeeNum { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public string LaborType { get; set; }
        public string JobNum { get; set; }
        public int OprSeq { get; set; }
        public string OpCode { get; set; }
        public decimal EstSetHours { get; set; }
        public decimal EstProdHours { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public decimal StartHour { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public decimal DueHour { get; set; }
        public int Machines { get; set; }
        public bool ProdComplete { get; set; }
        public bool SetupComplete { get; set; }
        public decimal ActProdHours { get; set; }
        public decimal ActProdRwkHours { get; set; }
        public decimal ActSetupHours { get; set; }
        public decimal ActSetupRwkHours { get; set; }
        public decimal QtyCompleted { get; set; }
        public string PartNum { get; set; }
        public decimal RunQty { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
        public decimal LoadHour { get; set; }
        public decimal HoursPerMachine { get; set; }
        public string JCDept { get; set; }
        public bool Complete { get; set; }
        public Nullable<System.DateTime> ClockInDate { get; set; }
        public decimal ClockinTime { get; set; }
        public bool ActiveTrans { get; set; }
        public string IndirectCode { get; set; }
        public int SetupPctComplete { get; set; }
        public string DspClockInTime { get; set; }
        public string DspClockOutTime { get; set; }
        public string EmpStatus { get; set; }
    }
}
