//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int id { get; set; }
        public string slip_no { get; set; }
        public Nullable<int> line_no { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public Nullable<System.DateTime> inward_date { get; set; }
        public Nullable<System.DateTime> promise_date { get; set; }
        public Nullable<int> po_no { get; set; }
        public Nullable<int> po_line { get; set; }
        public string supplier_id { get; set; }
        public string consumable_non_consumable { get; set; }
        public string invoice_no { get; set; }
        public string challan_no { get; set; }
        public string requistion_no { get; set; }
        public string department { get; set; }
        public string item_group { get; set; }
        public string category { get; set; }
        public string item_name { get; set; }
        public string hsn { get; set; }
        public string uom { get; set; }
        public Nullable<double> po_qty { get; set; }
        public Nullable<double> received_qty { get; set; }
        public Nullable<double> unit_price { get; set; }
        public Nullable<double> gst_persentage { get; set; }
        public Nullable<double> transportation_charges { get; set; }
        public Nullable<double> frieght_charges { get; set; }
        public Nullable<double> packaging_charges { get; set; }
        public Nullable<double> accepted_qty { get; set; }
        public Nullable<double> u_d_accepted_qty { get; set; }
        public Nullable<int> ltb { get; set; }
        public Nullable<double> rej_at_suppliers_end { get; set; }
        public Nullable<double> cd { get; set; }
        public Nullable<double> cost { get; set; }
        public Nullable<double> gst_amount { get; set; }
        public Nullable<double> total_cost { get; set; }
        public Nullable<double> quality_rating { get; set; }
        public Nullable<int> delay_in_days { get; set; }
        public Nullable<double> delivery_rating { get; set; }
        public Nullable<double> average_rating { get; set; }
        public string over_all_rating { get; set; }
        public bool is_deleted { get; set; }
        public Nullable<System.DateTime> insert_time { get; set; }
        public string added_by { get; set; }
        public Nullable<int> formula_id { get; set; }
        public string remark { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<int> MID { get; set; }
        public string Expr2 { get; set; }
        public string Supp_name { get; set; }
        public string Supp_add1 { get; set; }
        public string Supp_add2 { get; set; }
        public string Supp_add3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string postal_code { get; set; }
        public string country { get; set; }
        public string phone { get; set; }
        public string email_id { get; set; }
        public string GSTIN { get; set; }
        public string Register_Type { get; set; }
    }
}
