//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMS_Monthly_Data
    {
        public int ID { get; set; }
        public string Month { get; set; }
        public string year { get; set; }
        public string Person_ID { get; set; }
        public string Person_Name { get; set; }
        public string one_in { get; set; }
        public string one_out { get; set; }
        public string one_status { get; set; }
        public string two_in { get; set; }
        public string two_out { get; set; }
        public string two_status { get; set; }
        public string three_in { get; set; }
        public string three_out { get; set; }
        public string three_status { get; set; }
        public string four_in { get; set; }
        public string four_out { get; set; }
        public string four_status { get; set; }
        public string five_in { get; set; }
        public string five_out { get; set; }
        public string five_status { get; set; }
        public string six_in { get; set; }
        public string six_out { get; set; }
        public string six_status { get; set; }
        public string seven_in { get; set; }
        public string seven_out { get; set; }
        public string seven_status { get; set; }
        public string eight_in { get; set; }
        public string eight_out { get; set; }
        public string eight_status { get; set; }
        public string nine_in { get; set; }
        public string nine_out { get; set; }
        public string nine_status { get; set; }
        public string ten_in { get; set; }
        public string ten_out { get; set; }
        public string ten_status { get; set; }
        public string eleven_in { get; set; }
        public string eleven_out { get; set; }
        public string eleven_status { get; set; }
        public string twelve_in { get; set; }
        public string twelve_out { get; set; }
        public string twelve_status { get; set; }
        public string thirteen_in { get; set; }
        public string thirteen_out { get; set; }
        public string thirteen_status { get; set; }
        public string fourteen_in { get; set; }
        public string fourteen_out { get; set; }
        public string fourteen_status { get; set; }
        public string fifteen_in { get; set; }
        public string fifteen_out { get; set; }
        public string fifteen_status { get; set; }
        public string sixteen_in { get; set; }
        public string sixteen_out { get; set; }
        public string sixteen_status { get; set; }
        public string seventeen_in { get; set; }
        public string seventeen_out { get; set; }
        public string seventeen_status { get; set; }
        public string eighteen_in { get; set; }
        public string eighteen_out { get; set; }
        public string eighteen_status { get; set; }
        public string nineteen_in { get; set; }
        public string nineteen_out { get; set; }
        public string nineteen_status { get; set; }
        public string twenty_in { get; set; }
        public string twenty_out { get; set; }
        public string twenty_status { get; set; }
        public string twenty_one_in { get; set; }
        public string twenty_one_out { get; set; }
        public string twenty_one_status { get; set; }
        public string twenty_two_in { get; set; }
        public string twenty_two_out { get; set; }
        public string twenty_two_status { get; set; }
        public string twenty_three_in { get; set; }
        public string twenty_three_out { get; set; }
        public string twenty_three_status { get; set; }
        public string twenty_four_in { get; set; }
        public string twenty_four_out { get; set; }
        public string twenty_four_status { get; set; }
        public string twenty_five_in { get; set; }
        public string twenty_five_out { get; set; }
        public string twenty_five_status { get; set; }
        public string twenty_six_in { get; set; }
        public string twenty_six_out { get; set; }
        public string twenty_six_status { get; set; }
        public string twenty_seven_in { get; set; }
        public string twenty_seven_out { get; set; }
        public string twenty_seven_status { get; set; }
        public string twenty_eight_in { get; set; }
        public string twenty_eight_out { get; set; }
        public string twenty_eight_status { get; set; }
        public string twenty_nine_in { get; set; }
        public string twenty_nine_out { get; set; }
        public string twenty_nine_status { get; set; }
        public string thirty_in { get; set; }
        public string thirty_out { get; set; }
        public string thirty_status { get; set; }
        public string thirty_one_in { get; set; }
        public string thirty_one_out { get; set; }
        public string thirty_one_status { get; set; }
        public Nullable<int> PID { get; set; }
        public string shift { get; set; }
        public string Organization { get; set; }
        public string In_01 { get; set; }
        public string Out_01 { get; set; }
        public string Status_01 { get; set; }
        public string In_02 { get; set; }
        public string Out_02 { get; set; }
        public string Status_02 { get; set; }
        public string In_03 { get; set; }
        public string Out_03 { get; set; }
        public string Status_03 { get; set; }
    }
}
