//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSAttendanceShiftchangedata_History
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string Person_ID { get; set; }
        public string Person_Name { get; set; }
        public string Organization { get; set; }
        public string Shift { get; set; }
        public string Off_day { get; set; }
        public Nullable<System.DateTime> Upload_date { get; set; }
        public string Month { get; set; }
        public string History { get; set; }
        public string year { get; set; }
        public string Contractor { get; set; }
    }
}
