//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Working_Sampling_Time
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string Machine_name { get; set; }
        public Nullable<System.DateTime> Machine_Record_Date { get; set; }
        public Nullable<System.TimeSpan> machine_Record_Time { get; set; }
        public string t_machine { get; set; }
    }
}
