//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookDtl
    {
        public string Company { get; set; }
        public int OrderNum { get; set; }
        public int OrderLine { get; set; }
        public Nullable<System.DateTime> BookDate { get; set; }
        public int BookTime { get; set; }
        public string RecType { get; set; }
        public int TranNum { get; set; }
        public string BookType { get; set; }
        public decimal OurBookQty { get; set; }
        public string ProdCode { get; set; }
        public decimal BookValue { get; set; }
        public string DCDUserID { get; set; }
        public decimal SellingBookQty { get; set; }
        public string IUM { get; set; }
        public string SalesUM { get; set; }
        public decimal SellingFactor { get; set; }
        public string SellingFactorDirection { get; set; }
    }
}
