//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckHed
    {
        public string Company { get; set; }
        public bool Posted { get; set; }
        public string GroupID { get; set; }
        public int HeadNum { get; set; }
        public string BankAcctID { get; set; }
        public int CheckNum { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public int FiscalYear { get; set; }
        public int FiscalPeriod { get; set; }
        public bool Voided { get; set; }
        public string CheckSrc { get; set; }
        public bool ClearedCheck { get; set; }
        public bool ClearedPending { get; set; }
        public decimal ClearedAmt { get; set; }
        public decimal DocClearedAmt { get; set; }
        public string ClearedPerson { get; set; }
        public Nullable<System.DateTime> ClearedDate { get; set; }
        public string ClearedTime { get; set; }
        public Nullable<System.DateTime> ClearedStmtEndDate { get; set; }
        public string EmployeeNum { get; set; }
        public decimal CheckAmt { get; set; }
        public decimal DocCheckAmt { get; set; }
        public bool ManualPrint { get; set; }
        public string EntryPerson { get; set; }
        public int VendorNum { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP { get; set; }
        public string Country { get; set; }
        public string CurrencyCode { get; set; }
        public decimal ExchangeRate { get; set; }
        public int CountryNum { get; set; }
        public string BankSlip { get; set; }
        public bool ElecPayment { get; set; }
        public string VendorBankID { get; set; }
        public string VendorBankName { get; set; }
        public string VendorBankNameOnAccount { get; set; }
        public string VendorBankAddress1 { get; set; }
        public string VendorBankAddress2 { get; set; }
        public string VendorBankAddress3 { get; set; }
        public string VendorBankCity { get; set; }
        public string VendorBankState { get; set; }
        public string VendorBankPostalCode { get; set; }
        public int VendorBankCountryNum { get; set; }
        public string VendorBankAcctNumber { get; set; }
        public string VendorBankSwiftNum { get; set; }
        public decimal CashBookNum { get; set; }
        public int CashbookLine { get; set; }
        public string XRefCheckNum { get; set; }
        public decimal Rpt1CheckAmt { get; set; }
        public decimal Rpt2CheckAmt { get; set; }
        public decimal Rpt3CheckAmt { get; set; }
        public decimal Rpt1ClearedAmt { get; set; }
        public decimal Rpt2ClearedAmt { get; set; }
        public decimal Rpt3ClearedAmt { get; set; }
        public string RateGrpCode { get; set; }
        public string FiscalYearSuffix { get; set; }
        public string FiscalCalendarID { get; set; }
        public decimal PaymentTotal { get; set; }
        public decimal DocPaymentTotal { get; set; }
        public decimal Rpt1PaymentTotal { get; set; }
        public decimal Rpt2PaymentTotal { get; set; }
        public decimal Rpt3PaymentTotal { get; set; }
        public decimal Variance { get; set; }
        public decimal DocVariance { get; set; }
        public decimal Rpt1Variance { get; set; }
        public decimal Rpt2Variance { get; set; }
        public decimal Rpt3Variance { get; set; }
        public decimal PaymentBankRate { get; set; }
        public decimal BankTotalAmt { get; set; }
        public bool IsEnterTotal { get; set; }
        public int LockRate { get; set; }
        public bool ReadyToCalc { get; set; }
        public bool RecalcBeforePost { get; set; }
        public bool UsePendAcct { get; set; }
        public bool ForceDiscount { get; set; }
        public int FirstHeadNum { get; set; }
        public bool ApplyingPayment { get; set; }
        public string Plant { get; set; }
        public string InvoiceNum { get; set; }
        public int PMUID { get; set; }
        public string PCashDeskID { get; set; }
        public string BankTranID { get; set; }
        public int PCashRefNum { get; set; }
        public decimal BankPaidAmt { get; set; }
        public decimal DocBankPaidAmt { get; set; }
        public decimal Rpt1BankPaidAmt { get; set; }
        public decimal Rpt2BankPaidAmt { get; set; }
        public decimal Rpt3BankPaidAmt { get; set; }
        public Nullable<System.DateTime> BankTransDate { get; set; }
        public string PaymentNumber { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public string VendorBankIBANCode { get; set; }
        public string OwnReference { get; set; }
        public int NOPaymentStatus { get; set; }
        public string NOPaymentDirection { get; set; }
        public string NOPaymentType { get; set; }
        public string NOTransferFileName { get; set; }
        public string NOBankTransRef { get; set; }
        public int BalanceUpdate { get; set; }
        public decimal BankClearedAmt { get; set; }
        public decimal BankRecGainLoss { get; set; }
        public string BOEInvoiceNum { get; set; }
        public decimal DocBankRecGainLoss { get; set; }
        public string MsgId { get; set; }
        public Nullable<System.DateTime> MXRecDate { get; set; }
        public string PayLegalNumber { get; set; }
        public string PayTranDocTypeID { get; set; }
        public decimal Rpt1BankRecGainLoss { get; set; }
        public decimal Rpt2BankRecGainLoss { get; set; }
        public decimal Rpt3BankRecGainLoss { get; set; }
        public string TaxPaymInfo { get; set; }
        public string VoidLegalNumber { get; set; }
        public string VoidTranDocTypeID { get; set; }
        public int SEGrpNum { get; set; }
        public string SEReference { get; set; }
        public bool SEISGroupedPO3 { get; set; }
        public bool SEISExported { get; set; }
        public string LegalNumber { get; set; }
        public string TranDocTypeID { get; set; }
        public string MXBankAcctNumber { get; set; }
        public string MXBankIdentifier { get; set; }
        public string MXRFC { get; set; }
        public bool BankBatchExcluded { get; set; }
        public System.Guid BankBatchSysRowID { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string ABTUID { get; set; }
        public string SEPAPaymentDescription { get; set; }
        public int THPayerType { get; set; }
        public string THRefInvoiceNum { get; set; }
        public int THRefVendorNum { get; set; }
        public string VoidedReason { get; set; }
        public string RegulatoryReportingCode { get; set; }
        public string MXFiscalFolio { get; set; }
        public Nullable<System.DateTime> TaxPointDate { get; set; }
        public string SEC { get; set; }
        public int ACHTranCode { get; set; }
        public string US1099KMerchCatCode { get; set; }
        public bool US1099KGen { get; set; }
        public string VendorBankBranchCode { get; set; }
        public Nullable<bool> CheckBox01 { get; set; }
        public Nullable<System.Guid> ForeignSysRowID { get; set; }
        public byte[] UD_SysRevID { get; set; }
    }
}
