//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Column
    {
        public string SchemaName { get; set; }
        public int TableID { get; set; }
        public string Name { get; set; }
        public int ColumnOrder { get; set; }
        public int ColumnID { get; set; }
        public byte SystemTypeID { get; set; }
        public string DataType { get; set; }
        public short MaxLength { get; set; }
        public byte Precision { get; set; }
        public byte Scale { get; set; }
        public bool IsNullable { get; set; }
        public string ColumnDefault { get; set; }
        public string ColumnDesc { get; set; }
        public string Format { get; set; }
        public string Label { get; set; }
        public bool is_identity { get; set; }
        public bool is_computed { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
    }
}
