//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public int id { get; set; }
        public int mid { get; set; }
        public string departmentname { get; set; }
        public string departmentsupervisor { get; set; }
        public string departmentsupervisorname { get; set; }
        public string ColorCode { get; set; }
        public string personID { get; set; }
    }
}
