//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string document_type { get; set; }
        public int document_id { get; set; }
        public string document_title { get; set; }
        public string document_name { get; set; }
        public string purpose { get; set; }
        public string scope { get; set; }
        public string responsibilities { get; set; }
        public string definitions { get; set; }
        public string procedures { get; set; }
        public string associated_documents { get; set; }
        public Nullable<int> revision_log { get; set; }
        public string associated_document_ID { get; set; }
        public Nullable<int> rev { get; set; }
        public string File_Subject_to_Approval_process { get; set; }
        public string rev_sec_para_changed { get; set; }
        public string rev_change_mode { get; set; }
        public string rev_changed_by { get; set; }
        public Nullable<System.DateTime> rev_changed_date { get; set; }
        public string rev_training_required { get; set; }
        public Nullable<System.DateTime> rev_training_completed_on { get; set; }
        public Nullable<int> attachment_ID { get; set; }
        public Nullable<int> property_Electrical_id { get; set; }
        public Nullable<int> property_approval_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_by { get; set; }
        public string document_ID_Title { get; set; }
        public string form { get; set; }
        public string notes { get; set; }
        public string proce_dure { get; set; }
        public string work_instruction { get; set; }
        public string ECN_Number { get; set; }
        public string ECN_Title { get; set; }
        public Nullable<System.DateTime> ECN_date_needed { get; set; }
        public string Customer_approval_required { get; set; }
        public string Customer_Notification_Required { get; set; }
        public string part_description_or_name { get; set; }
        public string part_number { get; set; }
        public string Drawing_Number { get; set; }
        public string Customer_part_number { get; set; }
        public Nullable<int> Current_rev { get; set; }
        public Nullable<int> New_rev { get; set; }
        public string description_of_change { get; set; }
        public string reason_for_change { get; set; }
        public Nullable<int> ECN_Will_change_no { get; set; }
        public string Instruction_for_ECN_implementation { get; set; }
        public Nullable<System.DateTime> implementation_date { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> update_date_doc { get; set; }
        public string update_by { get; set; }
    }
}
