//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECOOpr
    {
        public string Company { get; set; }
        public string PartNum { get; set; }
        public string RevisionNum { get; set; }
        public int OprSeq { get; set; }
        public string OpCode { get; set; }
        public string OpStdID { get; set; }
        public decimal EstSetHours { get; set; }
        public decimal EstProdHours { get; set; }
        public decimal ProdStandard { get; set; }
        public string StdFormat { get; set; }
        public string StdBasis { get; set; }
        public int OpsPerPart { get; set; }
        public decimal QtyPer { get; set; }
        public int Machines { get; set; }
        public decimal SetUpCrewSize { get; set; }
        public decimal ProdCrewSize { get; set; }
        public decimal EstScrap { get; set; }
        public string EstScrapType { get; set; }
        public bool SubContract { get; set; }
        public string IUM { get; set; }
        public decimal EstUnitCost { get; set; }
        public decimal DaysOut { get; set; }
        public string SubPartNum { get; set; }
        public int VendorNum { get; set; }
        public string PurPoint { get; set; }
        public string CommentText { get; set; }
        public string SchedRelation { get; set; }
        public decimal RunQty { get; set; }
        public decimal AddlSetupHours { get; set; }
        public decimal AddlSetUpQty { get; set; }
        public int APSPrepOp { get; set; }
        public int APSNextOp { get; set; }
        public int APSAltOp { get; set; }
        public string APSSpecificResource { get; set; }
        public decimal APSCycleTime { get; set; }
        public decimal APSConstantTime { get; set; }
        public int APSSetupGroup { get; set; }
        public int APSMakeFactor { get; set; }
        public decimal APSContainerSize { get; set; }
        public string APSSchedulerName { get; set; }
        public decimal APSMaxLength { get; set; }
        public decimal APSTransferTime { get; set; }
        public decimal APSEffectiveness { get; set; }
        public string APSOperationClass { get; set; }
        public string APSAuxResource { get; set; }
        public string APSAddResource { get; set; }
        public string LaborEntryMethod { get; set; }
        public decimal FAQty { get; set; }
        public bool RFQNeeded { get; set; }
        public int RFQVendQuotes { get; set; }
        public string GroupID { get; set; }
        public int OrigOprSeq { get; set; }
        public string SetupGroup { get; set; }
        public string AnalysisCode { get; set; }
        public int PrimarySetupOpDtl { get; set; }
        public int PrimaryProdOpDtl { get; set; }
        public string AltMethod { get; set; }
        public string OpDesc { get; set; }
        public string StageNumber { get; set; }
        public bool BaseMethodOverridden { get; set; }
        public string ParentAltMethod { get; set; }
        public int ParentOprSeq { get; set; }
        public decimal BrkQty01 { get; set; }
        public decimal BrkQty02 { get; set; }
        public decimal BrkQty03 { get; set; }
        public decimal BrkQty04 { get; set; }
        public decimal BrkQty05 { get; set; }
        public decimal BrkQty06 { get; set; }
        public decimal BrkQty07 { get; set; }
        public decimal BrkQty08 { get; set; }
        public decimal BrkQty09 { get; set; }
        public decimal BrkQty10 { get; set; }
        public decimal PBrkCost01 { get; set; }
        public decimal PBrkCost02 { get; set; }
        public decimal PBrkCost03 { get; set; }
        public decimal PBrkCost04 { get; set; }
        public decimal PBrkCost05 { get; set; }
        public decimal PBrkCost06 { get; set; }
        public decimal PBrkCost07 { get; set; }
        public decimal PBrkCost08 { get; set; }
        public decimal PBrkCost09 { get; set; }
        public decimal PBrkCost10 { get; set; }
        public decimal PBrkStdRate01 { get; set; }
        public decimal PBrkStdRate02 { get; set; }
        public decimal PBrkStdRate03 { get; set; }
        public decimal PBrkStdRate04 { get; set; }
        public decimal PBrkStdRate05 { get; set; }
        public decimal PBrkStdRate06 { get; set; }
        public decimal PBrkStdRate07 { get; set; }
        public decimal PBrkStdRate08 { get; set; }
        public decimal PBrkStdRate09 { get; set; }
        public decimal PBrkStdRate10 { get; set; }
        public bool SNRequiredOpr { get; set; }
        public bool SNRequiredSubConShip { get; set; }
        public decimal Weight { get; set; }
        public string WeightUOM { get; set; }
        public string SendAheadType { get; set; }
        public decimal SendAheadOffset { get; set; }
        public string PrjRoleList { get; set; }
        public bool UseAllRoles { get; set; }
        public bool ExternalMES { get; set; }
        public decimal PctReg { get; set; }
        public decimal SetupMaterial { get; set; }
        public int MaterialColorRating { get; set; }
        public string MiscInfo1 { get; set; }
        public string MiscInfo2 { get; set; }
        public string SetupURL { get; set; }
        public decimal ExpPctUp { get; set; }
        public decimal ExpCycTm { get; set; }
        public decimal ExpGood { get; set; }
        public decimal NonProdLimit { get; set; }
        public bool AutoSpcEnable { get; set; }
        public int AutoSpcPeriod { get; set; }
        public bool PartQualEnable { get; set; }
        public int AutoSpcSubgroup { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public int PulsesPerCycle { get; set; }
        public decimal QtyPerCycle { get; set; }
        public Nullable<decimal> Number01 { get; set; }
        public Nullable<decimal> Number02 { get; set; }
        public Nullable<decimal> Number03 { get; set; }
        public Nullable<decimal> Number04 { get; set; }
        public Nullable<decimal> Number05 { get; set; }
        public Nullable<System.Guid> ForeignSysRowID { get; set; }
        public byte[] UD_SysRevID { get; set; }
    }
}
