//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Course_data
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int courseid { get; set; }
        public string course_name { get; set; }
        public Nullable<System.DateTime> from_date { get; set; }
        public Nullable<System.DateTime> to_date { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public string location { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public string author_name { get; set; }
        public Nullable<bool> added_date_after_due_date { get; set; }
    }
}
