//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Training_final_database
    {
        public int ID { get; set; }
        public Nullable<int> CourceID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Empname { get; set; }
        public string Course_name { get; set; }
        public Nullable<System.DateTime> From_date { get; set; }
        public Nullable<System.DateTime> To_date { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public Nullable<int> MID { get; set; }
        public string location { get; set; }
        public string author { get; set; }
        public string instructor { get; set; }
        public string enteredby { get; set; }
        public Nullable<System.DateTime> uploaddate { get; set; }
        public string active { get; set; }
        public string uploadby { get; set; }
        public byte[] Evoluation_required { get; set; }
        public Nullable<System.DateTime> Evoluation_date { get; set; }
        public string Evoluation_method { get; set; }
        public string Evoluation_req { get; set; }
        public Nullable<bool> General_training { get; set; }
        public Nullable<bool> Technical_training { get; set; }
        public Nullable<bool> Safery_training { get; set; }
        public string Attachment { get; set; }
        public string description { get; set; }
        public string Attachment1_JobDescription { get; set; }
        public string Attachment2_Training_Hardcopy { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<bool> added_date_after_due_date { get; set; }
    }
}
