//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Limit
    {
        public int ID { get; set; }
        public int PID { get; set; }
        public int EmployeeID { get; set; }
        public string Employee_name { get; set; }
        public string Emp_dept { get; set; }
        public string Emp_Manager { get; set; }
        public Nullable<decimal> Emp_Limitnew { get; set; }
        public Nullable<int> Previous_emp_limit_no { get; set; }
        public Nullable<decimal> Previous_emp_Limit1 { get; set; }
        public Nullable<decimal> Previous_emp_Limit2 { get; set; }
        public Nullable<decimal> Previous_emp_limit3 { get; set; }
        public Nullable<decimal> Previous_emp_limit4 { get; set; }
        public Nullable<decimal> Previous_emp_limit5 { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> revised_date1 { get; set; }
        public Nullable<System.DateTime> revised_date2 { get; set; }
        public Nullable<System.DateTime> revised_date3 { get; set; }
        public Nullable<System.DateTime> revised_date4 { get; set; }
        public Nullable<System.DateTime> revised_date5 { get; set; }
        public string MPC_Member { get; set; }
        public string MPC_Number { get; set; }
    }
}
