//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int PersonId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Country { get; set; }
        public string Cityname { get; set; }
        public Nullable<int> Postalcode { get; set; }
        public string Password { get; set; }
        public Nullable<int> Number { get; set; }
    }
}
