//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engwork_MOM
    {
        public int Id { get; set; }
        public int RId { get; set; }
        public int MId { get; set; }
        public Nullable<System.DateTime> OPSeqSheetCompleteDate { get; set; }
        public Nullable<System.DateTime> MOMCompleteDate { get; set; }
        public string OPSequenceFileAttachment { get; set; }
        public string ProcessRemark { get; set; }
        public Nullable<bool> Is_deleted { get; set; }
        public Nullable<bool> Is_Saved { get; set; }
        public Nullable<bool> Is_Submited { get; set; }
        public Nullable<bool> Is_SavedBy { get; set; }
        public Nullable<System.DateTime> Timestapm { get; set; }
    }
}
