//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engwork_AddNewTool
    {
        public int Id { get; set; }
        public string ToolName { get; set; }
        public string PartDescription { get; set; }
        public string ToolType { get; set; }
        public string TotalCorner { get; set; }
        public Nullable<decimal> PerCornerQty { get; set; }
        public Nullable<decimal> TotalQty { get; set; }
        public Nullable<decimal> PerPartQty { get; set; }
        public Nullable<bool> Is_deleted { get; set; }
        public Nullable<bool> Is_Saved { get; set; }
        public Nullable<bool> Is_Submited { get; set; }
        public Nullable<bool> Is_SavedBy { get; set; }
        public Nullable<System.DateTime> Timestapm { get; set; }
    }
}
