//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engwork_MaterialSuggestion
    {
        public int Id { get; set; }
        public int RId { get; set; }
        public int MId { get; set; }
        public string MaterialGrade { get; set; }
        public Nullable<decimal> PartDimension { get; set; }
        public string MaterialPartName { get; set; }
        public string MaterialDescription { get; set; }
        public Nullable<decimal> UOM { get; set; }
        public Nullable<System.DateTime> MaterialEmailDate { get; set; }
        public Nullable<decimal> Calculator { get; set; }
        public Nullable<decimal> QtyPerParent { get; set; }
        public Nullable<bool> Is_deleted { get; set; }
        public Nullable<bool> Is_Saved { get; set; }
        public Nullable<bool> Is_Submited { get; set; }
        public Nullable<bool> Is_SavedBy { get; set; }
        public Nullable<System.DateTime> Timestapm { get; set; }
    }
}
