//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engwork_MAFIA
    {
        public int Id { get; set; }
        public int RId { get; set; }
        public int MId { get; set; }
        public Nullable<bool> SN_Available { get; set; }
        public Nullable<bool> FL_Available { get; set; }
        public Nullable<bool> MAFIA_Made { get; set; }
        public Nullable<bool> MAFIA_Released { get; set; }
        public Nullable<System.DateTime> MAFIA_MadeDate { get; set; }
        public Nullable<System.DateTime> MAFIA_ReleasedDate { get; set; }
        public string MAFIA_Remark { get; set; }
        public Nullable<System.DateTime> MAFIA_CorrectionDate { get; set; }
        public Nullable<System.DateTime> MAFIA_StatusCheckDate { get; set; }
        public Nullable<int> MadeBy { get; set; }
        public Nullable<bool> Is_deleted { get; set; }
        public Nullable<bool> Is_Saved { get; set; }
        public Nullable<bool> Is_Submited { get; set; }
        public Nullable<bool> Is_SavedBy { get; set; }
        public Nullable<System.DateTime> Timestapm { get; set; }
    }
}
