//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Epicor_Job_Head
    {
        public int Id { get; set; }
        public int MID { get; set; }
        public string Company { get; set; }
        public string JobNum { get; set; }
        public string PartNum { get; set; }
        public string Rev { get; set; }
        public string DrawNum { get; set; }
        public string PartDescription { get; set; }
        public Nullable<decimal> JobQty { get; set; }
        public Nullable<bool> JobClosed { get; set; }
        public Nullable<System.DateTime> Closed_date { get; set; }
        public Nullable<bool> JobCompleted { get; set; }
        public Nullable<System.DateTime> Completed_date { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
    }
}
