//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPO_Creation
    {
        public int ID { get; set; }
        public int EID { get; set; }
        public int PID { get; set; }
        public int GID { get; set; }
        public int LID { get; set; }
        public string EPOID { get; set; }
        public string employee_vendor { get; set; }
        public Nullable<int> employee_Id { get; set; }
        public Nullable<int> userid { get; set; }
        public string vendor { get; set; }
        public string vendorID { get; set; }
        public string street1 { get; set; }
        public string street2 { get; set; }
        public string country { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string zip { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string gst_no { get; set; }
        public string email { get; set; }
        public string purposeofpurchase { get; set; }
        public string epo_type { get; set; }
        public string receipt_method { get; set; }
        public string epo_purchase_status { get; set; }
        public string payment_type { get; set; }
        public string payment_given_by { get; set; }
        public string product_description { get; set; }
        public string product_group { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public string uom { get; set; }
        public string uom_other { get; set; }
        public string department { get; set; }
        public string account_no { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> cost_of_unit_price_and_qty { get; set; }
        public Nullable<decimal> extended_cost { get; set; }
        public Nullable<decimal> tax_with_discount { get; set; }
        public Nullable<decimal> tax_discount_gst { get; set; }
        public string within_gujarat { get; set; }
        public Nullable<decimal> gst { get; set; }
        public Nullable<decimal> cgst { get; set; }
        public Nullable<decimal> sgst { get; set; }
        public Nullable<decimal> igst { get; set; }
        public string purchase_type { get; set; }
        public string attachment_file_name { get; set; }
        public Nullable<System.DateTime> attachment_date { get; set; }
        public Nullable<int> attached_by_employee { get; set; }
        public string purchase_notes { get; set; }
        public string internal_notes { get; set; }
        public Nullable<decimal> shipping_charges { get; set; }
        public Nullable<decimal> sub_total { get; set; }
        public Nullable<decimal> grand_total { get; set; }
        public string employee_name { get; set; }
        public Nullable<System.DateTime> date_of_payment_check_request_or_cash_advance { get; set; }
        public string days_of_payment_pay_when_billed { get; set; }
        public string gujarat_or_outside { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string created_by { get; set; }
        public string Self_approval { get; set; }
        public string Manager_approval { get; set; }
        public string MPC_approval { get; set; }
        public string MPC_Higher_approval { get; set; }
        public Nullable<System.DateTime> Self_Date { get; set; }
        public Nullable<System.DateTime> Manager_approval_date { get; set; }
        public Nullable<System.DateTime> MPC_Approval_date { get; set; }
        public Nullable<System.DateTime> MPC_Higher_approval_date { get; set; }
        public string qty_status { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> revised_date { get; set; }
        public string approved_by { get; set; }
        public string street3 { get; set; }
        public string currency_type { get; set; }
        public string Without_Attachment { get; set; }
    }
}
