//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPO_MPC_VOTE
    {
        public int ID { get; set; }
        public int PID { get; set; }
        public int EPO { get; set; }
        public string MPC1_vote { get; set; }
        public string MPC2_vote { get; set; }
        public string MPC3_vote { get; set; }
        public string MPC4_vote { get; set; }
        public string MPC5_vote { get; set; }
        public string MPC6_vote { get; set; }
        public Nullable<int> countvote { get; set; }
        public string status { get; set; }
        public string need_Higher_Authority { get; set; }
        public string Higher_authority_vote { get; set; }
        public Nullable<System.DateTime> MPC1_vote_date { get; set; }
        public Nullable<System.DateTime> MPC2_vote_date { get; set; }
        public Nullable<System.DateTime> MPC3_vote_date { get; set; }
        public Nullable<System.DateTime> MPC4_vote_date { get; set; }
        public Nullable<System.DateTime> MPC5_vote_date { get; set; }
        public Nullable<System.DateTime> MPC6_vote_date { get; set; }
        public Nullable<System.DateTime> Higher_authority_vote_date { get; set; }
    }
}
