//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Management_MSM
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string event_ID { get; set; }
        public string Event_Name { get; set; }
        public Nullable<bool> Employee_ID { get; set; }
        public Nullable<bool> date { get; set; }
        public Nullable<bool> shift { get; set; }
        public Nullable<bool> time { get; set; }
        public Nullable<bool> MSM { get; set; }
        public Nullable<bool> hour_meter_reading { get; set; }
        public Nullable<bool> footage_counter_reading { get; set; }
        public Nullable<bool> shaft_name_or_new_shaft_name { get; set; }
        public Nullable<bool> FPM { get; set; }
        public Nullable<bool> Heat_temp { get; set; }
        public Nullable<bool> Brake_tension_Tighten_or_loosen { get; set; }
        public Nullable<bool> Head_1_RPM { get; set; }
        public Nullable<bool> Head_2_RPM { get; set; }
        public Nullable<bool> Head_3_RPM { get; set; }
        public Nullable<bool> Head_4_RPM { get; set; }
        public Nullable<bool> Head_5_RPM { get; set; }
        public Nullable<bool> Capstan_RPM { get; set; }
        public Nullable<bool> Reel { get; set; }
        public Nullable<bool> Reel_Tare_weight_KG { get; set; }
        public Nullable<bool> Reel_Gross_weight_KG { get; set; }
        public Nullable<bool> Approx_feet_on_reel { get; set; }
        public Nullable<bool> Head_number { get; set; }
        public Nullable<bool> New_RPM { get; set; }
        public Nullable<bool> Spool_from_Winding_head { get; set; }
        public Nullable<bool> TTROZ { get; set; }
        public Nullable<bool> Defl_Tol { get; set; }
        public Nullable<bool> Defl_LOL { get; set; }
        public Nullable<bool> UTS_TOL { get; set; }
        public Nullable<bool> UTL_TOL { get; set; }
        public Nullable<bool> Pulley_Teeth { get; set; }
        public Nullable<bool> order_no { get; set; }
        public Nullable<bool> feet_per_order { get; set; }
        public Nullable<bool> Layer_from { get; set; }
        public Nullable<bool> Layer_to { get; set; }
        public Nullable<bool> Approximate_Feet { get; set; }
        public Nullable<bool> Remark_Reason_details { get; set; }
        public Nullable<bool> shaft_OD { get; set; }
        public Nullable<bool> TTRAverage { get; set; }
        public Nullable<bool> TTRPeak { get; set; }
        public Nullable<bool> TTRMinimum { get; set; }
        public Nullable<bool> TTRDifferential { get; set; }
        public Nullable<bool> Head_1_Operator { get; set; }
        public Nullable<bool> Head_2_Operator { get; set; }
        public Nullable<bool> Head_3_Operator { get; set; }
        public Nullable<bool> Head_4_Operator { get; set; }
        public Nullable<bool> Head_5_Operator { get; set; }
        public Nullable<bool> Heater_Coil_Number_of_Turn { get; set; }
        public Nullable<bool> JobNum { get; set; }
    }
}
