//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Final_Inspection_Rework
    {
        public int ID { get; set; }
        public string InsID { get; set; }
        public string reworkID { get; set; }
        public string JobNum { get; set; }
        public string PartNum { get; set; }
        public Nullable<int> Rework_Qty { get; set; }
        public Nullable<int> Rework_complete_Qty { get; set; }
    }
}
