//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlexTopParts2
    {
        public string Name { get; set; }
        public Nullable<decimal> qtyper { get; set; }
        public string partnum { get; set; }
        public string mtlpartnum { get; set; }
        public Nullable<int> lv { get; set; }
        public string sort { get; set; }
        public string Part_LineCode { get; set; }
        public string Material_PartCode { get; set; }
        public string typecode { get; set; }
    }
}
