//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetMasterOrderDataset
    {
        public bool OpenOrderBool { get; set; }
        public int BackOrderBool { get; set; }
        public int RentalBool { get; set; }
        public string OrderType_c { get; set; }
        public string EntryPerson { get; set; }
        public int OrderNum { get; set; }
        public string PONum { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderMonthYear { get; set; }
        public int CustNum { get; set; }
        public string CustId { get; set; }
        public string CustName { get; set; }
        public string State { get; set; }
        public string DistributorId { get; set; }
        public string SalesRepCode { get; set; }
        public string RepName { get; set; }
        public string RepEmail { get; set; }
        public string RepReportsTo { get; set; }
        public Nullable<int> ShipCount { get; set; }
        public Nullable<int> PackNums { get; set; }
        public Nullable<int> TrackingNumbers { get; set; }
        public Nullable<int> ShipDate { get; set; }
        public Nullable<int> ShipMonthYear { get; set; }
        public string OpenInvoice { get; set; }
        public Nullable<int> InvoiceCount { get; set; }
        public string InvoiceNum { get; set; }
        public string InvoiceDate { get; set; }
        public string InvoiceMonthYear { get; set; }
        public string InvoiceLineTotal { get; set; }
        public string InvoiceMiscDiscounts { get; set; }
        public string InvoiceMiscCharges { get; set; }
        public Nullable<decimal> LineDiscountTotals { get; set; }
        public string CommissionableAmt { get; set; }
        public decimal HeaderRepRate { get; set; }
        public string Commission { get; set; }
        public decimal OrderAmt { get; set; }
        public Nullable<decimal> CommissionableInvoiceTotals { get; set; }
        public Nullable<decimal> CommissionTotal { get; set; }
        public int TotalLinesOrdered { get; set; }
        public Nullable<int> TotalLinesShipped { get; set; }
        public int TotalLinesInvoiced { get; set; }
    }
}
