//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIBC_Code_Generator
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public int UDI_ID { get; set; }
        public string Labeler_Code { get; set; }
        public string Brand_Name { get; set; }
        public string Version_or_Model { get; set; }
        public string Device_Description { get; set; }
        public string Product_Catalogue_Number { get; set; }
        public Nullable<int> UOM { get; set; }
        public string Primary_Check_Character { get; set; }
        public string Primary_Barcode_Data { get; set; }
        public string Text_Under_Primary_Bar_Code { get; set; }
        public string UPN_UDI_Device_Identifier { get; set; }
        public string UPN_UDI_Device_ID { get; set; }
        public string Lot_Number { get; set; }
        public string Secondary_Check_Character { get; set; }
        public string Secondary_Barcode_Data { get; set; }
        public string Text_Under_Secondary_Bar_Code { get; set; }
        public string Secondary_Barcode_Data2 { get; set; }
        public string Concentrate_Barcode1 { get; set; }
        public string Concentrate_Barcode2 { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Secondary_Barcode_Data1 { get; set; }
        public string barcode_imagename { get; set; }
        public string data_matrix_imagename { get; set; }
        public string qrcode_imagename { get; set; }
        public string qrcode_imagename_new { get; set; }
        public string Concentrate_Check_Character1 { get; set; }
        public string Concentrate_Check_Character_2 { get; set; }
    }
}
