//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIBC_Apprentix_Table
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public string Apprentix_Name { get; set; }
        public Nullable<int> Apprentix_VAlue { get; set; }
    }
}
