//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIBC_Temp_Storage
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string LICID { get; set; }
        public string LIC { get; set; }
        public string Product_Name { get; set; }
        public Nullable<int> UOM { get; set; }
        public string Lot_number { get; set; }
    }
}
