//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIBC_Primary_Barcode_Temp
    {
        public int Id { get; set; }
        public int MID { get; set; }
        public int UDI_ID { get; set; }
        public string Character_Name { get; set; }
        public Nullable<decimal> Characetr_value { get; set; }
        public Nullable<decimal> Reminder { get; set; }
        public string primary_secondary { get; set; }
    }
}
