//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndexColumn
    {
        public int TableID { get; set; }
        public int IndexID { get; set; }
        public int IndexColumnID { get; set; }
        public int ColumnID { get; set; }
        public byte KeyOrdinal { get; set; }
        public byte PartitionOrdinal { get; set; }
        public bool IsDescending { get; set; }
        public Nullable<bool> IsIncludedColumn { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
    }
}
