//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview_family_background
    {
        public int Id { get; set; }
        public int MID { get; set; }
        public Nullable<int> Personal_Id { get; set; }
        public string Relation { get; set; }
        public string Relation_name { get; set; }
        public string present_last_occupation { get; set; }
        public string name_of_organization { get; set; }
    }
}
