//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview_Education_details
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public Nullable<int> personal_Id { get; set; }
        public Nullable<System.DateTime> Academic_Year { get; set; }
        public string Course_name { get; set; }
        public string school_College_name { get; set; }
        public string Main_subject { get; set; }
        public string percentage { get; set; }
    }
}
