//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview_Questions
    {
        public int Id { get; set; }
        public int MID { get; set; }
        public string Question_Type { get; set; }
        public string Question_for_basic_English { get; set; }
        public string Question_for_basic_grammer { get; set; }
        public string Option_Basic_1 { get; set; }
        public string Option_Basic_2 { get; set; }
        public string Option_Basic_3 { get; set; }
        public string Option_Basic_4 { get; set; }
        public string Question_For_logic { get; set; }
        public string Option_logic_1 { get; set; }
        public string Option_logic_2 { get; set; }
        public string Option_logic_3 { get; set; }
        public string Option_logic_4 { get; set; }
        public string logic_question_Image { get; set; }
        public Nullable<bool> haslogicimage { get; set; }
        public string answer { get; set; }
    }
}
