//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview_form_personal_details
    {
        public int Id { get; set; }
        public int MID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Father_Husband_name { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<decimal> age { get; set; }
        public string sex { get; set; }
        public string maritual_status { get; set; }
        public Nullable<int> no_of_children { get; set; }
        public string current_addline1 { get; set; }
        public string current_addline2 { get; set; }
        public string current_addcity { get; set; }
        public string current_addtaluka { get; set; }
        public string current_adddist { get; set; }
        public string current_addmobile { get; set; }
        public string per_addline1 { get; set; }
        public string per_addline2 { get; set; }
        public string per_addcity { get; set; }
        public string per_addtaluka { get; set; }
        public string per_adddist { get; set; }
        public string per_addmobile { get; set; }
        public string per_addemail { get; set; }
        public Nullable<bool> relatives_at_sswhite { get; set; }
        public string relative_name { get; set; }
        public string relative_relation { get; set; }
        public string Identity_proof { get; set; }
        public string Identity_proof_name { get; set; }
        public Nullable<bool> disability { get; set; }
        public string disability_name { get; set; }
        public Nullable<System.DateTime> upload_date { get; set; }
        public Nullable<int> Basic_Question_Score { get; set; }
        public Nullable<int> Grammar_Score { get; set; }
        public Nullable<int> Logical_Score { get; set; }
        public string Experience { get; set; }
        public string Reference { get; set; }
        public string Interview_pdf { get; set; }
        public string Person_Img { get; set; }
    }
}
