//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue_Material
    {
        public string reqno { get; set; }
        public int id { get; set; }
        public int issue_id { get; set; }
        public int receiptno { get; set; }
        public int mid { get; set; }
        public string item_name { get; set; }
        public Nullable<int> onhandqty { get; set; }
        public Nullable<int> receivedqty { get; set; }
        public Nullable<int> totalqty { get; set; }
    }
}
