//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobHead
    {
        public string Company { get; set; }
        public bool JobClosed { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public bool JobComplete { get; set; }
        public Nullable<System.DateTime> JobCompletionDate { get; set; }
        public bool JobEngineered { get; set; }
        public bool CheckOff1 { get; set; }
        public bool CheckOff2 { get; set; }
        public bool CheckOff3 { get; set; }
        public bool CheckOff4 { get; set; }
        public bool CheckOff5 { get; set; }
        public bool JobReleased { get; set; }
        public bool JobHeld { get; set; }
        public string SchedStatus { get; set; }
        public string JobNum { get; set; }
        public string PartNum { get; set; }
        public string RevisionNum { get; set; }
        public string DrawNum { get; set; }
        public string PartDescription { get; set; }
        public decimal ProdQty { get; set; }
        public string IUM { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public decimal StartHour { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public decimal DueHour { get; set; }
        public Nullable<System.DateTime> ReqDueDate { get; set; }
        public string JobCode { get; set; }
        public int QuoteNum { get; set; }
        public int QuoteLine { get; set; }
        public string ProdCode { get; set; }
        public string UserChar1 { get; set; }
        public string UserChar2 { get; set; }
        public string UserChar3 { get; set; }
        public string UserChar4 { get; set; }
        public Nullable<System.DateTime> UserDate1 { get; set; }
        public Nullable<System.DateTime> UserDate2 { get; set; }
        public Nullable<System.DateTime> UserDate3 { get; set; }
        public Nullable<System.DateTime> UserDate4 { get; set; }
        public decimal UserDecimal1 { get; set; }
        public decimal UserDecimal2 { get; set; }
        public int UserInteger1 { get; set; }
        public int UserInteger2 { get; set; }
        public string CommentText { get; set; }
        public string ExpenseCode { get; set; }
        public bool InCopyList { get; set; }
        public string WIName { get; set; }
        public Nullable<System.DateTime> WIStartDate { get; set; }
        public decimal WIStartHour { get; set; }
        public Nullable<System.DateTime> WIDueDate { get; set; }
        public decimal WIDueHour { get; set; }
        public bool Candidate { get; set; }
        public string SchedCode { get; set; }
        public bool SchedLocked { get; set; }
        public string ProjectID { get; set; }
        public bool WIPCleared { get; set; }
        public bool JobFirm { get; set; }
        public string PersonList { get; set; }
        public string PersonID { get; set; }
        public string ProdTeamID { get; set; }
        public decimal QtyCompleted { get; set; }
        public string Plant { get; set; }
        public Nullable<System.DateTime> DatePurged { get; set; }
        public bool TravelerReadyToPrint { get; set; }
        public Nullable<System.DateTime> TravelerLastPrinted { get; set; }
        public bool StatusReadyToPrint { get; set; }
        public Nullable<System.DateTime> StatusLastPrinted { get; set; }
        public int CallNum { get; set; }
        public int CallLine { get; set; }
        public string JobType { get; set; }
        public string RestoreFlag { get; set; }
        public string PhaseID { get; set; }
        public string AnalysisCode { get; set; }
        public bool LockQty { get; set; }
        public int HDCaseNum { get; set; }
        public string ProcessMode { get; set; }
        public Nullable<System.DateTime> PlannedActionDate { get; set; }
        public Nullable<System.DateTime> PlannedKitDate { get; set; }
        public string MSPTaskID { get; set; }
        public string MSPPredecessor { get; set; }
        public string UserMapData { get; set; }
        public bool ProductionYield { get; set; }
        public decimal OrigProdQty { get; set; }
        public bool PreserveOrigQtys { get; set; }
        public bool NoAutoCompletion { get; set; }
        public bool NoAutoClosing { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool WhseAllocFlag { get; set; }
        public string OwnershipStatus { get; set; }
        public string PDMObjID { get; set; }
        public string ExportRequested { get; set; }
        public bool SplitMfgCostElements { get; set; }
        public string XRefPartNum { get; set; }
        public string XRefPartType { get; set; }
        public int XRefCustNum { get; set; }
        public string BasePartNum { get; set; }
        public string BaseRevisionNum { get; set; }
        public bool RoughCutScheduled { get; set; }
        public string EquipID { get; set; }
        public int PlanNum { get; set; }
        public string MaintPriority { get; set; }
        public bool SplitJob { get; set; }
        public bool NumberSource { get; set; }
        public int CloseMeterReading { get; set; }
        public string IssueTopicID1 { get; set; }
        public string IssueTopicID2 { get; set; }
        public string IssueTopicID3 { get; set; }
        public string IssueTopicID4 { get; set; }
        public string IssueTopicID5 { get; set; }
        public string IssueTopicID6 { get; set; }
        public string IssueTopicID7 { get; set; }
        public string IssueTopicID8 { get; set; }
        public string IssueTopicID9 { get; set; }
        public string IssueTopicID10 { get; set; }
        public string IssueTopics { get; set; }
        public string ResTopicID1 { get; set; }
        public string ResTopicID2 { get; set; }
        public string ResTopicID3 { get; set; }
        public string ResTopicID4 { get; set; }
        public string ResTopicID5 { get; set; }
        public string ResTopicID6 { get; set; }
        public string ResTopicID7 { get; set; }
        public string ResTopicID8 { get; set; }
        public string ResTopicID9 { get; set; }
        public string ResTopicID10 { get; set; }
        public string ResTopics { get; set; }
        public bool Forward { get; set; }
        public int SchedSeq { get; set; }
        public bool PAAExists { get; set; }
        public bool DtlsWithinLeadTime { get; set; }
        public int GroupSeq { get; set; }
        public bool RoughCut { get; set; }
        public string PlanGUID { get; set; }
        public string PlanUserID { get; set; }
        public string LastChangedBy { get; set; }
        public Nullable<System.DateTime> LastChangedOn { get; set; }
        public int EPMExportLevel { get; set; }
        public string JobWorkflowState { get; set; }
        public string JobCSR { get; set; }
        public bool ExternalMES { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public Nullable<System.DateTime> LastExternalMESDate { get; set; }
        public Nullable<System.DateTime> LastScheduleDate { get; set; }
        public string LastScheduleProc { get; set; }
        public int SchedPriority { get; set; }
        public int DaysLate { get; set; }
        public string ContractID { get; set; }
        public bool ProjProcessed { get; set; }
        public bool SyncReqBy { get; set; }
        public string CustName { get; set; }
        public string CustID { get; set; }
        public bool IsCSRSet { get; set; }
        public bool UnReadyCostProcess { get; set; }
        public string ProcSuspendedUpdates { get; set; }
        public Nullable<System.DateTime> ProjProcessedDate { get; set; }
        public bool PCLinkRemoved { get; set; }
        public bool ExternalMESSyncRequired { get; set; }
        public Nullable<System.DateTime> ExternalMESLastSync { get; set; }
        public bool EpicorFSA { get; set; }
    }
}
