//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine_Details
    {
        public int ID { get; set; }
        public string Machine_Type { get; set; }
        public string Machine_Name { get; set; }
        public string Dept { get; set; }
    }
}
