//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDR_Part_Data
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string MDR_No { get; set; }
        public string System_Name { get; set; }
        public string Product_Name { get; set; }
        public string Description { get; set; }
        public string Sub_System { get; set; }
        public Nullable<bool> Ref_Part { get; set; }
        public string Sub_Ref_Part { get; set; }
        public string Manufacturing_Production { get; set; }
        public string Assembly_part { get; set; }
        public string Sub_Ref_Part_desc { get; set; }
        public Nullable<bool> allow { get; set; }
    }
}
