//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class METADATA
    {
        public int ID { get; set; }
        public string requisition_no { get; set; }
        public string type { get; set; }
        public string Problem_solved { get; set; }
        public string status { get; set; }
        public string your_name { get; set; }
        public string shift { get; set; }
        public string requested_name { get; set; }
        public string machine_system_process_unit { get; set; }
        public string type_of_maintanance { get; set; }
        public string problem_type { get; set; }
        public string breakdown_problem { get; set; }
        public Nullable<System.DateTime> breakdown_date { get; set; }
        public string breakdown_time { get; set; }
        public string breakdown_time2 { get; set; }
        public string breakdown_reason { get; set; }
        public Nullable<System.DateTime> repairstart_date { get; set; }
        public string repairstart_time { get; set; }
        public string comment_on_waiting_to_breakdown { get; set; }
        public string repair_action_taken { get; set; }
        public Nullable<System.DateTime> repair_completion_date { get; set; }
        public string repair_completion_time { get; set; }
        public string comment_on_total_time_consumed_in_breakdown { get; set; }
        public string floor_shutdown_weeklyoff_holiday { get; set; }
        public Nullable<decimal> time_taken_to_atten_HR { get; set; }
        public Nullable<decimal> time_taken_to_attend_min { get; set; }
        public Nullable<decimal> time_taken_to_repair_HR { get; set; }
        public Nullable<decimal> time_taken_to_repair_min { get; set; }
        public Nullable<decimal> total_time_HR { get; set; }
        public Nullable<decimal> total_time_min { get; set; }
        public Nullable<decimal> adjustment_time_taken_to_attend_HR { get; set; }
        public Nullable<decimal> adjustment_time_taken_to_atten_min { get; set; }
        public string comment_for_time_adjustment { get; set; }
        public string part_name { get; set; }
        public Nullable<int> quantity { get; set; }
        public string cost { get; set; }
        public string part_name1 { get; set; }
        public Nullable<int> quantity1 { get; set; }
        public string cost1 { get; set; }
        public string part_name2 { get; set; }
        public Nullable<int> quantity2 { get; set; }
        public string cost2 { get; set; }
        public Nullable<decimal> machine_downtime_cost { get; set; }
        public Nullable<decimal> total_spare_part_cost { get; set; }
        public Nullable<decimal> total_cost { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string email_address { get; set; }
        public string breakdown_month { get; set; }
        public string remarks { get; set; }
        public string Approval { get; set; }
        public string Pending { get; set; }
        public string Closed { get; set; }
        public string usertype { get; set; }
        public string Machine_System_Process_Unit_Number { get; set; }
        public string reasonfornotapprove { get; set; }
        public Nullable<decimal> rstime { get; set; }
        public Nullable<decimal> rstimem { get; set; }
        public Nullable<decimal> rctime { get; set; }
        public Nullable<decimal> rctimem { get; set; }
        public Nullable<decimal> rtotal { get; set; }
        public Nullable<decimal> rtotalm { get; set; }
        public Nullable<decimal> adjustment_time_taken_to_repair_HR { get; set; }
        public Nullable<decimal> adjustment_time_taken_to_repair_min { get; set; }
        public Nullable<decimal> total_adjust_HR { get; set; }
        public Nullable<decimal> total_adjust_min { get; set; }
        public Nullable<decimal> total_repair_HR { get; set; }
        public Nullable<decimal> total_repair_min { get; set; }
        public string Comment_for_Adjust_repair { get; set; }
        public Nullable<int> userid { get; set; }
        public string Breakdown_detail_change_reason { get; set; }
        public string repair_detail_change_reason { get; set; }
        public string breakdown_detail_change { get; set; }
        public Nullable<System.DateTime> old_breakdown_date { get; set; }
        public string old_breakdown_time { get; set; }
        public Nullable<System.DateTime> upload_date { get; set; }
    }
}
