//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class nonreturnablegatepass
    {
        public string gatepassno { get; set; }
        public int id { get; set; }
        public int gid { get; set; }
        public string descriptionofgoods { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string remarks { get; set; }
        public string authorisedperson { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> deliverydate { get; set; }
        public Nullable<System.DateTime> cancelleddate { get; set; }
        public string reasonfordelete { get; set; }
        public string supplieraddress { get; set; }
    }
}
