//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartMtl
    {
        public string Company { get; set; }
        public string PartNum { get; set; }
        public string RevisionNum { get; set; }
        public int MtlSeq { get; set; }
        public string MtlPartNum { get; set; }
        public decimal QtyPer { get; set; }
        public bool FixedQty { get; set; }
        public int RelatedOperation { get; set; }
        public string SalvagePartNum { get; set; }
        public string SalvageDescription { get; set; }
        public decimal SalvageQtyPer { get; set; }
        public string SalvageUM { get; set; }
        public decimal SalvageUnitCredit { get; set; }
        public string MfgComment { get; set; }
        public bool OverRideMfgComments { get; set; }
        public string PurComment { get; set; }
        public bool OverRidePurComments { get; set; }
        public decimal EstScrap { get; set; }
        public string EstScrapType { get; set; }
        public bool PullAsAsm { get; set; }
        public string FindNum { get; set; }
        public bool ViewAsAsm { get; set; }
        public string APSSchedulerName { get; set; }
        public Nullable<System.DateTime> APSSLDate { get; set; }
        public decimal APSSLTime { get; set; }
        public string APSInsertDirection { get; set; }
        public string APSInsertCriteria { get; set; }
        public decimal APSAttrib1 { get; set; }
        public decimal APSAttrib2 { get; set; }
        public decimal APSAttrib3 { get; set; }
        public decimal APSAttrib4 { get; set; }
        public string APSAddResType { get; set; }
        public decimal SalvageMtlBurRate { get; set; }
        public decimal SalvageEstMtlBurUnitCredit { get; set; }
        public decimal MtlBurRate { get; set; }
        public decimal EstMtlBurUnitCost { get; set; }
        public bool RFQNeeded { get; set; }
        public int RFQVendQuotes { get; set; }
        public string AnalysisCode { get; set; }
        public string ReqdInPlant { get; set; }
        public string AltMethod { get; set; }
        public bool BaseMethodOverridden { get; set; }
        public string RelatedStage { get; set; }
        public string ParentAltMethod { get; set; }
        public int ParentMtlSeq { get; set; }
        public string UOMCode { get; set; }
        public decimal Weight { get; set; }
        public string WeightUOM { get; set; }
        public string RuleTag { get; set; }
        public int ReqRefDes { get; set; }
        public bool PlanAsAsm { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public bool ReassignSNAsm { get; set; }
        public bool ExternalMESSyncRequired { get; set; }
        public Nullable<System.DateTime> ExternalMESLastSync { get; set; }
        public bool LocationView { get; set; }
    }
}
