//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part_Library
    {
        public int ID { get; set; }
        public int PID { get; set; }
        public int RID { get; set; }
        public string type_of_doc { get; set; }
        public string part_type { get; set; }
        public string part_sub_type { get; set; }
        public string part_sub_sub_type { get; set; }
        public string part_name { get; set; }
        public string op_no { get; set; }
        public string attachment { get; set; }
        public string Machine_name { get; set; }
        public string type_of_op { get; set; }
        public Nullable<System.DateTime> Drawing_Revision_Date { get; set; }
        public Nullable<int> Drawing_Revision_no { get; set; }
        public Nullable<int> uploaded_Revision_no { get; set; }
        public string part_start_name { get; set; }
        public string Current_History { get; set; }
        public string Dra_rev_no { get; set; }
        public string Approved { get; set; }
        public Nullable<System.DateTime> Approval_date { get; set; }
        public string Created_by { get; set; }
        public string Approval_comment { get; set; }
        public string attchment2 { get; set; }
        public string Jobno { get; set; }
        public string PO_No { get; set; }
        public string approved_by { get; set; }
        public string attachment2 { get; set; }
        public string Machine_No { get; set; }
        public string attachment3 { get; set; }
        public string attachment4 { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
