//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartClass
    {
        public string Company { get; set; }
        public string ClassID { get; set; }
        public string Description { get; set; }
        public string BuyerID { get; set; }
        public bool RcvInspectionReq { get; set; }
        public string CommodityCode { get; set; }
        public bool AvailForReq { get; set; }
        public decimal MtlBurRate { get; set; }
        public bool SplitPOLine { get; set; }
        public string NegQtyAction { get; set; }
        public string PurchCode { get; set; }
        public bool ConsolidatedPurchasing { get; set; }
        public bool GlobalPartClass { get; set; }
        public bool GlobalLock { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public bool MMSInclude { get; set; }
        public bool MMSSales { get; set; }
        public bool MMSIssue { get; set; }
        public int MMSHistory { get; set; }
        public int MMSSafetyFactor { get; set; }
        public decimal MMSMaxFactor { get; set; }
        public int PartLeadTime { get; set; }
        public bool DeferredExp { get; set; }
        public string DEACode { get; set; }
        public bool LCNRVReporting { get; set; }
        public string Character01 { get; set; }
        public Nullable<System.Guid> ForeignSysRowID { get; set; }
        public byte[] UD_SysRevID { get; set; }
        public string InventoryClass_c { get; set; }
        public Nullable<bool> Inactive_c { get; set; }
    }
}
