//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartRev
    {
        public string Company { get; set; }
        public string PartNum { get; set; }
        public string RevisionNum { get; set; }
        public string RevShortDesc { get; set; }
        public string RevDescription { get; set; }
        public bool Approved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public decimal TLRLaborCost { get; set; }
        public decimal TLRBurdenCost { get; set; }
        public decimal TLRMaterialCost { get; set; }
        public decimal TLRSubcontractCost { get; set; }
        public decimal TLRMtlBurCost { get; set; }
        public decimal TLRSetupLaborCost { get; set; }
        public decimal TLRSetupBurdenCost { get; set; }
        public decimal LLRLaborCost { get; set; }
        public decimal LLRBurdenCost { get; set; }
        public decimal LLRMaterialCost { get; set; }
        public decimal LLRSubcontractCost { get; set; }
        public decimal LLRMtlBurCost { get; set; }
        public decimal LLRSetupLaborCost { get; set; }
        public decimal LLRSetupBurdenCost { get; set; }
        public Nullable<System.DateTime> RollupDate { get; set; }
        public string DrawNum { get; set; }
        public string ECO { get; set; }
        public bool Method { get; set; }
        public string AltMethod { get; set; }
        public string AltMethodDesc { get; set; }
        public string ParentAltMethod { get; set; }
        public bool UseStaging { get; set; }
        public bool UseAltRevForParts { get; set; }
        public string BasePartNum { get; set; }
        public string BaseRevisionNum { get; set; }
        public bool GlobalRev { get; set; }
    }
}
