//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PcInputValue
    {
        public string Company { get; set; }
        public int GroupSeq { get; set; }
        public string RelatedToTableName { get; set; }
        public System.Guid RelatedToSysRowID { get; set; }
        public int HeadNum { get; set; }
        public string StructTag { get; set; }
        public string ConfigID { get; set; }
        public string RuleTag { get; set; }
        public int RevolvingSeq { get; set; }
        public string ForeignTableName { get; set; }
        public System.Guid ForeignSysRowID { get; set; }
        public string SourceTableName { get; set; }
        public System.Guid SourceSysRowID { get; set; }
        public string ConfigType { get; set; }
        public int ConfigVersion { get; set; }
        public bool ExtConfig { get; set; }
        public string ExtCompany { get; set; }
        public bool AllowRecordCreation { get; set; }
        public bool AllowPricing { get; set; }
        public bool PromptForConfig { get; set; }
        public bool InSmartString { get; set; }
        public bool DisplaySummary { get; set; }
        public bool AllowReconfig { get; set; }
        public string NewPartNum { get; set; }
        public string NewSmartString { get; set; }
        public bool SIValues { get; set; }
        public int PageSeq { get; set; }
        public string InputName { get; set; }
        public string InputValue { get; set; }
        public string DataType { get; set; }
        public System.Guid SysRowID { get; set; }
        public byte[] SysRevID { get; set; }
    }
}
