//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_Flex_Part_List_History
    {
        public int ID { get; set; }
        public int PID { get; set; }
        public int MID { get; set; }
        public string Part_number { get; set; }
        public string Revision_Number { get; set; }
        public string Part_Type { get; set; }
        public string Weight { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Approved { get; set; }
        public Nullable<System.DateTime> Upload_date { get; set; }
        public Nullable<System.DateTime> change_date { get; set; }
    }
}
