//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_Flex_Bulk_Shaft_Job_List
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string Job_Number { get; set; }
        public Nullable<decimal> Job_Qty { get; set; }
        public string Part_Number { get; set; }
        public string Revision_Number { get; set; }
        public Nullable<int> Part_ID { get; set; }
        public string part_type { get; set; }
        public Nullable<System.DateTime> Upload_date { get; set; }
        public string Upload_By { get; set; }
    }
}
