//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program_Operation_wise_Tool_Library
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string Part_Name { get; set; }
        public string Op_No { get; set; }
        public string Type_of_Operation { get; set; }
        public string Tool_Type { get; set; }
        public string Tool_Name { get; set; }
        public string Machine_Name { get; set; }
        public Nullable<int> Program_ID { get; set; }
        public string Machine_No { get; set; }
        public string Job_No { get; set; }
        public string Rev_no { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
