//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurAgent
    {
        public bool InActive { get; set; }
        public string Company { get; set; }
        public string BuyerID { get; set; }
        public string Name { get; set; }
        public string ApprovalPerson { get; set; }
        public decimal POLimit { get; set; }
        public string EMailAddress { get; set; }
        public bool ConsolidatedPurchasing { get; set; }
        public string CnvEmpID { get; set; }
        public int PerConID { get; set; }
        public bool SyncNameToPerCon { get; set; }
        public bool SyncEmailToPerCon { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public string Character01 { get; set; }
        public Nullable<System.Guid> ForeignSysRowID { get; set; }
        public byte[] UD_SysRevID { get; set; }
    }
}
