//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class purreq_invoice_viewdetail
    {
        public string reqno { get; set; }
        public int Id { get; set; }
        public int line_no { get; set; }
        public int pid { get; set; }
        public string payslipno { get; set; }
        public string invoice_no { get; set; }
        public string challan_no { get; set; }
        public string itemname { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
        public string supp_name { get; set; }
        public Nullable<int> itemqty { get; set; }
        public Nullable<int> remaining_qty { get; set; }
        public Nullable<int> received_qty { get; set; }
        public Nullable<int> Transaction_qty { get; set; }
        public string remark { get; set; }
        public Nullable<int> payslipnonew { get; set; }
        public Nullable<decimal> itemqty_new { get; set; }
        public Nullable<decimal> remaining_qty_new { get; set; }
        public Nullable<decimal> received_qty_new { get; set; }
        public Nullable<decimal> transaction_qty_new { get; set; }
        public Nullable<System.DateTime> Issue_date { get; set; }
        public string Issue_by { get; set; }
        public string Issue_status { get; set; }
        public Nullable<decimal> issue_ite_qty { get; set; }
    }
}
