//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RcvDtl
    {
        public string Company { get; set; }
        public int VendorNum { get; set; }
        public string PurPoint { get; set; }
        public string PackSlip { get; set; }
        public int PackLine { get; set; }
        public bool Invoiced { get; set; }
        public string InvoiceNum { get; set; }
        public int InvoiceLine { get; set; }
        public string PartNum { get; set; }
        public string WareHouseCode { get; set; }
        public string BinNum { get; set; }
        public decimal OurQty { get; set; }
        public string IUM { get; set; }
        public decimal OurUnitCost { get; set; }
        public string JobNum { get; set; }
        public int AssemblySeq { get; set; }
        public string JobSeqType { get; set; }
        public int JobSeq { get; set; }
        public int PONum { get; set; }
        public int POLine { get; set; }
        public int PORelNum { get; set; }
        public string TranReference { get; set; }
        public string PartDescription { get; set; }
        public string RevisionNum { get; set; }
        public decimal VendorQty { get; set; }
        public decimal VendorUnitCost { get; set; }
        public string ReceiptType { get; set; }
        public string ReceivedTo { get; set; }
        public bool ReceivedComplete { get; set; }
        public bool IssuedComplete { get; set; }
        public string PUM { get; set; }
        public string VenPartNum { get; set; }
        public string CostPerCode { get; set; }
        public string LotNum { get; set; }
        public int NumLabels { get; set; }
        public string DimCode { get; set; }
        public string DUM { get; set; }
        public decimal DimConvFactor { get; set; }
        public bool InspectionReq { get; set; }
        public bool InspectionPending { get; set; }
        public string InspectorID { get; set; }
        public string InspectedBy { get; set; }
        public Nullable<System.DateTime> InspectedDate { get; set; }
        public int InspectedTime { get; set; }
        public decimal PassedQty { get; set; }
        public decimal FailedQty { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public string ReasonCode { get; set; }
        public decimal TotCostVariance { get; set; }
        public decimal Weight { get; set; }
        public string WeightUOM { get; set; }
        public bool NonConformnce { get; set; }
        public decimal MtlBurRate { get; set; }
        public decimal OurMtlBurUnitCost { get; set; }
        public string RefType { get; set; }
        public string RefCode { get; set; }
        public string PurchCode { get; set; }
        public bool LCFlag { get; set; }
        public string GlbCompany { get; set; }
        public int GlbVendorNum { get; set; }
        public string GlbPurPoint { get; set; }
        public string GlbPackSlip { get; set; }
        public int GlbPackLine { get; set; }
        public decimal DocUnitCost { get; set; }
        public int ContainerID { get; set; }
        public decimal Volume { get; set; }
        public decimal Rpt1UnitCost { get; set; }
        public decimal Rpt2UnitCost { get; set; }
        public decimal Rpt3UnitCost { get; set; }
        public int OrderNum { get; set; }
        public int OrderLine { get; set; }
        public int OrderRelNum { get; set; }
        public int OrigCountryNum { get; set; }
        public decimal UpliftPercent { get; set; }
        public decimal LCDutyAmt { get; set; }
        public decimal LCIndCost { get; set; }
        public decimal POTransValue { get; set; }
        public decimal ExtTransValue { get; set; }
        public bool Received { get; set; }
        public string CommodityCode { get; set; }
        public string POType { get; set; }
        public bool AutoReceipt { get; set; }
        public string VolumeUOM { get; set; }
        public Nullable<System.DateTime> ArrivedDate { get; set; }
        public decimal LCSpecLineDutyAmt { get; set; }
        public decimal AppliedRcptLCAmt { get; set; }
        public decimal LCUpliftIndCost { get; set; }
        public decimal LCAmt { get; set; }
        public decimal AppliedLCVariance { get; set; }
        public decimal LCMtlBurUnitCost { get; set; }
        public decimal DocVendorUnitCost { get; set; }
        public decimal Rpt1VendorUnitCost { get; set; }
        public decimal Rpt2VendorUnitCost { get; set; }
        public decimal Rpt3VendorUnitCost { get; set; }
        public bool NotCompliant { get; set; }
        public string ComplianceMsg { get; set; }
        public int MangCustNum { get; set; }
        public string LegalNumber { get; set; }
        public int ICPackNum { get; set; }
        public string ShipRcv { get; set; }
        public string ImportNum { get; set; }
        public int ImportedFrom { get; set; }
        public string ImportedFromDesc { get; set; }
        public decimal GrossWeight { get; set; }
        public string GrossWeightUOM { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public string QtyOption { get; set; }
        public bool ConvOverride { get; set; }
        public string ContractID { get; set; }
        public int SMITransNum { get; set; }
        public string PCID { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public bool Delivered { get; set; }
        public string DeliveredComments { get; set; }
        public decimal InOurCost { get; set; }
        public decimal DocInUnitCost { get; set; }
        public decimal Rpt1InUnitCost { get; set; }
        public decimal Rpt2InUnitCost { get; set; }
        public decimal Rpt3InUnitCost { get; set; }
        public decimal InVendorUnitCost { get; set; }
        public decimal DocInVendorUnitCost { get; set; }
        public decimal Rpt1InVendorUnitCost { get; set; }
        public decimal Rpt2InVendorUnitCost { get; set; }
        public decimal Rpt3InVendorUnitCost { get; set; }
        public decimal SupplierUnInvcReceiptQty { get; set; }
        public decimal OurUnInvcReceiptQty { get; set; }
        public string TaxRegionCode { get; set; }
        public string TaxCatID { get; set; }
        public bool Taxable { get; set; }
        public string TaxExempt { get; set; }
        public bool NoTaxRecalc { get; set; }
        public decimal InAppliedLCVariance { get; set; }
        public decimal InAppliedRcptLCAmt { get; set; }
        public decimal InLCAmt { get; set; }
        public decimal InLCDutyAmt { get; set; }
        public decimal InLCIndCost { get; set; }
        public decimal InLCMtlBurUnitCost { get; set; }
        public decimal InLCSpecLineDutyAmt { get; set; }
        public decimal InLCUpliftIndCost { get; set; }
        public decimal InPOTransValue { get; set; }
        public bool ProjProcessed { get; set; }
        public decimal ExtNonRecoverableCost { get; set; }
        public bool EpicorFSA { get; set; }
        public string Character01 { get; set; }
        public string Character02 { get; set; }
        public Nullable<System.DateTime> Date01 { get; set; }
        public Nullable<bool> CheckBox01 { get; set; }
        public string ShortChar01 { get; set; }
        public string ShortChar02 { get; set; }
        public Nullable<System.Guid> ForeignSysRowID { get; set; }
        public byte[] UD_SysRevID { get; set; }
    }
}
