//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMADtl
    {
        public string Company { get; set; }
        public bool OpenRMA { get; set; }
        public bool OpenDtl { get; set; }
        public int RMANum { get; set; }
        public int RMALine { get; set; }
        public int OrderNum { get; set; }
        public int OrderLine { get; set; }
        public string ReturnReasonCode { get; set; }
        public string Note { get; set; }
        public string PartNum { get; set; }
        public string LineDesc { get; set; }
        public string RevisionNum { get; set; }
        public decimal ReturnQty { get; set; }
        public string ReturnQtyUOM { get; set; }
        public int RefInvoiceNum { get; set; }
        public int RefInvoiceLine { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public int ChangeTime { get; set; }
        public string ShipToNum { get; set; }
        public int ConNum { get; set; }
        public int CustNum { get; set; }
        public int OrderRelNum { get; set; }
        public int ShipToCustNum { get; set; }
        public int InvoiceNum { get; set; }
        public int InvoiceLine { get; set; }
        public string JobNum { get; set; }
        public int AssemblySeq { get; set; }
        public int MtlSeq { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public string ECCComment { get; set; }
        public string ECCRMANum { get; set; }
        public int ECCRMALine { get; set; }
        public string Character01 { get; set; }
        public string Character02 { get; set; }
        public string Character03 { get; set; }
        public string Character04 { get; set; }
        public Nullable<bool> CheckBox01 { get; set; }
        public Nullable<bool> CheckBox02 { get; set; }
        public Nullable<bool> CheckBox03 { get; set; }
        public Nullable<System.Guid> ForeignSysRowID { get; set; }
        public byte[] UD_SysRevID { get; set; }
    }
}
