//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMAHead
    {
        public bool OpenRMA { get; set; }
        public string Company { get; set; }
        public int RMANum { get; set; }
        public Nullable<System.DateTime> RMADate { get; set; }
        public int CustNum { get; set; }
        public string DebitMemoRef { get; set; }
        public string CLCallNum { get; set; }
        public string XRefRMANumber { get; set; }
        public int HDCaseNum { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public int ChangeTime { get; set; }
        public string ShipToNum { get; set; }
        public int ConNum { get; set; }
        public bool AutoPrintReady { get; set; }
        public int BTCustNum { get; set; }
        public bool UseOTS { get; set; }
        public string OTSName { get; set; }
        public string OTSAddress1 { get; set; }
        public string OTSAddress2 { get; set; }
        public string OTSAddress3 { get; set; }
        public string OTSCity { get; set; }
        public string OTSState { get; set; }
        public string OTSZIP { get; set; }
        public string OTSResaleID { get; set; }
        public string OTSTaxRegionCode { get; set; }
        public string OTSContact { get; set; }
        public string OTSFaxNum { get; set; }
        public string OTSPhoneNum { get; set; }
        public int OTSCountryNum { get; set; }
        public int ShipToCustNum { get; set; }
        public int InvoiceNum { get; set; }
        public string TranDocTypeID { get; set; }
        public string LegalNumber { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public string RetInvoiceNum { get; set; }
        public string ECCRMANum { get; set; }
        public string ECCCustRef { get; set; }
        public bool DocumentPrinted { get; set; }
        public string RMAComment { get; set; }
        public string WebComment { get; set; }
        public bool EpicorFSA { get; set; }
        public Nullable<System.Guid> ForeignSysRowID { get; set; }
        public byte[] UD_SysRevID { get; set; }
        public Nullable<int> IncidentReportNum_c { get; set; }
    }
}
