//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMARcpt
    {
        public string Company { get; set; }
        public int RMANum { get; set; }
        public int RMALine { get; set; }
        public int RMAReceipt { get; set; }
        public string WareHouseCode { get; set; }
        public string BinNum { get; set; }
        public Nullable<System.DateTime> RcvDate { get; set; }
        public string LotNum { get; set; }
        public bool OpenReceipt { get; set; }
        public decimal MtlUnitCost { get; set; }
        public decimal LbrUnitCost { get; set; }
        public decimal BurUnitCost { get; set; }
        public decimal SubUnitCost { get; set; }
        public decimal MtlBurUnitCost { get; set; }
        public string Plant { get; set; }
        public decimal MtlMtlUnitCost { get; set; }
        public decimal MtlLabUnitCost { get; set; }
        public decimal MtlSubUnitCost { get; set; }
        public decimal MtlBurdenUnitCost { get; set; }
        public decimal MtlMtlBurUnitCost { get; set; }
        public decimal ReceivedQty { get; set; }
        public decimal DisposedQty { get; set; }
        public string CostUOM { get; set; }
        public string ReceivedQtyUOM { get; set; }
        public string LegalNumber { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public int ChangeTime { get; set; }
        public bool RequestMove { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
    }
}
