//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSW_Appliances_Main_added
    {
        public int ID { get; set; }
        public int PID { get; set; }
        public int MID { get; set; }
        public string Type_of_appliance { get; set; }
        public string Appliance_type { get; set; }
        public string Appliance_Name { get; set; }
        public string Appliance_Number { get; set; }
        public string Active { get; set; }
        public string Hall { get; set; }
        public string IP { get; set; }
        public string monitor_detail { get; set; }
        public string mount_stand { get; set; }
        public string Window_version { get; set; }
        public string PC_configuration { get; set; }
        public string Keyboard_Mouse { get; set; }
        public string Desktop_Phone { get; set; }
        public string MAC_Address { get; set; }
        public string Appliance_sub_type { get; set; }
    }
}
