//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSW_Vacancy
    {
        public int ID { get; set; }
        public int PID { get; set; }
        public int MID { get; set; }
        public string Applicant_name { get; set; }
        public string Applicant_email { get; set; }
        public string Applicant_Mobile { get; set; }
        public string Applicant_Position { get; set; }
        public string Attachment { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
