//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class sswhite_gallery
    {
        public int MID { get; set; }
        public int ImageID { get; set; }
        public int ID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Title { get; set; }
        public string aTitle { get; set; }
        public string Type { get; set; }
        public string image { get; set; }
        public string image_name { get; set; }
    }
}
