//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubShipH
    {
        public string Company { get; set; }
        public int PackNum { get; set; }
        public int VendorNum { get; set; }
        public string PurPoint { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string ShipViaCode { get; set; }
        public string ShipPerson { get; set; }
        public string EntryPerson { get; set; }
        public string ShipLog { get; set; }
        public string LabelComment { get; set; }
        public string ShipComment { get; set; }
        public string Plant { get; set; }
        public string TrackingNumber { get; set; }
        public string LegalNumber { get; set; }
        public bool ResDelivery { get; set; }
        public bool SatDelivery { get; set; }
        public bool SatPickup { get; set; }
        public bool Hazmat { get; set; }
        public bool DocOnly { get; set; }
        public string RefNotes { get; set; }
        public bool ApplyChrg { get; set; }
        public decimal ChrgAmount { get; set; }
        public bool COD { get; set; }
        public bool CODFreight { get; set; }
        public bool CODCheck { get; set; }
        public decimal CODAmount { get; set; }
        public string GroundType { get; set; }
        public bool NotifyFlag { get; set; }
        public string NotifyEMail { get; set; }
        public bool DeclaredIns { get; set; }
        public decimal DeclaredAmt { get; set; }
        public string MFTransNum { get; set; }
        public string MFCallTag { get; set; }
        public string MFPickupNum { get; set; }
        public decimal MFDiscFreight { get; set; }
        public string MFTemplate { get; set; }
        public bool MFUse3B { get; set; }
        public string MF3BAccount { get; set; }
        public decimal MFDimWeight { get; set; }
        public string MFZone { get; set; }
        public decimal MFFreightAmt { get; set; }
        public decimal MFOtherAmt { get; set; }
        public bool MFOversized { get; set; }
        public string ShipStatus { get; set; }
        public string ShipGroup { get; set; }
        public decimal Weight { get; set; }
        public string PkgCode { get; set; }
        public string PkgClass { get; set; }
        public bool ServSignature { get; set; }
        public bool ServAlert { get; set; }
        public bool ServHomeDel { get; set; }
        public string DeliveryType { get; set; }
        public Nullable<System.DateTime> ServDeliveryDate { get; set; }
        public string ServPhone { get; set; }
        public string ServInstruct { get; set; }
        public bool ServRelease { get; set; }
        public string ServAuthNum { get; set; }
        public string ServRef1 { get; set; }
        public string ServRef2 { get; set; }
        public string ServRef3 { get; set; }
        public string ServRef4 { get; set; }
        public string ServRef5 { get; set; }
        public int BOLNum { get; set; }
        public int BOLLine { get; set; }
        public bool CommercialInvoice { get; set; }
        public bool ShipExprtDeclartn { get; set; }
        public bool CertOfOrigin { get; set; }
        public bool LetterOfInstr { get; set; }
        public bool HazardousShipment { get; set; }
        public bool IntrntlShip { get; set; }
        public string PayFlag { get; set; }
        public string PayAccount { get; set; }
        public string PayBTAddress1 { get; set; }
        public string PayBTAddress2 { get; set; }
        public string PayBTCity { get; set; }
        public string PayBTState { get; set; }
        public string PayBTZip { get; set; }
        public string PayBTCountry { get; set; }
        public string FFID { get; set; }
        public string FFAddress1 { get; set; }
        public string FFAddress2 { get; set; }
        public string FFCity { get; set; }
        public string FFState { get; set; }
        public string FFZip { get; set; }
        public string FFCountry { get; set; }
        public string FFContact { get; set; }
        public string FFCompName { get; set; }
        public string FFPhoneNum { get; set; }
        public bool IndividualPackIDs { get; set; }
        public string FFAddress3 { get; set; }
        public int DeliveryConf { get; set; }
        public bool AddlHdlgFlag { get; set; }
        public bool NonStdPkg { get; set; }
        public int FFCountryNum { get; set; }
        public string PayBTAddress3 { get; set; }
        public int PayBTCountryNum { get; set; }
        public string PayBTPhone { get; set; }
        public string WayBillNbr { get; set; }
        public string FreightedShipViaCode { get; set; }
        public bool UPSQuantumView { get; set; }
        public string UPSQVShipFromName { get; set; }
        public string UPSQVMemo { get; set; }
        public decimal PkgLength { get; set; }
        public decimal PkgWidth { get; set; }
        public decimal PkgHeight { get; set; }
        public bool PhantomPack { get; set; }
        public string PkgSizeUOM { get; set; }
        public string WeightUOM { get; set; }
        public string TranDocTypeID { get; set; }
        public bool DocumentPrinted { get; set; }
        public string DeviceUOM { get; set; }
        public string ManifestSizeUOM { get; set; }
        public string ManifestWtUOM { get; set; }
        public decimal ManifestWeight { get; set; }
        public decimal ManifestLength { get; set; }
        public decimal ManifestWidth { get; set; }
        public decimal ManifestHeight { get; set; }
        public bool AutoPrintReady { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public string AGAuthorizationCode { get; set; }
        public Nullable<System.DateTime> AGAuthorizationDate { get; set; }
        public string AGCarrierCUIT { get; set; }
        public string AGDocumentLetter { get; set; }
        public string AGInvoicingPoint { get; set; }
        public string AGLegalNumber { get; set; }
        public string AGPrintingControlType { get; set; }
        public string AGTrackLicense { get; set; }
        public string DispatchReason { get; set; }
        public string AGShippingWay { get; set; }
        public bool AGCOTMark { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string DigitalSignature { get; set; }
        public Nullable<System.DateTime> SignedOn { get; set; }
        public string SignedBy { get; set; }
        public Nullable<System.DateTime> FirstPrintDate { get; set; }
        public int DocCopyNum { get; set; }
        public string Character03 { get; set; }
        public Nullable<System.Guid> ForeignSysRowID { get; set; }
        public byte[] UD_SysRevID { get; set; }
        public Nullable<decimal> OBShippingCost_c { get; set; }
    }
}
