//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Data
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public string Supp_ID { get; set; }
        public string Supp_Name { get; set; }
        public string Supp_Add1 { get; set; }
        public string Supp_Add2 { get; set; }
        public string Supp_Add3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string country { get; set; }
        public string phone { get; set; }
        public string email_Id { get; set; }
        public string Pan_no { get; set; }
        public string GST_No { get; set; }
        public string postal_code { get; set; }
    }
}
