//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_New_Data
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public string Supplier_ID { get; set; }
        public string Supp_name { get; set; }
        public string Supp_add1 { get; set; }
        public string Supp_add2 { get; set; }
        public string Supp_add3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string postal_code { get; set; }
        public string country { get; set; }
        public string phone { get; set; }
        public string email_id { get; set; }
        public string GSTIN { get; set; }
        public string Register_Type { get; set; }
    }
}
