//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int TableID { get; set; }
        public string Name { get; set; }
        public string TableDesc { get; set; }
        public Nullable<bool> IsReplicated { get; set; }
        public Nullable<bool> HasReplicationFilter { get; set; }
        public Nullable<bool> IsMergePublished { get; set; }
        public Nullable<bool> IsSyncTranSubscribed { get; set; }
        public Nullable<bool> IsTrackedByCDC { get; set; }
        public Nullable<int> PrimaryIndexID { get; set; }
        public string PrimaryIndexName { get; set; }
        public string TableOwner { get; set; }
        public string SchemaName { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
    }
}
