//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Management_Trial_Secondary
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string Task_ID { get; set; }
        public string Assign_ID { get; set; }
        public string Task_Name { get; set; }
        public Nullable<System.DateTime> Task_Date { get; set; }
        public Nullable<decimal> Task_Hour { get; set; }
        public string Task_Assigned { get; set; }
        public Nullable<bool> Complete { get; set; }
        public Nullable<System.DateTime> task_start_date { get; set; }
        public string task_start_time { get; set; }
        public Nullable<System.DateTime> task_end_date { get; set; }
        public string task_end_time { get; set; }
        public string task_status { get; set; }
        public string task_department { get; set; }
    }
}
