//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Management_Trial
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string taskID { get; set; }
        public string Task_Name { get; set; }
        public string Task_Remark { get; set; }
        public Nullable<System.DateTime> Task_Date { get; set; }
        public Nullable<decimal> Task_hour { get; set; }
        public string Task_Assigned { get; set; }
        public Nullable<bool> Complete { get; set; }
    }
}
