//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_process_chat
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string Ticketno { get; set; }
        public Nullable<int> Ticket_user { get; set; }
        public string Ticket_chat { get; set; }
        public string Ticket_remark { get; set; }
        public Nullable<System.DateTime> chat_date { get; set; }
    }
}
