//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tool_Category
    {
        public int ID { get; set; }
        public string Tool_Category1 { get; set; }
        public string Tool_Type { get; set; }
        public string Tool_type_search_word { get; set; }
        public string Tool_Type_description { get; set; }
        public Nullable<int> MID { get; set; }
        public Nullable<int> PID { get; set; }
        public string Tool_Type_Name { get; set; }
        public Nullable<int> Qty_in_Shopfloor_Monday { get; set; }
        public string Using { get; set; }
    }
}
