//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tool_Utilization
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string Tool_Category { get; set; }
        public string Tool_Name { get; set; }
        public Nullable<int> Order_Qty { get; set; }
        public Nullable<int> Received_Qty { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> upload_date { get; set; }
        public string uploadedby { get; set; }
        public Nullable<int> Shop_floor_Onhand_Qty { get; set; }
        public string Machine_Type { get; set; }
        public string Req_Status { get; set; }
        public Nullable<int> Store_on_Hand_qty { get; set; }
        public string Jobno { get; set; }
        public string Machine_name { get; set; }
        public string Part_No { get; set; }
        public string Rev { get; set; }
        public Nullable<int> Issue_Qty { get; set; }
        public Nullable<int> transaction_qty { get; set; }
        public Nullable<System.DateTime> transaction_date { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
        public Nullable<System.DateTime> transaction__transaction_date { get; set; }
    }
}
