//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tooling_Utilization_all_details
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public Nullable<int> Transaction_Id { get; set; }
        public string Tool_Type { get; set; }
        public string Tool_Name { get; set; }
        public Nullable<int> Order_Qty { get; set; }
        public Nullable<int> Shop_floor_qty { get; set; }
        public Nullable<int> transaction_qty { get; set; }
        public Nullable<System.DateTime> transaction_date { get; set; }
        public string Job_no { get; set; }
        public string part_no { get; set; }
        public string Rev { get; set; }
        public string transaction_by { get; set; }
        public string status { get; set; }
        public string Machine_Type { get; set; }
        public Nullable<int> Return_To_Stock_qty_ShopFloor { get; set; }
        public Nullable<int> Return_To_Scrap_qty_ShopFloor { get; set; }
        public Nullable<int> PID { get; set; }
        public string Oparator_receive_qty { get; set; }
        public Nullable<int> Operator_receive_qty { get; set; }
        public Nullable<System.DateTime> Operator_receive_date { get; set; }
        public Nullable<int> Pending_Qty { get; set; }
        public string Machine_Name { get; set; }
        public Nullable<int> Return_To_Stock_qty_Store { get; set; }
        public Nullable<int> Return_To_Scrap_qty_Store { get; set; }
        public string Remark_Shopfloor { get; set; }
        public string Remark_Store { get; set; }
    }
}
