//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UOM
    {
        public string Company { get; set; }
        public string UOMCode { get; set; }
        public string UOMDesc { get; set; }
        public bool Active { get; set; }
        public string UOMSymbol { get; set; }
        public bool AllowDecimals { get; set; }
        public int NumOfDec { get; set; }
        public string Rounding { get; set; }
        public bool GlobalUOM { get; set; }
        public bool GlobalLock { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public string AGAFIPCode { get; set; }
        public string AGCOTCode { get; set; }
        public string PESUNATCode { get; set; }
        public string MXCustomsUOM { get; set; }
        public string MXSATCode { get; set; }
    }
}
