//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Wise_Shoulder_Implant_History
    {
        public int Id { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public int User_ID { get; set; }
        public string Implant_ID { get; set; }
        public string Implant_name { get; set; }
        public string Manufacturer { get; set; }
        public string Implant_Img { get; set; }
    }
}
