//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_roles_for_Shoulder_app
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public int User_ID { get; set; }
        public string Menu_name { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> Upload_date { get; set; }
        public string Menu_icon { get; set; }
        public string Menu_Role { get; set; }
        public Nullable<bool> role_active { get; set; }
        public string Menu_link { get; set; }
    }
}
