//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_data
    {
        public int id { get; set; }
        public string name { get; set; }
        public string department { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string role { get; set; }
        public string attachment { get; set; }
        public Nullable<bool> is_deleted { get; set; }
    }
}
