//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLaborDtl
    {
        public string Company { get; set; }
        public string EmployeeNum { get; set; }
        public int LaborHedSeq { get; set; }
        public int LaborDtlSeq { get; set; }
        public string LaborType { get; set; }
        public string LaborTypePseudo { get; set; }
        public bool ReWork { get; set; }
        public string ReworkReasonCode { get; set; }
        public string JobNum { get; set; }
        public int AssemblySeq { get; set; }
        public int OprSeq { get; set; }
        public string JCDept { get; set; }
        public string ResourceGrpID { get; set; }
        public string OpCode { get; set; }
        public decimal LaborHrs { get; set; }
        public decimal BurdenHrs { get; set; }
        public decimal LaborQty { get; set; }
        public decimal ScrapQty { get; set; }
        public string ScrapReasonCode { get; set; }
        public int SetupPctComplete { get; set; }
        public bool Complete { get; set; }
        public string IndirectCode { get; set; }
        public string LaborNote { get; set; }
        public string ExpenseCode { get; set; }
        public bool LaborCollection { get; set; }
        public bool AppliedToSchedule { get; set; }
        public int ClockInMInute { get; set; }
        public int ClockOutMinute { get; set; }
        public Nullable<System.DateTime> ClockInDate { get; set; }
        public decimal ClockinTime { get; set; }
        public decimal ClockOutTime { get; set; }
        public bool ActiveTrans { get; set; }
        public decimal OverRidePayRate { get; set; }
        public decimal LaborRate { get; set; }
        public decimal BurdenRate { get; set; }
        public string DspClockInTime { get; set; }
        public string DspClockOutTime { get; set; }
        public string ResourceID { get; set; }
        public bool OpComplete { get; set; }
        public decimal EarnedHrs { get; set; }
        public bool AddedOper { get; set; }
        public Nullable<System.DateTime> PayrollDate { get; set; }
        public bool PostedToGL { get; set; }
        public int FiscalYear { get; set; }
        public int FiscalPeriod { get; set; }
        public int JournalNum { get; set; }
        public bool GLTrans { get; set; }
        public string JournalCode { get; set; }
        public bool InspectionPending { get; set; }
        public int CallNum { get; set; }
        public int CallLine { get; set; }
        public int ServNum { get; set; }
        public string ServCode { get; set; }
        public string ResReasonCode { get; set; }
        public bool WipPosted { get; set; }
        public decimal DiscrepQty { get; set; }
        public string DiscrpRsnCode { get; set; }
        public int ParentLaborDtlSeq { get; set; }
        public string LaborEntryMethod { get; set; }
        public string FiscalYearSuffix { get; set; }
        public string FiscalCalendarID { get; set; }
        public bool BFLaborReq { get; set; }
        public string ABTUID { get; set; }
        public string ProjectID { get; set; }
        public string PhaseID { get; set; }
        public string RoleCd { get; set; }
        public string TimeTypCd { get; set; }
        public int PBInvNum { get; set; }
        public int PMUID { get; set; }
        public string TaskSetID { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ClaimRef { get; set; }
        public string QuickEntryCode { get; set; }
        public string TimeStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int CreateTime { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public int ChangeTime { get; set; }
        public string ActiveTaskID { get; set; }
        public string LastTaskID { get; set; }
        public bool CreatedViaTEWeekView { get; set; }
        public string CurrentWFStageID { get; set; }
        public string WFGroupID { get; set; }
        public bool WFComplete { get; set; }
        public bool ApprovalRequired { get; set; }
        public string SubmittedBy { get; set; }
        public string PBRateFrom { get; set; }
        public string PBCurrencyCode { get; set; }
        public decimal PBHours { get; set; }
        public decimal PBChargeRate { get; set; }
        public decimal PBChargeAmt { get; set; }
        public decimal DocPBChargeRate { get; set; }
        public decimal Rpt1PBChargeRate { get; set; }
        public decimal Rpt2PBChargeRate { get; set; }
        public decimal Rpt3PBChargeRate { get; set; }
        public decimal DocPBChargeAmt { get; set; }
        public decimal Rpt1PBChargeAmt { get; set; }
        public decimal Rpt2PBChargeAmt { get; set; }
        public decimal Rpt3PBChargeAmt { get; set; }
        public int Shift { get; set; }
        public int ActID { get; set; }
        public int DtailID { get; set; }
        public bool ProjProcessed { get; set; }
        public Nullable<System.DateTime> AsOfDate { get; set; }
        public int AsOfSeq { get; set; }
        public string JDFInputFiles { get; set; }
        public string JDFNumberOfPages { get; set; }
        public string BatchWasSaved { get; set; }
        public bool AssignToBatch { get; set; }
        public bool BatchComplete { get; set; }
        public bool BatchRequestMove { get; set; }
        public bool BatchPrint { get; set; }
        public decimal BatchLaborHrs { get; set; }
        public decimal BatchPctOfTotHrs { get; set; }
        public decimal BatchQty { get; set; }
        public decimal BatchTotalExpectedHrs { get; set; }
        public string JDFOpCompleted { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public bool Downtime { get; set; }
        public string RefJobNum { get; set; }
        public int RefAssemblySeq { get; set; }
        public int RefOprSeq { get; set; }
        public bool Imported { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public bool TimeAutoSubmit { get; set; }
        public bool BatchMode { get; set; }
        public decimal BillServiceRate { get; set; }
        public decimal HCMPayHours { get; set; }
        public bool EpicorFSA { get; set; }
    }
}
