//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLRLaborDetail
    {
        public string EmployeeNum { get; set; }
        public string EmpName { get; set; }
        public string EmpStatus { get; set; }
        public int LaborHedSeq { get; set; }
        public int LaborDtlSeq { get; set; }
        public string LaborType { get; set; }
        public bool ReWork { get; set; }
        public string ReworkReasonCode { get; set; }
        public string JobNum { get; set; }
        public int OprSeq { get; set; }
        public string JCDept { get; set; }
        public string ResourceGrpID { get; set; }
        public string OpCode { get; set; }
        public bool Complete { get; set; }
        public string IndirectCode { get; set; }
        public string ExpenseCode { get; set; }
        public Nullable<System.DateTime> ClockInDate { get; set; }
        public string OpStartTime { get; set; }
        public string OpEndTime { get; set; }
        public bool OpComplete { get; set; }
        public decimal EarnedHrs { get; set; }
        public Nullable<System.DateTime> PayrollDate { get; set; }
        public string LaborNote { get; set; }
    }
}
