//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor_gatepass_data
    {
        public int ID { get; set; }
        public int PID { get; set; }
        public int MID { get; set; }
        public int visitorID { get; set; }
        public string initiator_name { get; set; }
        public string department { get; set; }
        public string visiting_person_name { get; set; }
        public Nullable<System.DateTime> visiting_date { get; set; }
        public string person_meet { get; set; }
        public string visiting_time { get; set; }
        public Nullable<int> no_of_person { get; set; }
        public string visiting_type { get; set; }
        public string purpose { get; set; }
        public Nullable<System.DateTime> uploaddate { get; set; }
        public string V_GPNO { get; set; }
        public Nullable<int> uploadby { get; set; }
        public string V_Status { get; set; }
        public Nullable<System.DateTime> In_Time { get; set; }
        public Nullable<System.DateTime> Out_Time { get; set; }
        public string ThemeColor { get; set; }
        public Nullable<bool> IsFullDay { get; set; }
        public string Representing { get; set; }
        public string Contact_No { get; set; }
        public Nullable<int> valid_upto { get; set; }
    }
}
