//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMS_DATA_FROM_DASHBOARD
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public string personId { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public string status { get; set; }
        public string Device { get; set; }
        public string DeviceNo { get; set; }
        public string PersonName { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
