//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSAttendanceShiftchangedata
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string Person_Id { get; set; }
        public string Person_Name { get; set; }
        public string Organization { get; set; }
        public string Current_Shift { get; set; }
        public string Change_Shift { get; set; }
        public Nullable<bool> Approve_By_Supervisor { get; set; }
        public Nullable<bool> Approve_By_HR { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> Upload_Date { get; set; }
        public Nullable<System.DateTime> Approve_Date_Supervisor { get; set; }
        public Nullable<System.DateTime> Approve_Date_HR { get; set; }
        public string Current_Offday { get; set; }
        public string Change_offday { get; set; }
    }
}
