//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSAttendanceShiftDetail
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public string Person_ID { get; set; }
        public string Person_Name { get; set; }
        public string Organization { get; set; }
        public string Shift_Jan { get; set; }
        public string Shift_Feb { get; set; }
        public string Shift_March { get; set; }
        public string Shift_April { get; set; }
        public string Shift_May { get; set; }
        public string Shift_June { get; set; }
        public string Shift_July { get; set; }
        public string Shift_Aug { get; set; }
        public string Shift_Sep { get; set; }
        public string Shift_Oct { get; set; }
        public string Shift_Nov { get; set; }
        public string Shift_Dec { get; set; }
        public string Offday_Jan { get; set; }
        public string Offday_Feb { get; set; }
        public string Offday_March { get; set; }
        public string Offday_April { get; set; }
        public string Offday_May { get; set; }
        public string Offday_June { get; set; }
        public string Offday_July { get; set; }
        public string Offday_Aug { get; set; }
        public string Offday_Sep { get; set; }
        public string Offday_Oct { get; set; }
        public string Offday_Nov { get; set; }
        public string Offday_Dec { get; set; }
    }
}
