//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSEmployeeDetail
    {
        public string PersonID { get; set; }
        public string Organization { get; set; }
        public string PersonName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> EffectiveTime { get; set; }
        public Nullable<System.DateTime> ExpiryTime { get; set; }
        public string cardno { get; set; }
        public string roomno { get; set; }
        public string floorno { get; set; }
        public string picture { get; set; }
        public string add1 { get; set; }
        public string add2 { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<System.DateTime> DOI { get; set; }
        public string bloodgroup { get; set; }
        public string signature { get; set; }
        public string email_address { get; set; }
        public string emp_position { get; set; }
        public string reporting_under { get; set; }
        public string bday_cards { get; set; }
        public string Approval_for_document { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> upload_date { get; set; }
        public Nullable<bool> Issue_Icard { get; set; }
        public Nullable<bool> Uniform { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Department { get; set; }
    }
}
