//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSFLEXDATAFilter
    {
        public int ID { get; set; }
        public int MID { get; set; }
        public int PID { get; set; }
        public string Organization { get; set; }
        public string Shift_1 { get; set; }
        public string Shift_2 { get; set; }
        public string Shift_3 { get; set; }
    }
}
