//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VntgStat
    {
        public string Company { get; set; }
        public string Module { get; set; }
        public Nullable<System.DateTime> RunDate { get; set; }
        public int RunTime { get; set; }
        public string DcdUserID { get; set; }
        public int ElapsedTime { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CutOffDate { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public Nullable<System.DateTime> Date01 { get; set; }
        public Nullable<System.Guid> ForeignSysRowID { get; set; }
        public byte[] UD_SysRevID { get; set; }
    }
}
