//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspection.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class who_Is_In_the_Building
    {
        public int ID { get; set; }
        public int PID { get; set; }
        public int PersonID { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string time { get; set; }
        public string Status { get; set; }
        public string personname { get; set; }
        public Nullable<int> CID { get; set; }
        public string picture_emp { get; set; }
    }
}
